/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model


import com.kcvn.spm.model.tables.AppSetting
import com.kcvn.spm.model.tables.AuthPasswordResetToken
import com.kcvn.spm.model.tables.AuthRole
import com.kcvn.spm.model.tables.AuthRoleClaim
import com.kcvn.spm.model.tables.AuthUser
import com.kcvn.spm.model.tables.AuthUserClaim
import com.kcvn.spm.model.tables.AuthUserRole
import com.kcvn.spm.model.tables.CalculateQuantityResult
import com.kcvn.spm.model.tables.CommonCategory
import com.kcvn.spm.model.tables.CompletionRateProcess
import com.kcvn.spm.model.tables.CompletionRateProcessProduct
import com.kcvn.spm.model.tables.CompletionRateProduct
import com.kcvn.spm.model.tables.InformationCalculateQuantity
import com.kcvn.spm.model.tables.InventoryProduct
import com.kcvn.spm.model.tables.Order
import com.kcvn.spm.model.tables.OrderDetail
import com.kcvn.spm.model.tables.ProcessMaster
import com.kcvn.spm.model.tables.ProcessProcedureStructure
import com.kcvn.spm.model.tables.Product
import com.kcvn.spm.model.tables.ProductProcess
import com.kcvn.spm.model.tables.SyncHistory
import com.kcvn.spm.model.tables.WorkResult

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Public : SchemaImpl("public", DefaultCatalog.DEFAULT_CATALOG) {
    public companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.app_setting</code>.
     */
    val APP_SETTING: AppSetting get() = AppSetting.APP_SETTING

    /**
     * The table <code>public.auth_password_reset_token</code>.
     */
    val AUTH_PASSWORD_RESET_TOKEN: AuthPasswordResetToken get() = AuthPasswordResetToken.AUTH_PASSWORD_RESET_TOKEN

    /**
     * The table <code>public.auth_role</code>.
     */
    val AUTH_ROLE: AuthRole get() = AuthRole.AUTH_ROLE

    /**
     * The table <code>public.auth_role_claim</code>.
     */
    val AUTH_ROLE_CLAIM: AuthRoleClaim get() = AuthRoleClaim.AUTH_ROLE_CLAIM

    /**
     * The table <code>public.auth_user</code>.
     */
    val AUTH_USER: AuthUser get() = AuthUser.AUTH_USER

    /**
     * The table <code>public.auth_user_claim</code>.
     */
    val AUTH_USER_CLAIM: AuthUserClaim get() = AuthUserClaim.AUTH_USER_CLAIM

    /**
     * The table <code>public.auth_user_role</code>.
     */
    val AUTH_USER_ROLE: AuthUserRole get() = AuthUserRole.AUTH_USER_ROLE

    /**
     * The table <code>public.calculate_quantity_result</code>.
     */
    val CALCULATE_QUANTITY_RESULT: CalculateQuantityResult get() = CalculateQuantityResult.CALCULATE_QUANTITY_RESULT

    /**
     * The table <code>public.common_category</code>.
     */
    val COMMON_CATEGORY: CommonCategory get() = CommonCategory.COMMON_CATEGORY

    /**
     * The table <code>public.completion_rate_process</code>.
     */
    val COMPLETION_RATE_PROCESS: CompletionRateProcess get() = CompletionRateProcess.COMPLETION_RATE_PROCESS

    /**
     * The table <code>public.completion_rate_process_product</code>.
     */
    val COMPLETION_RATE_PROCESS_PRODUCT: CompletionRateProcessProduct get() = CompletionRateProcessProduct.COMPLETION_RATE_PROCESS_PRODUCT

    /**
     * The table <code>public.completion_rate_product</code>.
     */
    val COMPLETION_RATE_PRODUCT: CompletionRateProduct get() = CompletionRateProduct.COMPLETION_RATE_PRODUCT

    /**
     * The table <code>public.information_calculate_quantity</code>.
     */
    val INFORMATION_CALCULATE_QUANTITY: InformationCalculateQuantity get() = InformationCalculateQuantity.INFORMATION_CALCULATE_QUANTITY

    /**
     * The table <code>public.inventory_product</code>.
     */
    val INVENTORY_PRODUCT: InventoryProduct get() = InventoryProduct.INVENTORY_PRODUCT

    /**
     * The table <code>public.order</code>.
     */
    val ORDER: Order get() = Order.ORDER

    /**
     * The table <code>public.order_detail</code>.
     */
    val ORDER_DETAIL: OrderDetail get() = OrderDetail.ORDER_DETAIL

    /**
     * The table <code>public.process_master</code>.
     */
    val PROCESS_MASTER: ProcessMaster get() = ProcessMaster.PROCESS_MASTER

    /**
     * The table <code>public.process_procedure_structure</code>.
     */
    val PROCESS_PROCEDURE_STRUCTURE: ProcessProcedureStructure get() = ProcessProcedureStructure.PROCESS_PROCEDURE_STRUCTURE

    /**
     * The table <code>public.product</code>.
     */
    val PRODUCT: Product get() = Product.PRODUCT

    /**
     * The table <code>public.product_process</code>.
     */
    val PRODUCT_PROCESS: ProductProcess get() = ProductProcess.PRODUCT_PROCESS

    /**
     * The table <code>public.sync_history</code>.
     */
    val SYNC_HISTORY: SyncHistory get() = SyncHistory.SYNC_HISTORY

    /**
     * The table <code>public.work_result</code>.
     */
    val WORK_RESULT: WorkResult get() = WorkResult.WORK_RESULT

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        AppSetting.APP_SETTING,
        AuthPasswordResetToken.AUTH_PASSWORD_RESET_TOKEN,
        AuthRole.AUTH_ROLE,
        AuthRoleClaim.AUTH_ROLE_CLAIM,
        AuthUser.AUTH_USER,
        AuthUserClaim.AUTH_USER_CLAIM,
        AuthUserRole.AUTH_USER_ROLE,
        CalculateQuantityResult.CALCULATE_QUANTITY_RESULT,
        CommonCategory.COMMON_CATEGORY,
        CompletionRateProcess.COMPLETION_RATE_PROCESS,
        CompletionRateProcessProduct.COMPLETION_RATE_PROCESS_PRODUCT,
        CompletionRateProduct.COMPLETION_RATE_PRODUCT,
        InformationCalculateQuantity.INFORMATION_CALCULATE_QUANTITY,
        InventoryProduct.INVENTORY_PRODUCT,
        Order.ORDER,
        OrderDetail.ORDER_DETAIL,
        ProcessMaster.PROCESS_MASTER,
        ProcessProcedureStructure.PROCESS_PROCEDURE_STRUCTURE,
        Product.PRODUCT,
        ProductProcess.PRODUCT_PROCESS,
        SyncHistory.SYNC_HISTORY,
        WorkResult.WORK_RESULT
    )
}
