/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables.records


import com.kcvn.spm.model.tables.Amoeba

import java.math.BigDecimal
import java.time.LocalDate
import java.time.OffsetDateTime

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record9
import org.jooq.Row9
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class AmoebaRecord() : UpdatableRecordImpl<AmoebaRecord>(Amoeba.AMOEBA), Record9<String?, LocalDate?, String?, String?, BigDecimal?, OffsetDateTime?, String?, OffsetDateTime?, String?> {

    open var id: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var inspectionDate: LocalDate?
        set(value): Unit = set(1, value)
        get(): LocalDate? = get(1) as LocalDate?

    open var poNumber: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var locationCode: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var qty: BigDecimal?
        set(value): Unit = set(4, value)
        get(): BigDecimal? = get(4) as BigDecimal?

    open var createdDate: OffsetDateTime?
        set(value): Unit = set(5, value)
        get(): OffsetDateTime? = get(5) as OffsetDateTime?

    open var createdBy: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var updatedDate: OffsetDateTime?
        set(value): Unit = set(7, value)
        get(): OffsetDateTime? = get(7) as OffsetDateTime?

    open var updatedBy: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row9<String?, LocalDate?, String?, String?, BigDecimal?, OffsetDateTime?, String?, OffsetDateTime?, String?> = super.fieldsRow() as Row9<String?, LocalDate?, String?, String?, BigDecimal?, OffsetDateTime?, String?, OffsetDateTime?, String?>
    override fun valuesRow(): Row9<String?, LocalDate?, String?, String?, BigDecimal?, OffsetDateTime?, String?, OffsetDateTime?, String?> = super.valuesRow() as Row9<String?, LocalDate?, String?, String?, BigDecimal?, OffsetDateTime?, String?, OffsetDateTime?, String?>
    override fun field1(): Field<String?> = Amoeba.AMOEBA.ID
    override fun field2(): Field<LocalDate?> = Amoeba.AMOEBA.INSPECTION_DATE
    override fun field3(): Field<String?> = Amoeba.AMOEBA.PO_NUMBER
    override fun field4(): Field<String?> = Amoeba.AMOEBA.LOCATION_CODE
    override fun field5(): Field<BigDecimal?> = Amoeba.AMOEBA.QTY
    override fun field6(): Field<OffsetDateTime?> = Amoeba.AMOEBA.CREATED_DATE
    override fun field7(): Field<String?> = Amoeba.AMOEBA.CREATED_BY
    override fun field8(): Field<OffsetDateTime?> = Amoeba.AMOEBA.UPDATED_DATE
    override fun field9(): Field<String?> = Amoeba.AMOEBA.UPDATED_BY
    override fun component1(): String? = id
    override fun component2(): LocalDate? = inspectionDate
    override fun component3(): String? = poNumber
    override fun component4(): String? = locationCode
    override fun component5(): BigDecimal? = qty
    override fun component6(): OffsetDateTime? = createdDate
    override fun component7(): String? = createdBy
    override fun component8(): OffsetDateTime? = updatedDate
    override fun component9(): String? = updatedBy
    override fun value1(): String? = id
    override fun value2(): LocalDate? = inspectionDate
    override fun value3(): String? = poNumber
    override fun value4(): String? = locationCode
    override fun value5(): BigDecimal? = qty
    override fun value6(): OffsetDateTime? = createdDate
    override fun value7(): String? = createdBy
    override fun value8(): OffsetDateTime? = updatedDate
    override fun value9(): String? = updatedBy

    override fun value1(value: String?): AmoebaRecord {
        set(0, value)
        return this
    }

    override fun value2(value: LocalDate?): AmoebaRecord {
        set(1, value)
        return this
    }

    override fun value3(value: String?): AmoebaRecord {
        set(2, value)
        return this
    }

    override fun value4(value: String?): AmoebaRecord {
        set(3, value)
        return this
    }

    override fun value5(value: BigDecimal?): AmoebaRecord {
        set(4, value)
        return this
    }

    override fun value6(value: OffsetDateTime?): AmoebaRecord {
        set(5, value)
        return this
    }

    override fun value7(value: String?): AmoebaRecord {
        set(6, value)
        return this
    }

    override fun value8(value: OffsetDateTime?): AmoebaRecord {
        set(7, value)
        return this
    }

    override fun value9(value: String?): AmoebaRecord {
        set(8, value)
        return this
    }

    override fun values(value1: String?, value2: LocalDate?, value3: String?, value4: String?, value5: BigDecimal?, value6: OffsetDateTime?, value7: String?, value8: OffsetDateTime?, value9: String?): AmoebaRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        return this
    }

    /**
     * Create a detached, initialised AmoebaRecord
     */
    constructor(id: String? = null, inspectionDate: LocalDate? = null, poNumber: String? = null, locationCode: String? = null, qty: BigDecimal? = null, createdDate: OffsetDateTime? = null, createdBy: String? = null, updatedDate: OffsetDateTime? = null, updatedBy: String? = null): this() {
        this.id = id
        this.inspectionDate = inspectionDate
        this.poNumber = poNumber
        this.locationCode = locationCode
        this.qty = qty
        this.createdDate = createdDate
        this.createdBy = createdBy
        this.updatedDate = updatedDate
        this.updatedBy = updatedBy
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised AmoebaRecord
     */
    constructor(value: com.kcvn.spm.model.tables.pojos.Amoeba?): this() {
        if (value != null) {
            this.id = value.id
            this.inspectionDate = value.inspectionDate
            this.poNumber = value.poNumber
            this.locationCode = value.locationCode
            this.qty = value.qty
            this.createdDate = value.createdDate
            this.createdBy = value.createdBy
            this.updatedDate = value.updatedDate
            this.updatedBy = value.updatedBy
            resetChangedOnNotNull()
        }
    }
}
