/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables.records


import com.kcvn.spm.model.tables.AuthUser

import java.time.LocalDate
import java.time.OffsetDateTime

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record17
import org.jooq.Row17
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class AuthUserRecord() : UpdatableRecordImpl<AuthUserRecord>(AuthUser.AUTH_USER), Record17<String?, String?, String?, String?, String?, String?, String?, String?, LocalDate?, String?, Short?, Boolean?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?> {

    open var id: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var username: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var password: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var employeeCode: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var email: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var phoneNumber: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var fullName: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var fullNameUnsigned: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var dateOfBirth: LocalDate?
        set(value): Unit = set(8, value)
        get(): LocalDate? = get(8) as LocalDate?

    open var avatar: String?
        set(value): Unit = set(9, value)
        get(): String? = get(9) as String?

    open var status: Short?
        set(value): Unit = set(10, value)
        get(): Short? = get(10) as Short?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsSuperAdmin")
    open var isSuperAdmin: Boolean?
        set(value): Unit = set(11, value)
        get(): Boolean? = get(11) as Boolean?

    open var createdDate: OffsetDateTime?
        set(value): Unit = set(12, value)
        get(): OffsetDateTime? = get(12) as OffsetDateTime?

    open var createdBy: String?
        set(value): Unit = set(13, value)
        get(): String? = get(13) as String?

    open var updatedDate: OffsetDateTime?
        set(value): Unit = set(14, value)
        get(): OffsetDateTime? = get(14) as OffsetDateTime?

    open var updatedBy: String?
        set(value): Unit = set(15, value)
        get(): String? = get(15) as String?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsDeleted")
    open var isDeleted: Boolean?
        set(value): Unit = set(16, value)
        get(): Boolean? = get(16) as Boolean?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row17<String?, String?, String?, String?, String?, String?, String?, String?, LocalDate?, String?, Short?, Boolean?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?> = super.fieldsRow() as Row17<String?, String?, String?, String?, String?, String?, String?, String?, LocalDate?, String?, Short?, Boolean?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?>
    override fun valuesRow(): Row17<String?, String?, String?, String?, String?, String?, String?, String?, LocalDate?, String?, Short?, Boolean?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?> = super.valuesRow() as Row17<String?, String?, String?, String?, String?, String?, String?, String?, LocalDate?, String?, Short?, Boolean?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?>
    override fun field1(): Field<String?> = AuthUser.AUTH_USER.ID
    override fun field2(): Field<String?> = AuthUser.AUTH_USER.USERNAME
    override fun field3(): Field<String?> = AuthUser.AUTH_USER.PASSWORD
    override fun field4(): Field<String?> = AuthUser.AUTH_USER.EMPLOYEE_CODE
    override fun field5(): Field<String?> = AuthUser.AUTH_USER.EMAIL
    override fun field6(): Field<String?> = AuthUser.AUTH_USER.PHONE_NUMBER
    override fun field7(): Field<String?> = AuthUser.AUTH_USER.FULL_NAME
    override fun field8(): Field<String?> = AuthUser.AUTH_USER.FULL_NAME_UNSIGNED
    override fun field9(): Field<LocalDate?> = AuthUser.AUTH_USER.DATE_OF_BIRTH
    override fun field10(): Field<String?> = AuthUser.AUTH_USER.AVATAR
    override fun field11(): Field<Short?> = AuthUser.AUTH_USER.STATUS
    override fun field12(): Field<Boolean?> = AuthUser.AUTH_USER.IS_SUPER_ADMIN
    override fun field13(): Field<OffsetDateTime?> = AuthUser.AUTH_USER.CREATED_DATE
    override fun field14(): Field<String?> = AuthUser.AUTH_USER.CREATED_BY
    override fun field15(): Field<OffsetDateTime?> = AuthUser.AUTH_USER.UPDATED_DATE
    override fun field16(): Field<String?> = AuthUser.AUTH_USER.UPDATED_BY
    override fun field17(): Field<Boolean?> = AuthUser.AUTH_USER.IS_DELETED
    override fun component1(): String? = id
    override fun component2(): String? = username
    override fun component3(): String? = password
    override fun component4(): String? = employeeCode
    override fun component5(): String? = email
    override fun component6(): String? = phoneNumber
    override fun component7(): String? = fullName
    override fun component8(): String? = fullNameUnsigned
    override fun component9(): LocalDate? = dateOfBirth
    override fun component10(): String? = avatar
    override fun component11(): Short? = status
    override fun component12(): Boolean? = isSuperAdmin
    override fun component13(): OffsetDateTime? = createdDate
    override fun component14(): String? = createdBy
    override fun component15(): OffsetDateTime? = updatedDate
    override fun component16(): String? = updatedBy
    override fun component17(): Boolean? = isDeleted
    override fun value1(): String? = id
    override fun value2(): String? = username
    override fun value3(): String? = password
    override fun value4(): String? = employeeCode
    override fun value5(): String? = email
    override fun value6(): String? = phoneNumber
    override fun value7(): String? = fullName
    override fun value8(): String? = fullNameUnsigned
    override fun value9(): LocalDate? = dateOfBirth
    override fun value10(): String? = avatar
    override fun value11(): Short? = status
    override fun value12(): Boolean? = isSuperAdmin
    override fun value13(): OffsetDateTime? = createdDate
    override fun value14(): String? = createdBy
    override fun value15(): OffsetDateTime? = updatedDate
    override fun value16(): String? = updatedBy
    override fun value17(): Boolean? = isDeleted

    override fun value1(value: String?): AuthUserRecord {
        set(0, value)
        return this
    }

    override fun value2(value: String?): AuthUserRecord {
        set(1, value)
        return this
    }

    override fun value3(value: String?): AuthUserRecord {
        set(2, value)
        return this
    }

    override fun value4(value: String?): AuthUserRecord {
        set(3, value)
        return this
    }

    override fun value5(value: String?): AuthUserRecord {
        set(4, value)
        return this
    }

    override fun value6(value: String?): AuthUserRecord {
        set(5, value)
        return this
    }

    override fun value7(value: String?): AuthUserRecord {
        set(6, value)
        return this
    }

    override fun value8(value: String?): AuthUserRecord {
        set(7, value)
        return this
    }

    override fun value9(value: LocalDate?): AuthUserRecord {
        set(8, value)
        return this
    }

    override fun value10(value: String?): AuthUserRecord {
        set(9, value)
        return this
    }

    override fun value11(value: Short?): AuthUserRecord {
        set(10, value)
        return this
    }

    override fun value12(value: Boolean?): AuthUserRecord {
        set(11, value)
        return this
    }

    override fun value13(value: OffsetDateTime?): AuthUserRecord {
        set(12, value)
        return this
    }

    override fun value14(value: String?): AuthUserRecord {
        set(13, value)
        return this
    }

    override fun value15(value: OffsetDateTime?): AuthUserRecord {
        set(14, value)
        return this
    }

    override fun value16(value: String?): AuthUserRecord {
        set(15, value)
        return this
    }

    override fun value17(value: Boolean?): AuthUserRecord {
        set(16, value)
        return this
    }

    override fun values(value1: String?, value2: String?, value3: String?, value4: String?, value5: String?, value6: String?, value7: String?, value8: String?, value9: LocalDate?, value10: String?, value11: Short?, value12: Boolean?, value13: OffsetDateTime?, value14: String?, value15: OffsetDateTime?, value16: String?, value17: Boolean?): AuthUserRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        this.value11(value11)
        this.value12(value12)
        this.value13(value13)
        this.value14(value14)
        this.value15(value15)
        this.value16(value16)
        this.value17(value17)
        return this
    }

    /**
     * Create a detached, initialised AuthUserRecord
     */
    constructor(id: String? = null, username: String? = null, password: String? = null, employeeCode: String? = null, email: String? = null, phoneNumber: String? = null, fullName: String? = null, fullNameUnsigned: String? = null, dateOfBirth: LocalDate? = null, avatar: String? = null, status: Short? = null, isSuperAdmin: Boolean? = null, createdDate: OffsetDateTime? = null, createdBy: String? = null, updatedDate: OffsetDateTime? = null, updatedBy: String? = null, isDeleted: Boolean? = null): this() {
        this.id = id
        this.username = username
        this.password = password
        this.employeeCode = employeeCode
        this.email = email
        this.phoneNumber = phoneNumber
        this.fullName = fullName
        this.fullNameUnsigned = fullNameUnsigned
        this.dateOfBirth = dateOfBirth
        this.avatar = avatar
        this.status = status
        this.isSuperAdmin = isSuperAdmin
        this.createdDate = createdDate
        this.createdBy = createdBy
        this.updatedDate = updatedDate
        this.updatedBy = updatedBy
        this.isDeleted = isDeleted
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised AuthUserRecord
     */
    constructor(value: com.kcvn.spm.model.tables.pojos.AuthUser?): this() {
        if (value != null) {
            this.id = value.id
            this.username = value.username
            this.password = value.password
            this.employeeCode = value.employeeCode
            this.email = value.email
            this.phoneNumber = value.phoneNumber
            this.fullName = value.fullName
            this.fullNameUnsigned = value.fullNameUnsigned
            this.dateOfBirth = value.dateOfBirth
            this.avatar = value.avatar
            this.status = value.status
            this.isSuperAdmin = value.isSuperAdmin
            this.createdDate = value.createdDate
            this.createdBy = value.createdBy
            this.updatedDate = value.updatedDate
            this.updatedBy = value.updatedBy
            this.isDeleted = value.isDeleted
            resetChangedOnNotNull()
        }
    }
}
