/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables.records


import com.kcvn.spm.model.tables.AuthPasswordResetToken

import java.time.OffsetDateTime

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record9
import org.jooq.Row9
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class AuthPasswordResetTokenRecord() : UpdatableRecordImpl<AuthPasswordResetTokenRecord>(AuthPasswordResetToken.AUTH_PASSWORD_RESET_TOKEN), Record9<String?, String?, String?, OffsetDateTime?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?> {

    open var id: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var userId: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var token: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var expiredDate: OffsetDateTime?
        set(value): Unit = set(3, value)
        get(): OffsetDateTime? = get(3) as OffsetDateTime?

    open var createdDate: OffsetDateTime?
        set(value): Unit = set(4, value)
        get(): OffsetDateTime? = get(4) as OffsetDateTime?

    open var createdBy: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var updatedDate: OffsetDateTime?
        set(value): Unit = set(6, value)
        get(): OffsetDateTime? = get(6) as OffsetDateTime?

    open var updatedBy: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsDeleted")
    open var isDeleted: Boolean?
        set(value): Unit = set(8, value)
        get(): Boolean? = get(8) as Boolean?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row9<String?, String?, String?, OffsetDateTime?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?> = super.fieldsRow() as Row9<String?, String?, String?, OffsetDateTime?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?>
    override fun valuesRow(): Row9<String?, String?, String?, OffsetDateTime?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?> = super.valuesRow() as Row9<String?, String?, String?, OffsetDateTime?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?>
    override fun field1(): Field<String?> = AuthPasswordResetToken.AUTH_PASSWORD_RESET_TOKEN.ID
    override fun field2(): Field<String?> = AuthPasswordResetToken.AUTH_PASSWORD_RESET_TOKEN.USER_ID
    override fun field3(): Field<String?> = AuthPasswordResetToken.AUTH_PASSWORD_RESET_TOKEN.TOKEN
    override fun field4(): Field<OffsetDateTime?> = AuthPasswordResetToken.AUTH_PASSWORD_RESET_TOKEN.EXPIRED_DATE
    override fun field5(): Field<OffsetDateTime?> = AuthPasswordResetToken.AUTH_PASSWORD_RESET_TOKEN.CREATED_DATE
    override fun field6(): Field<String?> = AuthPasswordResetToken.AUTH_PASSWORD_RESET_TOKEN.CREATED_BY
    override fun field7(): Field<OffsetDateTime?> = AuthPasswordResetToken.AUTH_PASSWORD_RESET_TOKEN.UPDATED_DATE
    override fun field8(): Field<String?> = AuthPasswordResetToken.AUTH_PASSWORD_RESET_TOKEN.UPDATED_BY
    override fun field9(): Field<Boolean?> = AuthPasswordResetToken.AUTH_PASSWORD_RESET_TOKEN.IS_DELETED
    override fun component1(): String? = id
    override fun component2(): String? = userId
    override fun component3(): String? = token
    override fun component4(): OffsetDateTime? = expiredDate
    override fun component5(): OffsetDateTime? = createdDate
    override fun component6(): String? = createdBy
    override fun component7(): OffsetDateTime? = updatedDate
    override fun component8(): String? = updatedBy
    override fun component9(): Boolean? = isDeleted
    override fun value1(): String? = id
    override fun value2(): String? = userId
    override fun value3(): String? = token
    override fun value4(): OffsetDateTime? = expiredDate
    override fun value5(): OffsetDateTime? = createdDate
    override fun value6(): String? = createdBy
    override fun value7(): OffsetDateTime? = updatedDate
    override fun value8(): String? = updatedBy
    override fun value9(): Boolean? = isDeleted

    override fun value1(value: String?): AuthPasswordResetTokenRecord {
        set(0, value)
        return this
    }

    override fun value2(value: String?): AuthPasswordResetTokenRecord {
        set(1, value)
        return this
    }

    override fun value3(value: String?): AuthPasswordResetTokenRecord {
        set(2, value)
        return this
    }

    override fun value4(value: OffsetDateTime?): AuthPasswordResetTokenRecord {
        set(3, value)
        return this
    }

    override fun value5(value: OffsetDateTime?): AuthPasswordResetTokenRecord {
        set(4, value)
        return this
    }

    override fun value6(value: String?): AuthPasswordResetTokenRecord {
        set(5, value)
        return this
    }

    override fun value7(value: OffsetDateTime?): AuthPasswordResetTokenRecord {
        set(6, value)
        return this
    }

    override fun value8(value: String?): AuthPasswordResetTokenRecord {
        set(7, value)
        return this
    }

    override fun value9(value: Boolean?): AuthPasswordResetTokenRecord {
        set(8, value)
        return this
    }

    override fun values(value1: String?, value2: String?, value3: String?, value4: OffsetDateTime?, value5: OffsetDateTime?, value6: String?, value7: OffsetDateTime?, value8: String?, value9: Boolean?): AuthPasswordResetTokenRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        return this
    }

    /**
     * Create a detached, initialised AuthPasswordResetTokenRecord
     */
    constructor(id: String? = null, userId: String? = null, token: String? = null, expiredDate: OffsetDateTime? = null, createdDate: OffsetDateTime? = null, createdBy: String? = null, updatedDate: OffsetDateTime? = null, updatedBy: String? = null, isDeleted: Boolean? = null): this() {
        this.id = id
        this.userId = userId
        this.token = token
        this.expiredDate = expiredDate
        this.createdDate = createdDate
        this.createdBy = createdBy
        this.updatedDate = updatedDate
        this.updatedBy = updatedBy
        this.isDeleted = isDeleted
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised AuthPasswordResetTokenRecord
     */
    constructor(value: com.kcvn.spm.model.tables.pojos.AuthPasswordResetToken?): this() {
        if (value != null) {
            this.id = value.id
            this.userId = value.userId
            this.token = value.token
            this.expiredDate = value.expiredDate
            this.createdDate = value.createdDate
            this.createdBy = value.createdBy
            this.updatedDate = value.updatedDate
            this.updatedBy = value.updatedBy
            this.isDeleted = value.isDeleted
            resetChangedOnNotNull()
        }
    }
}
