/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables.records


import com.kcvn.spm.model.tables.BacklogWhHistory

import java.math.BigDecimal
import java.time.LocalDate
import java.time.OffsetDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class BacklogWhHistoryRecord() : UpdatableRecordImpl<BacklogWhHistoryRecord>(BacklogWhHistory.BACKLOG_WH_HISTORY) {

    open var id: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var locationCode: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var poNumber: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var packageCode: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var backlogQty: BigDecimal?
        set(value): Unit = set(4, value)
        get(): BigDecimal? = get(4) as BigDecimal?

    open var boxQty: Int?
        set(value): Unit = set(5, value)
        get(): Int? = get(5) as Int?

    open var receivingDate: LocalDate?
        set(value): Unit = set(6, value)
        get(): LocalDate? = get(6) as LocalDate?

    open var inspectionDate: LocalDate?
        set(value): Unit = set(7, value)
        get(): LocalDate? = get(7) as LocalDate?

    open var transactionType: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    open var createdDate: OffsetDateTime?
        set(value): Unit = set(9, value)
        get(): OffsetDateTime? = get(9) as OffsetDateTime?

    open var createdBy: String?
        set(value): Unit = set(10, value)
        get(): String? = get(10) as String?

    open var updatedDate: OffsetDateTime?
        set(value): Unit = set(11, value)
        get(): OffsetDateTime? = get(11) as OffsetDateTime?

    open var updatedBy: String?
        set(value): Unit = set(12, value)
        get(): String? = get(12) as String?

    open var refId: String?
        set(value): Unit = set(13, value)
        get(): String? = get(13) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised BacklogWhHistoryRecord
     */
    constructor(id: String? = null, locationCode: String? = null, poNumber: String? = null, packageCode: String? = null, backlogQty: BigDecimal? = null, boxQty: Int? = null, receivingDate: LocalDate? = null, inspectionDate: LocalDate? = null, transactionType: String? = null, createdDate: OffsetDateTime? = null, createdBy: String? = null, updatedDate: OffsetDateTime? = null, updatedBy: String? = null, refId: String? = null): this() {
        this.id = id
        this.locationCode = locationCode
        this.poNumber = poNumber
        this.packageCode = packageCode
        this.backlogQty = backlogQty
        this.boxQty = boxQty
        this.receivingDate = receivingDate
        this.inspectionDate = inspectionDate
        this.transactionType = transactionType
        this.createdDate = createdDate
        this.createdBy = createdBy
        this.updatedDate = updatedDate
        this.updatedBy = updatedBy
        this.refId = refId
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised BacklogWhHistoryRecord
     */
    constructor(value: com.kcvn.spm.model.tables.pojos.BacklogWhHistory?): this() {
        if (value != null) {
            this.id = value.id
            this.locationCode = value.locationCode
            this.poNumber = value.poNumber
            this.packageCode = value.packageCode
            this.backlogQty = value.backlogQty
            this.boxQty = value.boxQty
            this.receivingDate = value.receivingDate
            this.inspectionDate = value.inspectionDate
            this.transactionType = value.transactionType
            this.createdDate = value.createdDate
            this.createdBy = value.createdBy
            this.updatedDate = value.updatedDate
            this.updatedBy = value.updatedBy
            this.refId = value.refId
            resetChangedOnNotNull()
        }
    }
}
