/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables.records


import com.kcvn.spm.model.tables.CancelReceivingTransactions

import java.time.OffsetDateTime

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record9
import org.jooq.Row9
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CancelReceivingTransactionsRecord() : UpdatableRecordImpl<CancelReceivingTransactionsRecord>(CancelReceivingTransactions.CANCEL_RECEIVING_TRANSACTIONS), Record9<String?, String?, String?, Int?, Int?, OffsetDateTime?, String?, OffsetDateTime?, String?> {

    open var id: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var locationCode: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var poNumber: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var qty: Int?
        set(value): Unit = set(3, value)
        get(): Int? = get(3) as Int?

    open var seqNo: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var createdDate: OffsetDateTime?
        set(value): Unit = set(5, value)
        get(): OffsetDateTime? = get(5) as OffsetDateTime?

    open var createdBy: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var updatedDate: OffsetDateTime?
        set(value): Unit = set(7, value)
        get(): OffsetDateTime? = get(7) as OffsetDateTime?

    open var updatedBy: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row9<String?, String?, String?, Int?, Int?, OffsetDateTime?, String?, OffsetDateTime?, String?> = super.fieldsRow() as Row9<String?, String?, String?, Int?, Int?, OffsetDateTime?, String?, OffsetDateTime?, String?>
    override fun valuesRow(): Row9<String?, String?, String?, Int?, Int?, OffsetDateTime?, String?, OffsetDateTime?, String?> = super.valuesRow() as Row9<String?, String?, String?, Int?, Int?, OffsetDateTime?, String?, OffsetDateTime?, String?>
    override fun field1(): Field<String?> = CancelReceivingTransactions.CANCEL_RECEIVING_TRANSACTIONS.ID
    override fun field2(): Field<String?> = CancelReceivingTransactions.CANCEL_RECEIVING_TRANSACTIONS.LOCATION_CODE
    override fun field3(): Field<String?> = CancelReceivingTransactions.CANCEL_RECEIVING_TRANSACTIONS.PO_NUMBER
    override fun field4(): Field<Int?> = CancelReceivingTransactions.CANCEL_RECEIVING_TRANSACTIONS.QTY
    override fun field5(): Field<Int?> = CancelReceivingTransactions.CANCEL_RECEIVING_TRANSACTIONS.SEQ_NO
    override fun field6(): Field<OffsetDateTime?> = CancelReceivingTransactions.CANCEL_RECEIVING_TRANSACTIONS.CREATED_DATE
    override fun field7(): Field<String?> = CancelReceivingTransactions.CANCEL_RECEIVING_TRANSACTIONS.CREATED_BY
    override fun field8(): Field<OffsetDateTime?> = CancelReceivingTransactions.CANCEL_RECEIVING_TRANSACTIONS.UPDATED_DATE
    override fun field9(): Field<String?> = CancelReceivingTransactions.CANCEL_RECEIVING_TRANSACTIONS.UPDATED_BY
    override fun component1(): String? = id
    override fun component2(): String? = locationCode
    override fun component3(): String? = poNumber
    override fun component4(): Int? = qty
    override fun component5(): Int? = seqNo
    override fun component6(): OffsetDateTime? = createdDate
    override fun component7(): String? = createdBy
    override fun component8(): OffsetDateTime? = updatedDate
    override fun component9(): String? = updatedBy
    override fun value1(): String? = id
    override fun value2(): String? = locationCode
    override fun value3(): String? = poNumber
    override fun value4(): Int? = qty
    override fun value5(): Int? = seqNo
    override fun value6(): OffsetDateTime? = createdDate
    override fun value7(): String? = createdBy
    override fun value8(): OffsetDateTime? = updatedDate
    override fun value9(): String? = updatedBy

    override fun value1(value: String?): CancelReceivingTransactionsRecord {
        set(0, value)
        return this
    }

    override fun value2(value: String?): CancelReceivingTransactionsRecord {
        set(1, value)
        return this
    }

    override fun value3(value: String?): CancelReceivingTransactionsRecord {
        set(2, value)
        return this
    }

    override fun value4(value: Int?): CancelReceivingTransactionsRecord {
        set(3, value)
        return this
    }

    override fun value5(value: Int?): CancelReceivingTransactionsRecord {
        set(4, value)
        return this
    }

    override fun value6(value: OffsetDateTime?): CancelReceivingTransactionsRecord {
        set(5, value)
        return this
    }

    override fun value7(value: String?): CancelReceivingTransactionsRecord {
        set(6, value)
        return this
    }

    override fun value8(value: OffsetDateTime?): CancelReceivingTransactionsRecord {
        set(7, value)
        return this
    }

    override fun value9(value: String?): CancelReceivingTransactionsRecord {
        set(8, value)
        return this
    }

    override fun values(value1: String?, value2: String?, value3: String?, value4: Int?, value5: Int?, value6: OffsetDateTime?, value7: String?, value8: OffsetDateTime?, value9: String?): CancelReceivingTransactionsRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        return this
    }

    /**
     * Create a detached, initialised CancelReceivingTransactionsRecord
     */
    constructor(id: String? = null, locationCode: String? = null, poNumber: String? = null, qty: Int? = null, seqNo: Int? = null, createdDate: OffsetDateTime? = null, createdBy: String? = null, updatedDate: OffsetDateTime? = null, updatedBy: String? = null): this() {
        this.id = id
        this.locationCode = locationCode
        this.poNumber = poNumber
        this.qty = qty
        this.seqNo = seqNo
        this.createdDate = createdDate
        this.createdBy = createdBy
        this.updatedDate = updatedDate
        this.updatedBy = updatedBy
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised CancelReceivingTransactionsRecord
     */
    constructor(value: com.kcvn.spm.model.tables.pojos.CancelReceivingTransactions?): this() {
        if (value != null) {
            this.id = value.id
            this.locationCode = value.locationCode
            this.poNumber = value.poNumber
            this.qty = value.qty
            this.seqNo = value.seqNo
            this.createdDate = value.createdDate
            this.createdBy = value.createdBy
            this.updatedDate = value.updatedDate
            this.updatedBy = value.updatedBy
            resetChangedOnNotNull()
        }
    }
}
