/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables.records


import com.kcvn.spm.model.tables.CompletionRateProcessProduct

import java.math.BigDecimal
import java.time.OffsetDateTime

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record13
import org.jooq.Row13
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CompletionRateProcessProductRecord() : UpdatableRecordImpl<CompletionRateProcessProductRecord>(CompletionRateProcessProduct.COMPLETION_RATE_PROCESS_PRODUCT), Record13<String?, String?, String?, String?, String?, BigDecimal?, OffsetDateTime?, OffsetDateTime?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?> {

    open var id: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var key: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var productNameShortcut: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var processCode: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var layerCode: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var rate: BigDecimal?
        set(value): Unit = set(5, value)
        get(): BigDecimal? = get(5) as BigDecimal?

    open var effectiveDate: OffsetDateTime?
        set(value): Unit = set(6, value)
        get(): OffsetDateTime? = get(6) as OffsetDateTime?

    open var expirationDate: OffsetDateTime?
        set(value): Unit = set(7, value)
        get(): OffsetDateTime? = get(7) as OffsetDateTime?

    open var createdDate: OffsetDateTime?
        set(value): Unit = set(8, value)
        get(): OffsetDateTime? = get(8) as OffsetDateTime?

    open var createdBy: String?
        set(value): Unit = set(9, value)
        get(): String? = get(9) as String?

    open var updatedDate: OffsetDateTime?
        set(value): Unit = set(10, value)
        get(): OffsetDateTime? = get(10) as OffsetDateTime?

    open var updatedBy: String?
        set(value): Unit = set(11, value)
        get(): String? = get(11) as String?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsDeleted")
    open var isDeleted: Boolean?
        set(value): Unit = set(12, value)
        get(): Boolean? = get(12) as Boolean?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row13<String?, String?, String?, String?, String?, BigDecimal?, OffsetDateTime?, OffsetDateTime?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?> = super.fieldsRow() as Row13<String?, String?, String?, String?, String?, BigDecimal?, OffsetDateTime?, OffsetDateTime?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?>
    override fun valuesRow(): Row13<String?, String?, String?, String?, String?, BigDecimal?, OffsetDateTime?, OffsetDateTime?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?> = super.valuesRow() as Row13<String?, String?, String?, String?, String?, BigDecimal?, OffsetDateTime?, OffsetDateTime?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?>
    override fun field1(): Field<String?> = CompletionRateProcessProduct.COMPLETION_RATE_PROCESS_PRODUCT.ID
    override fun field2(): Field<String?> = CompletionRateProcessProduct.COMPLETION_RATE_PROCESS_PRODUCT.KEY
    override fun field3(): Field<String?> = CompletionRateProcessProduct.COMPLETION_RATE_PROCESS_PRODUCT.PRODUCT_NAME_SHORTCUT
    override fun field4(): Field<String?> = CompletionRateProcessProduct.COMPLETION_RATE_PROCESS_PRODUCT.PROCESS_CODE
    override fun field5(): Field<String?> = CompletionRateProcessProduct.COMPLETION_RATE_PROCESS_PRODUCT.LAYER_CODE
    override fun field6(): Field<BigDecimal?> = CompletionRateProcessProduct.COMPLETION_RATE_PROCESS_PRODUCT.RATE
    override fun field7(): Field<OffsetDateTime?> = CompletionRateProcessProduct.COMPLETION_RATE_PROCESS_PRODUCT.EFFECTIVE_DATE
    override fun field8(): Field<OffsetDateTime?> = CompletionRateProcessProduct.COMPLETION_RATE_PROCESS_PRODUCT.EXPIRATION_DATE
    override fun field9(): Field<OffsetDateTime?> = CompletionRateProcessProduct.COMPLETION_RATE_PROCESS_PRODUCT.CREATED_DATE
    override fun field10(): Field<String?> = CompletionRateProcessProduct.COMPLETION_RATE_PROCESS_PRODUCT.CREATED_BY
    override fun field11(): Field<OffsetDateTime?> = CompletionRateProcessProduct.COMPLETION_RATE_PROCESS_PRODUCT.UPDATED_DATE
    override fun field12(): Field<String?> = CompletionRateProcessProduct.COMPLETION_RATE_PROCESS_PRODUCT.UPDATED_BY
    override fun field13(): Field<Boolean?> = CompletionRateProcessProduct.COMPLETION_RATE_PROCESS_PRODUCT.IS_DELETED
    override fun component1(): String? = id
    override fun component2(): String? = key
    override fun component3(): String? = productNameShortcut
    override fun component4(): String? = processCode
    override fun component5(): String? = layerCode
    override fun component6(): BigDecimal? = rate
    override fun component7(): OffsetDateTime? = effectiveDate
    override fun component8(): OffsetDateTime? = expirationDate
    override fun component9(): OffsetDateTime? = createdDate
    override fun component10(): String? = createdBy
    override fun component11(): OffsetDateTime? = updatedDate
    override fun component12(): String? = updatedBy
    override fun component13(): Boolean? = isDeleted
    override fun value1(): String? = id
    override fun value2(): String? = key
    override fun value3(): String? = productNameShortcut
    override fun value4(): String? = processCode
    override fun value5(): String? = layerCode
    override fun value6(): BigDecimal? = rate
    override fun value7(): OffsetDateTime? = effectiveDate
    override fun value8(): OffsetDateTime? = expirationDate
    override fun value9(): OffsetDateTime? = createdDate
    override fun value10(): String? = createdBy
    override fun value11(): OffsetDateTime? = updatedDate
    override fun value12(): String? = updatedBy
    override fun value13(): Boolean? = isDeleted

    override fun value1(value: String?): CompletionRateProcessProductRecord {
        set(0, value)
        return this
    }

    override fun value2(value: String?): CompletionRateProcessProductRecord {
        set(1, value)
        return this
    }

    override fun value3(value: String?): CompletionRateProcessProductRecord {
        set(2, value)
        return this
    }

    override fun value4(value: String?): CompletionRateProcessProductRecord {
        set(3, value)
        return this
    }

    override fun value5(value: String?): CompletionRateProcessProductRecord {
        set(4, value)
        return this
    }

    override fun value6(value: BigDecimal?): CompletionRateProcessProductRecord {
        set(5, value)
        return this
    }

    override fun value7(value: OffsetDateTime?): CompletionRateProcessProductRecord {
        set(6, value)
        return this
    }

    override fun value8(value: OffsetDateTime?): CompletionRateProcessProductRecord {
        set(7, value)
        return this
    }

    override fun value9(value: OffsetDateTime?): CompletionRateProcessProductRecord {
        set(8, value)
        return this
    }

    override fun value10(value: String?): CompletionRateProcessProductRecord {
        set(9, value)
        return this
    }

    override fun value11(value: OffsetDateTime?): CompletionRateProcessProductRecord {
        set(10, value)
        return this
    }

    override fun value12(value: String?): CompletionRateProcessProductRecord {
        set(11, value)
        return this
    }

    override fun value13(value: Boolean?): CompletionRateProcessProductRecord {
        set(12, value)
        return this
    }

    override fun values(value1: String?, value2: String?, value3: String?, value4: String?, value5: String?, value6: BigDecimal?, value7: OffsetDateTime?, value8: OffsetDateTime?, value9: OffsetDateTime?, value10: String?, value11: OffsetDateTime?, value12: String?, value13: Boolean?): CompletionRateProcessProductRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        this.value11(value11)
        this.value12(value12)
        this.value13(value13)
        return this
    }

    /**
     * Create a detached, initialised CompletionRateProcessProductRecord
     */
    constructor(id: String? = null, key: String? = null, productNameShortcut: String? = null, processCode: String? = null, layerCode: String? = null, rate: BigDecimal? = null, effectiveDate: OffsetDateTime? = null, expirationDate: OffsetDateTime? = null, createdDate: OffsetDateTime? = null, createdBy: String? = null, updatedDate: OffsetDateTime? = null, updatedBy: String? = null, isDeleted: Boolean? = null): this() {
        this.id = id
        this.key = key
        this.productNameShortcut = productNameShortcut
        this.processCode = processCode
        this.layerCode = layerCode
        this.rate = rate
        this.effectiveDate = effectiveDate
        this.expirationDate = expirationDate
        this.createdDate = createdDate
        this.createdBy = createdBy
        this.updatedDate = updatedDate
        this.updatedBy = updatedBy
        this.isDeleted = isDeleted
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised CompletionRateProcessProductRecord
     */
    constructor(value: com.kcvn.spm.model.tables.pojos.CompletionRateProcessProduct?): this() {
        if (value != null) {
            this.id = value.id
            this.key = value.key
            this.productNameShortcut = value.productNameShortcut
            this.processCode = value.processCode
            this.layerCode = value.layerCode
            this.rate = value.rate
            this.effectiveDate = value.effectiveDate
            this.expirationDate = value.expirationDate
            this.createdDate = value.createdDate
            this.createdBy = value.createdBy
            this.updatedDate = value.updatedDate
            this.updatedBy = value.updatedBy
            this.isDeleted = value.isDeleted
            resetChangedOnNotNull()
        }
    }
}
