/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables.records


import com.kcvn.spm.model.tables.EquipmentProductivity

import java.math.BigDecimal
import java.time.OffsetDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class EquipmentProductivityRecord() : UpdatableRecordImpl<EquipmentProductivityRecord>(EquipmentProductivity.EQUIPMENT_PRODUCTIVITY) {

    open var id: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var equipmentCode: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var description: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var frame_1: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var grpProcess: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var mold: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var operatingRate: BigDecimal?
        set(value): Unit = set(6, value)
        get(): BigDecimal? = get(6) as BigDecimal?

    open var time: Int?
        set(value): Unit = set(7, value)
        get(): Int? = get(7) as Int?

    open var count: BigDecimal?
        set(value): Unit = set(8, value)
        get(): BigDecimal? = get(8) as BigDecimal?

    open var task: BigDecimal?
        set(value): Unit = set(9, value)
        get(): BigDecimal? = get(9) as BigDecimal?

    open var sheetHour_100: BigDecimal?
        set(value): Unit = set(10, value)
        get(): BigDecimal? = get(10) as BigDecimal?

    open var blockSh: BigDecimal?
        set(value): Unit = set(11, value)
        get(): BigDecimal? = get(11) as BigDecimal?

    open var sltbHour: BigDecimal?
        set(value): Unit = set(12, value)
        get(): BigDecimal? = get(12) as BigDecimal?

    open var sltbSheet: BigDecimal?
        set(value): Unit = set(13, value)
        get(): BigDecimal? = get(13) as BigDecimal?

    open var sltbSet: BigDecimal?
        set(value): Unit = set(14, value)
        get(): BigDecimal? = get(14) as BigDecimal?

    open var sltbBlock: BigDecimal?
        set(value): Unit = set(15, value)
        get(): BigDecimal? = get(15) as BigDecimal?

    open var createdDate: OffsetDateTime?
        set(value): Unit = set(16, value)
        get(): OffsetDateTime? = get(16) as OffsetDateTime?

    open var createdBy: String?
        set(value): Unit = set(17, value)
        get(): String? = get(17) as String?

    open var updatedDate: OffsetDateTime?
        set(value): Unit = set(18, value)
        get(): OffsetDateTime? = get(18) as OffsetDateTime?

    open var updatedBy: String?
        set(value): Unit = set(19, value)
        get(): String? = get(19) as String?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsDeleted")
    open var isDeleted: Boolean?
        set(value): Unit = set(20, value)
        get(): Boolean? = get(20) as Boolean?

    open var capHour: BigDecimal?
        set(value): Unit = set(21, value)
        get(): BigDecimal? = get(21) as BigDecimal?

    open var capSheet: BigDecimal?
        set(value): Unit = set(22, value)
        get(): BigDecimal? = get(22) as BigDecimal?

    open var capSet: BigDecimal?
        set(value): Unit = set(23, value)
        get(): BigDecimal? = get(23) as BigDecimal?

    open var capBlock: BigDecimal?
        set(value): Unit = set(24, value)
        get(): BigDecimal? = get(24) as BigDecimal?

    open var quantityMachine: Int?
        set(value): Unit = set(25, value)
        get(): Int? = get(25) as Int?

    open var processCode: String?
        set(value): Unit = set(26, value)
        get(): String? = get(26) as String?

    open var productionStartDate: OffsetDateTime?
        set(value): Unit = set(27, value)
        get(): OffsetDateTime? = get(27) as OffsetDateTime?

    open var productionEndDate: OffsetDateTime?
        set(value): Unit = set(28, value)
        get(): OffsetDateTime? = get(28) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised EquipmentProductivityRecord
     */
    constructor(id: String? = null, equipmentCode: String? = null, description: String? = null, frame_1: String? = null, grpProcess: String? = null, mold: String? = null, operatingRate: BigDecimal? = null, time: Int? = null, count: BigDecimal? = null, task: BigDecimal? = null, sheetHour_100: BigDecimal? = null, blockSh: BigDecimal? = null, sltbHour: BigDecimal? = null, sltbSheet: BigDecimal? = null, sltbSet: BigDecimal? = null, sltbBlock: BigDecimal? = null, createdDate: OffsetDateTime? = null, createdBy: String? = null, updatedDate: OffsetDateTime? = null, updatedBy: String? = null, isDeleted: Boolean? = null, capHour: BigDecimal? = null, capSheet: BigDecimal? = null, capSet: BigDecimal? = null, capBlock: BigDecimal? = null, quantityMachine: Int? = null, processCode: String? = null, productionStartDate: OffsetDateTime? = null, productionEndDate: OffsetDateTime? = null): this() {
        this.id = id
        this.equipmentCode = equipmentCode
        this.description = description
        this.frame_1 = frame_1
        this.grpProcess = grpProcess
        this.mold = mold
        this.operatingRate = operatingRate
        this.time = time
        this.count = count
        this.task = task
        this.sheetHour_100 = sheetHour_100
        this.blockSh = blockSh
        this.sltbHour = sltbHour
        this.sltbSheet = sltbSheet
        this.sltbSet = sltbSet
        this.sltbBlock = sltbBlock
        this.createdDate = createdDate
        this.createdBy = createdBy
        this.updatedDate = updatedDate
        this.updatedBy = updatedBy
        this.isDeleted = isDeleted
        this.capHour = capHour
        this.capSheet = capSheet
        this.capSet = capSet
        this.capBlock = capBlock
        this.quantityMachine = quantityMachine
        this.processCode = processCode
        this.productionStartDate = productionStartDate
        this.productionEndDate = productionEndDate
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised EquipmentProductivityRecord
     */
    constructor(value: com.kcvn.spm.model.tables.pojos.EquipmentProductivity?): this() {
        if (value != null) {
            this.id = value.id
            this.equipmentCode = value.equipmentCode
            this.description = value.description
            this.frame_1 = value.frame_1
            this.grpProcess = value.grpProcess
            this.mold = value.mold
            this.operatingRate = value.operatingRate
            this.time = value.time
            this.count = value.count
            this.task = value.task
            this.sheetHour_100 = value.sheetHour_100
            this.blockSh = value.blockSh
            this.sltbHour = value.sltbHour
            this.sltbSheet = value.sltbSheet
            this.sltbSet = value.sltbSet
            this.sltbBlock = value.sltbBlock
            this.createdDate = value.createdDate
            this.createdBy = value.createdBy
            this.updatedDate = value.updatedDate
            this.updatedBy = value.updatedBy
            this.isDeleted = value.isDeleted
            this.capHour = value.capHour
            this.capSheet = value.capSheet
            this.capSet = value.capSet
            this.capBlock = value.capBlock
            this.quantityMachine = value.quantityMachine
            this.processCode = value.processCode
            this.productionStartDate = value.productionStartDate
            this.productionEndDate = value.productionEndDate
            resetChangedOnNotNull()
        }
    }
}
