/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables.records


import com.kcvn.spm.model.tables.InformationCalculateQuantity

import java.math.BigDecimal
import java.time.OffsetDateTime

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record15
import org.jooq.Row15
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class InformationCalculateQuantityRecord() : UpdatableRecordImpl<InformationCalculateQuantityRecord>(InformationCalculateQuantity.INFORMATION_CALCULATE_QUANTITY), Record15<String?, OffsetDateTime?, String?, String?, Int?, BigDecimal?, OffsetDateTime?, Int?, Int?, Int?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?> {

    open var id: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var monthReport: OffsetDateTime?
        set(value): Unit = set(1, value)
        get(): OffsetDateTime? = get(1) as OffsetDateTime?

    open var productName: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var processStatisticCode: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var totalQuantity: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var completionRate: BigDecimal?
        set(value): Unit = set(5, value)
        get(): BigDecimal? = get(5) as BigDecimal?

    open var orderDate: OffsetDateTime?
        set(value): Unit = set(6, value)
        get(): OffsetDateTime? = get(6) as OffsetDateTime?

    open var processCount: Int?
        set(value): Unit = set(7, value)
        get(): Int? = get(7) as Int?

    open var blockSh: Int?
        set(value): Unit = set(8, value)
        get(): Int? = get(8) as Int?

    open var blockQuantity: Int?
        set(value): Unit = set(9, value)
        get(): Int? = get(9) as Int?

    open var createdDate: OffsetDateTime?
        set(value): Unit = set(10, value)
        get(): OffsetDateTime? = get(10) as OffsetDateTime?

    open var createdBy: String?
        set(value): Unit = set(11, value)
        get(): String? = get(11) as String?

    open var updatedDate: OffsetDateTime?
        set(value): Unit = set(12, value)
        get(): OffsetDateTime? = get(12) as OffsetDateTime?

    open var updatedBy: String?
        set(value): Unit = set(13, value)
        get(): String? = get(13) as String?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsDeleted")
    open var isDeleted: Boolean?
        set(value): Unit = set(14, value)
        get(): Boolean? = get(14) as Boolean?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row15<String?, OffsetDateTime?, String?, String?, Int?, BigDecimal?, OffsetDateTime?, Int?, Int?, Int?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?> = super.fieldsRow() as Row15<String?, OffsetDateTime?, String?, String?, Int?, BigDecimal?, OffsetDateTime?, Int?, Int?, Int?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?>
    override fun valuesRow(): Row15<String?, OffsetDateTime?, String?, String?, Int?, BigDecimal?, OffsetDateTime?, Int?, Int?, Int?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?> = super.valuesRow() as Row15<String?, OffsetDateTime?, String?, String?, Int?, BigDecimal?, OffsetDateTime?, Int?, Int?, Int?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?>
    override fun field1(): Field<String?> = InformationCalculateQuantity.INFORMATION_CALCULATE_QUANTITY.ID
    override fun field2(): Field<OffsetDateTime?> = InformationCalculateQuantity.INFORMATION_CALCULATE_QUANTITY.MONTH_REPORT
    override fun field3(): Field<String?> = InformationCalculateQuantity.INFORMATION_CALCULATE_QUANTITY.PRODUCT_NAME
    override fun field4(): Field<String?> = InformationCalculateQuantity.INFORMATION_CALCULATE_QUANTITY.PROCESS_STATISTIC_CODE
    override fun field5(): Field<Int?> = InformationCalculateQuantity.INFORMATION_CALCULATE_QUANTITY.TOTAL_QUANTITY
    override fun field6(): Field<BigDecimal?> = InformationCalculateQuantity.INFORMATION_CALCULATE_QUANTITY.COMPLETION_RATE
    override fun field7(): Field<OffsetDateTime?> = InformationCalculateQuantity.INFORMATION_CALCULATE_QUANTITY.ORDER_DATE
    override fun field8(): Field<Int?> = InformationCalculateQuantity.INFORMATION_CALCULATE_QUANTITY.PROCESS_COUNT
    override fun field9(): Field<Int?> = InformationCalculateQuantity.INFORMATION_CALCULATE_QUANTITY.BLOCK_SH
    override fun field10(): Field<Int?> = InformationCalculateQuantity.INFORMATION_CALCULATE_QUANTITY.BLOCK_QUANTITY
    override fun field11(): Field<OffsetDateTime?> = InformationCalculateQuantity.INFORMATION_CALCULATE_QUANTITY.CREATED_DATE
    override fun field12(): Field<String?> = InformationCalculateQuantity.INFORMATION_CALCULATE_QUANTITY.CREATED_BY
    override fun field13(): Field<OffsetDateTime?> = InformationCalculateQuantity.INFORMATION_CALCULATE_QUANTITY.UPDATED_DATE
    override fun field14(): Field<String?> = InformationCalculateQuantity.INFORMATION_CALCULATE_QUANTITY.UPDATED_BY
    override fun field15(): Field<Boolean?> = InformationCalculateQuantity.INFORMATION_CALCULATE_QUANTITY.IS_DELETED
    override fun component1(): String? = id
    override fun component2(): OffsetDateTime? = monthReport
    override fun component3(): String? = productName
    override fun component4(): String? = processStatisticCode
    override fun component5(): Int? = totalQuantity
    override fun component6(): BigDecimal? = completionRate
    override fun component7(): OffsetDateTime? = orderDate
    override fun component8(): Int? = processCount
    override fun component9(): Int? = blockSh
    override fun component10(): Int? = blockQuantity
    override fun component11(): OffsetDateTime? = createdDate
    override fun component12(): String? = createdBy
    override fun component13(): OffsetDateTime? = updatedDate
    override fun component14(): String? = updatedBy
    override fun component15(): Boolean? = isDeleted
    override fun value1(): String? = id
    override fun value2(): OffsetDateTime? = monthReport
    override fun value3(): String? = productName
    override fun value4(): String? = processStatisticCode
    override fun value5(): Int? = totalQuantity
    override fun value6(): BigDecimal? = completionRate
    override fun value7(): OffsetDateTime? = orderDate
    override fun value8(): Int? = processCount
    override fun value9(): Int? = blockSh
    override fun value10(): Int? = blockQuantity
    override fun value11(): OffsetDateTime? = createdDate
    override fun value12(): String? = createdBy
    override fun value13(): OffsetDateTime? = updatedDate
    override fun value14(): String? = updatedBy
    override fun value15(): Boolean? = isDeleted

    override fun value1(value: String?): InformationCalculateQuantityRecord {
        set(0, value)
        return this
    }

    override fun value2(value: OffsetDateTime?): InformationCalculateQuantityRecord {
        set(1, value)
        return this
    }

    override fun value3(value: String?): InformationCalculateQuantityRecord {
        set(2, value)
        return this
    }

    override fun value4(value: String?): InformationCalculateQuantityRecord {
        set(3, value)
        return this
    }

    override fun value5(value: Int?): InformationCalculateQuantityRecord {
        set(4, value)
        return this
    }

    override fun value6(value: BigDecimal?): InformationCalculateQuantityRecord {
        set(5, value)
        return this
    }

    override fun value7(value: OffsetDateTime?): InformationCalculateQuantityRecord {
        set(6, value)
        return this
    }

    override fun value8(value: Int?): InformationCalculateQuantityRecord {
        set(7, value)
        return this
    }

    override fun value9(value: Int?): InformationCalculateQuantityRecord {
        set(8, value)
        return this
    }

    override fun value10(value: Int?): InformationCalculateQuantityRecord {
        set(9, value)
        return this
    }

    override fun value11(value: OffsetDateTime?): InformationCalculateQuantityRecord {
        set(10, value)
        return this
    }

    override fun value12(value: String?): InformationCalculateQuantityRecord {
        set(11, value)
        return this
    }

    override fun value13(value: OffsetDateTime?): InformationCalculateQuantityRecord {
        set(12, value)
        return this
    }

    override fun value14(value: String?): InformationCalculateQuantityRecord {
        set(13, value)
        return this
    }

    override fun value15(value: Boolean?): InformationCalculateQuantityRecord {
        set(14, value)
        return this
    }

    override fun values(value1: String?, value2: OffsetDateTime?, value3: String?, value4: String?, value5: Int?, value6: BigDecimal?, value7: OffsetDateTime?, value8: Int?, value9: Int?, value10: Int?, value11: OffsetDateTime?, value12: String?, value13: OffsetDateTime?, value14: String?, value15: Boolean?): InformationCalculateQuantityRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        this.value11(value11)
        this.value12(value12)
        this.value13(value13)
        this.value14(value14)
        this.value15(value15)
        return this
    }

    /**
     * Create a detached, initialised InformationCalculateQuantityRecord
     */
    constructor(id: String? = null, monthReport: OffsetDateTime? = null, productName: String? = null, processStatisticCode: String? = null, totalQuantity: Int? = null, completionRate: BigDecimal? = null, orderDate: OffsetDateTime? = null, processCount: Int? = null, blockSh: Int? = null, blockQuantity: Int? = null, createdDate: OffsetDateTime? = null, createdBy: String? = null, updatedDate: OffsetDateTime? = null, updatedBy: String? = null, isDeleted: Boolean? = null): this() {
        this.id = id
        this.monthReport = monthReport
        this.productName = productName
        this.processStatisticCode = processStatisticCode
        this.totalQuantity = totalQuantity
        this.completionRate = completionRate
        this.orderDate = orderDate
        this.processCount = processCount
        this.blockSh = blockSh
        this.blockQuantity = blockQuantity
        this.createdDate = createdDate
        this.createdBy = createdBy
        this.updatedDate = updatedDate
        this.updatedBy = updatedBy
        this.isDeleted = isDeleted
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised InformationCalculateQuantityRecord
     */
    constructor(value: com.kcvn.spm.model.tables.pojos.InformationCalculateQuantity?): this() {
        if (value != null) {
            this.id = value.id
            this.monthReport = value.monthReport
            this.productName = value.productName
            this.processStatisticCode = value.processStatisticCode
            this.totalQuantity = value.totalQuantity
            this.completionRate = value.completionRate
            this.orderDate = value.orderDate
            this.processCount = value.processCount
            this.blockSh = value.blockSh
            this.blockQuantity = value.blockQuantity
            this.createdDate = value.createdDate
            this.createdBy = value.createdBy
            this.updatedDate = value.updatedDate
            this.updatedBy = value.updatedBy
            this.isDeleted = value.isDeleted
            resetChangedOnNotNull()
        }
    }
}
