/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables.records


import com.kcvn.spm.model.tables.NewBacklogWh

import java.math.BigDecimal
import java.time.LocalDate
import java.time.OffsetDateTime

import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class NewBacklogWhRecord() : TableRecordImpl<NewBacklogWhRecord>(NewBacklogWh.NEW_BACKLOG_WH) {

    open var id: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var receivingDate: LocalDate?
        set(value): Unit = set(1, value)
        get(): LocalDate? = get(1) as LocalDate?

    open var locationCode: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var poNumber: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var packageCode: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var backlogQty: BigDecimal?
        set(value): Unit = set(5, value)
        get(): BigDecimal? = get(5) as BigDecimal?

    open var boxQty: Int?
        set(value): Unit = set(6, value)
        get(): Int? = get(6) as Int?

    open var itemName: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var lotNo: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    open var issueDate: String?
        set(value): Unit = set(9, value)
        get(): String? = get(9) as String?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsSynced")
    open var isSynced: Boolean?
        set(value): Unit = set(10, value)
        get(): Boolean? = get(10) as Boolean?

    open var createdDate: OffsetDateTime?
        set(value): Unit = set(11, value)
        get(): OffsetDateTime? = get(11) as OffsetDateTime?

    open var createdBy: String?
        set(value): Unit = set(12, value)
        get(): String? = get(12) as String?

    open var updatedDate: OffsetDateTime?
        set(value): Unit = set(13, value)
        get(): OffsetDateTime? = get(13) as OffsetDateTime?

    open var updatedBy: String?
        set(value): Unit = set(14, value)
        get(): String? = get(14) as String?

    /**
     * Create a detached, initialised NewBacklogWhRecord
     */
    constructor(id: String? = null, receivingDate: LocalDate? = null, locationCode: String? = null, poNumber: String? = null, packageCode: String? = null, backlogQty: BigDecimal? = null, boxQty: Int? = null, itemName: String? = null, lotNo: String? = null, issueDate: String? = null, isSynced: Boolean? = null, createdDate: OffsetDateTime? = null, createdBy: String? = null, updatedDate: OffsetDateTime? = null, updatedBy: String? = null): this() {
        this.id = id
        this.receivingDate = receivingDate
        this.locationCode = locationCode
        this.poNumber = poNumber
        this.packageCode = packageCode
        this.backlogQty = backlogQty
        this.boxQty = boxQty
        this.itemName = itemName
        this.lotNo = lotNo
        this.issueDate = issueDate
        this.isSynced = isSynced
        this.createdDate = createdDate
        this.createdBy = createdBy
        this.updatedDate = updatedDate
        this.updatedBy = updatedBy
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised NewBacklogWhRecord
     */
    constructor(value: com.kcvn.spm.model.tables.pojos.NewBacklogWh?): this() {
        if (value != null) {
            this.id = value.id
            this.receivingDate = value.receivingDate
            this.locationCode = value.locationCode
            this.poNumber = value.poNumber
            this.packageCode = value.packageCode
            this.backlogQty = value.backlogQty
            this.boxQty = value.boxQty
            this.itemName = value.itemName
            this.lotNo = value.lotNo
            this.issueDate = value.issueDate
            this.isSynced = value.isSynced
            this.createdDate = value.createdDate
            this.createdBy = value.createdBy
            this.updatedDate = value.updatedDate
            this.updatedBy = value.updatedBy
            resetChangedOnNotNull()
        }
    }
}
