/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables.records


import com.kcvn.spm.model.tables.Plan

import java.time.OffsetDateTime

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record16
import org.jooq.Row16
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PlanRecord() : UpdatableRecordImpl<PlanRecord>(Plan.PLAN), Record16<String?, OffsetDateTime?, OffsetDateTime?, Int?, Boolean?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?, String?, String?, Int?, Int?, Boolean?, OffsetDateTime?> {

    open var id: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var startDate: OffsetDateTime?
        set(value): Unit = set(1, value)
        get(): OffsetDateTime? = get(1) as OffsetDateTime?

    open var endDate: OffsetDateTime?
        set(value): Unit = set(2, value)
        get(): OffsetDateTime? = get(2) as OffsetDateTime?

    open var version: Int?
        set(value): Unit = set(3, value)
        get(): Int? = get(3) as Int?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsActive")
    open var isActive: Boolean?
        set(value): Unit = set(4, value)
        get(): Boolean? = get(4) as Boolean?

    open var createdDate: OffsetDateTime?
        set(value): Unit = set(5, value)
        get(): OffsetDateTime? = get(5) as OffsetDateTime?

    open var createdBy: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var updatedDate: OffsetDateTime?
        set(value): Unit = set(7, value)
        get(): OffsetDateTime? = get(7) as OffsetDateTime?

    open var updatedBy: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsDeleted")
    open var isDeleted: Boolean?
        set(value): Unit = set(9, value)
        get(): Boolean? = get(9) as Boolean?

    open var planCode: String?
        set(value): Unit = set(10, value)
        get(): String? = get(10) as String?

    open var description: String?
        set(value): Unit = set(11, value)
        get(): String? = get(11) as String?

    open var month: Int?
        set(value): Unit = set(12, value)
        get(): Int? = get(12) as Int?

    open var year: Int?
        set(value): Unit = set(13, value)
        get(): Int? = get(13) as Int?

    open var hasInventory: Boolean?
        set(value): Unit = set(14, value)
        get(): Boolean? = get(14) as Boolean?

    open var inventoryDate: OffsetDateTime?
        set(value): Unit = set(15, value)
        get(): OffsetDateTime? = get(15) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row16<String?, OffsetDateTime?, OffsetDateTime?, Int?, Boolean?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?, String?, String?, Int?, Int?, Boolean?, OffsetDateTime?> = super.fieldsRow() as Row16<String?, OffsetDateTime?, OffsetDateTime?, Int?, Boolean?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?, String?, String?, Int?, Int?, Boolean?, OffsetDateTime?>
    override fun valuesRow(): Row16<String?, OffsetDateTime?, OffsetDateTime?, Int?, Boolean?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?, String?, String?, Int?, Int?, Boolean?, OffsetDateTime?> = super.valuesRow() as Row16<String?, OffsetDateTime?, OffsetDateTime?, Int?, Boolean?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?, String?, String?, Int?, Int?, Boolean?, OffsetDateTime?>
    override fun field1(): Field<String?> = Plan.PLAN.ID
    override fun field2(): Field<OffsetDateTime?> = Plan.PLAN.START_DATE
    override fun field3(): Field<OffsetDateTime?> = Plan.PLAN.END_DATE
    override fun field4(): Field<Int?> = Plan.PLAN.VERSION
    override fun field5(): Field<Boolean?> = Plan.PLAN.IS_ACTIVE
    override fun field6(): Field<OffsetDateTime?> = Plan.PLAN.CREATED_DATE
    override fun field7(): Field<String?> = Plan.PLAN.CREATED_BY
    override fun field8(): Field<OffsetDateTime?> = Plan.PLAN.UPDATED_DATE
    override fun field9(): Field<String?> = Plan.PLAN.UPDATED_BY
    override fun field10(): Field<Boolean?> = Plan.PLAN.IS_DELETED
    override fun field11(): Field<String?> = Plan.PLAN.PLAN_CODE
    override fun field12(): Field<String?> = Plan.PLAN.DESCRIPTION
    override fun field13(): Field<Int?> = Plan.PLAN.MONTH
    override fun field14(): Field<Int?> = Plan.PLAN.YEAR
    override fun field15(): Field<Boolean?> = Plan.PLAN.HAS_INVENTORY
    override fun field16(): Field<OffsetDateTime?> = Plan.PLAN.INVENTORY_DATE
    override fun component1(): String? = id
    override fun component2(): OffsetDateTime? = startDate
    override fun component3(): OffsetDateTime? = endDate
    override fun component4(): Int? = version
    override fun component5(): Boolean? = isActive
    override fun component6(): OffsetDateTime? = createdDate
    override fun component7(): String? = createdBy
    override fun component8(): OffsetDateTime? = updatedDate
    override fun component9(): String? = updatedBy
    override fun component10(): Boolean? = isDeleted
    override fun component11(): String? = planCode
    override fun component12(): String? = description
    override fun component13(): Int? = month
    override fun component14(): Int? = year
    override fun component15(): Boolean? = hasInventory
    override fun component16(): OffsetDateTime? = inventoryDate
    override fun value1(): String? = id
    override fun value2(): OffsetDateTime? = startDate
    override fun value3(): OffsetDateTime? = endDate
    override fun value4(): Int? = version
    override fun value5(): Boolean? = isActive
    override fun value6(): OffsetDateTime? = createdDate
    override fun value7(): String? = createdBy
    override fun value8(): OffsetDateTime? = updatedDate
    override fun value9(): String? = updatedBy
    override fun value10(): Boolean? = isDeleted
    override fun value11(): String? = planCode
    override fun value12(): String? = description
    override fun value13(): Int? = month
    override fun value14(): Int? = year
    override fun value15(): Boolean? = hasInventory
    override fun value16(): OffsetDateTime? = inventoryDate

    override fun value1(value: String?): PlanRecord {
        set(0, value)
        return this
    }

    override fun value2(value: OffsetDateTime?): PlanRecord {
        set(1, value)
        return this
    }

    override fun value3(value: OffsetDateTime?): PlanRecord {
        set(2, value)
        return this
    }

    override fun value4(value: Int?): PlanRecord {
        set(3, value)
        return this
    }

    override fun value5(value: Boolean?): PlanRecord {
        set(4, value)
        return this
    }

    override fun value6(value: OffsetDateTime?): PlanRecord {
        set(5, value)
        return this
    }

    override fun value7(value: String?): PlanRecord {
        set(6, value)
        return this
    }

    override fun value8(value: OffsetDateTime?): PlanRecord {
        set(7, value)
        return this
    }

    override fun value9(value: String?): PlanRecord {
        set(8, value)
        return this
    }

    override fun value10(value: Boolean?): PlanRecord {
        set(9, value)
        return this
    }

    override fun value11(value: String?): PlanRecord {
        set(10, value)
        return this
    }

    override fun value12(value: String?): PlanRecord {
        set(11, value)
        return this
    }

    override fun value13(value: Int?): PlanRecord {
        set(12, value)
        return this
    }

    override fun value14(value: Int?): PlanRecord {
        set(13, value)
        return this
    }

    override fun value15(value: Boolean?): PlanRecord {
        set(14, value)
        return this
    }

    override fun value16(value: OffsetDateTime?): PlanRecord {
        set(15, value)
        return this
    }

    override fun values(value1: String?, value2: OffsetDateTime?, value3: OffsetDateTime?, value4: Int?, value5: Boolean?, value6: OffsetDateTime?, value7: String?, value8: OffsetDateTime?, value9: String?, value10: Boolean?, value11: String?, value12: String?, value13: Int?, value14: Int?, value15: Boolean?, value16: OffsetDateTime?): PlanRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        this.value11(value11)
        this.value12(value12)
        this.value13(value13)
        this.value14(value14)
        this.value15(value15)
        this.value16(value16)
        return this
    }

    /**
     * Create a detached, initialised PlanRecord
     */
    constructor(id: String? = null, startDate: OffsetDateTime? = null, endDate: OffsetDateTime? = null, version: Int? = null, isActive: Boolean? = null, createdDate: OffsetDateTime? = null, createdBy: String? = null, updatedDate: OffsetDateTime? = null, updatedBy: String? = null, isDeleted: Boolean? = null, planCode: String? = null, description: String? = null, month: Int? = null, year: Int? = null, hasInventory: Boolean? = null, inventoryDate: OffsetDateTime? = null): this() {
        this.id = id
        this.startDate = startDate
        this.endDate = endDate
        this.version = version
        this.isActive = isActive
        this.createdDate = createdDate
        this.createdBy = createdBy
        this.updatedDate = updatedDate
        this.updatedBy = updatedBy
        this.isDeleted = isDeleted
        this.planCode = planCode
        this.description = description
        this.month = month
        this.year = year
        this.hasInventory = hasInventory
        this.inventoryDate = inventoryDate
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised PlanRecord
     */
    constructor(value: com.kcvn.spm.model.tables.pojos.Plan?): this() {
        if (value != null) {
            this.id = value.id
            this.startDate = value.startDate
            this.endDate = value.endDate
            this.version = value.version
            this.isActive = value.isActive
            this.createdDate = value.createdDate
            this.createdBy = value.createdBy
            this.updatedDate = value.updatedDate
            this.updatedBy = value.updatedBy
            this.isDeleted = value.isDeleted
            this.planCode = value.planCode
            this.description = value.description
            this.month = value.month
            this.year = value.year
            this.hasInventory = value.hasInventory
            this.inventoryDate = value.inventoryDate
            resetChangedOnNotNull()
        }
    }
}
