/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables.records


import com.kcvn.spm.model.tables.PlanProcess

import java.math.BigDecimal
import java.time.OffsetDateTime

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record20
import org.jooq.Row20
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PlanProcessRecord() : UpdatableRecordImpl<PlanProcessRecord>(PlanProcess.PLAN_PROCESS), Record20<String?, String?, String?, String?, String?, String?, String?, BigDecimal?, Int?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?, String?, Int?, String?, String?, String?> {

    open var id: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var planId: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var planProductId: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var processCode: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var processName: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var processConvertCode: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var layerCode: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var completionRate: BigDecimal?
        set(value): Unit = set(7, value)
        get(): BigDecimal? = get(7) as BigDecimal?

    open var inventory: Int?
        set(value): Unit = set(8, value)
        get(): Int? = get(8) as Int?

    open var parentId: String?
        set(value): Unit = set(9, value)
        get(): String? = get(9) as String?

    open var createdDate: OffsetDateTime?
        set(value): Unit = set(10, value)
        get(): OffsetDateTime? = get(10) as OffsetDateTime?

    open var createdBy: String?
        set(value): Unit = set(11, value)
        get(): String? = get(11) as String?

    open var updatedDate: OffsetDateTime?
        set(value): Unit = set(12, value)
        get(): OffsetDateTime? = get(12) as OffsetDateTime?

    open var updatedBy: String?
        set(value): Unit = set(13, value)
        get(): String? = get(13) as String?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsDeleted")
    open var isDeleted: Boolean?
        set(value): Unit = set(14, value)
        get(): Boolean? = get(14) as Boolean?

    open var unit: String?
        set(value): Unit = set(15, value)
        get(): String? = get(15) as String?

    open var processSequence: Int?
        set(value): Unit = set(16, value)
        get(): Int? = get(16) as Int?

    open var processNameJp: String?
        set(value): Unit = set(17, value)
        get(): String? = get(17) as String?

    open var processGroup: String?
        set(value): Unit = set(18, value)
        get(): String? = get(18) as String?

    open var processStatisticCode: String?
        set(value): Unit = set(19, value)
        get(): String? = get(19) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    // -------------------------------------------------------------------------
    // Record20 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row20<String?, String?, String?, String?, String?, String?, String?, BigDecimal?, Int?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?, String?, Int?, String?, String?, String?> = super.fieldsRow() as Row20<String?, String?, String?, String?, String?, String?, String?, BigDecimal?, Int?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?, String?, Int?, String?, String?, String?>
    override fun valuesRow(): Row20<String?, String?, String?, String?, String?, String?, String?, BigDecimal?, Int?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?, String?, Int?, String?, String?, String?> = super.valuesRow() as Row20<String?, String?, String?, String?, String?, String?, String?, BigDecimal?, Int?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?, String?, Int?, String?, String?, String?>
    override fun field1(): Field<String?> = PlanProcess.PLAN_PROCESS.ID
    override fun field2(): Field<String?> = PlanProcess.PLAN_PROCESS.PLAN_ID
    override fun field3(): Field<String?> = PlanProcess.PLAN_PROCESS.PLAN_PRODUCT_ID
    override fun field4(): Field<String?> = PlanProcess.PLAN_PROCESS.PROCESS_CODE
    override fun field5(): Field<String?> = PlanProcess.PLAN_PROCESS.PROCESS_NAME
    override fun field6(): Field<String?> = PlanProcess.PLAN_PROCESS.PROCESS_CONVERT_CODE
    override fun field7(): Field<String?> = PlanProcess.PLAN_PROCESS.LAYER_CODE
    override fun field8(): Field<BigDecimal?> = PlanProcess.PLAN_PROCESS.COMPLETION_RATE
    override fun field9(): Field<Int?> = PlanProcess.PLAN_PROCESS.INVENTORY
    override fun field10(): Field<String?> = PlanProcess.PLAN_PROCESS.PARENT_ID
    override fun field11(): Field<OffsetDateTime?> = PlanProcess.PLAN_PROCESS.CREATED_DATE
    override fun field12(): Field<String?> = PlanProcess.PLAN_PROCESS.CREATED_BY
    override fun field13(): Field<OffsetDateTime?> = PlanProcess.PLAN_PROCESS.UPDATED_DATE
    override fun field14(): Field<String?> = PlanProcess.PLAN_PROCESS.UPDATED_BY
    override fun field15(): Field<Boolean?> = PlanProcess.PLAN_PROCESS.IS_DELETED
    override fun field16(): Field<String?> = PlanProcess.PLAN_PROCESS.UNIT
    override fun field17(): Field<Int?> = PlanProcess.PLAN_PROCESS.PROCESS_SEQUENCE
    override fun field18(): Field<String?> = PlanProcess.PLAN_PROCESS.PROCESS_NAME_JP
    override fun field19(): Field<String?> = PlanProcess.PLAN_PROCESS.PROCESS_GROUP
    override fun field20(): Field<String?> = PlanProcess.PLAN_PROCESS.PROCESS_STATISTIC_CODE
    override fun component1(): String? = id
    override fun component2(): String? = planId
    override fun component3(): String? = planProductId
    override fun component4(): String? = processCode
    override fun component5(): String? = processName
    override fun component6(): String? = processConvertCode
    override fun component7(): String? = layerCode
    override fun component8(): BigDecimal? = completionRate
    override fun component9(): Int? = inventory
    override fun component10(): String? = parentId
    override fun component11(): OffsetDateTime? = createdDate
    override fun component12(): String? = createdBy
    override fun component13(): OffsetDateTime? = updatedDate
    override fun component14(): String? = updatedBy
    override fun component15(): Boolean? = isDeleted
    override fun component16(): String? = unit
    override fun component17(): Int? = processSequence
    override fun component18(): String? = processNameJp
    override fun component19(): String? = processGroup
    override fun component20(): String? = processStatisticCode
    override fun value1(): String? = id
    override fun value2(): String? = planId
    override fun value3(): String? = planProductId
    override fun value4(): String? = processCode
    override fun value5(): String? = processName
    override fun value6(): String? = processConvertCode
    override fun value7(): String? = layerCode
    override fun value8(): BigDecimal? = completionRate
    override fun value9(): Int? = inventory
    override fun value10(): String? = parentId
    override fun value11(): OffsetDateTime? = createdDate
    override fun value12(): String? = createdBy
    override fun value13(): OffsetDateTime? = updatedDate
    override fun value14(): String? = updatedBy
    override fun value15(): Boolean? = isDeleted
    override fun value16(): String? = unit
    override fun value17(): Int? = processSequence
    override fun value18(): String? = processNameJp
    override fun value19(): String? = processGroup
    override fun value20(): String? = processStatisticCode

    override fun value1(value: String?): PlanProcessRecord {
        set(0, value)
        return this
    }

    override fun value2(value: String?): PlanProcessRecord {
        set(1, value)
        return this
    }

    override fun value3(value: String?): PlanProcessRecord {
        set(2, value)
        return this
    }

    override fun value4(value: String?): PlanProcessRecord {
        set(3, value)
        return this
    }

    override fun value5(value: String?): PlanProcessRecord {
        set(4, value)
        return this
    }

    override fun value6(value: String?): PlanProcessRecord {
        set(5, value)
        return this
    }

    override fun value7(value: String?): PlanProcessRecord {
        set(6, value)
        return this
    }

    override fun value8(value: BigDecimal?): PlanProcessRecord {
        set(7, value)
        return this
    }

    override fun value9(value: Int?): PlanProcessRecord {
        set(8, value)
        return this
    }

    override fun value10(value: String?): PlanProcessRecord {
        set(9, value)
        return this
    }

    override fun value11(value: OffsetDateTime?): PlanProcessRecord {
        set(10, value)
        return this
    }

    override fun value12(value: String?): PlanProcessRecord {
        set(11, value)
        return this
    }

    override fun value13(value: OffsetDateTime?): PlanProcessRecord {
        set(12, value)
        return this
    }

    override fun value14(value: String?): PlanProcessRecord {
        set(13, value)
        return this
    }

    override fun value15(value: Boolean?): PlanProcessRecord {
        set(14, value)
        return this
    }

    override fun value16(value: String?): PlanProcessRecord {
        set(15, value)
        return this
    }

    override fun value17(value: Int?): PlanProcessRecord {
        set(16, value)
        return this
    }

    override fun value18(value: String?): PlanProcessRecord {
        set(17, value)
        return this
    }

    override fun value19(value: String?): PlanProcessRecord {
        set(18, value)
        return this
    }

    override fun value20(value: String?): PlanProcessRecord {
        set(19, value)
        return this
    }

    override fun values(value1: String?, value2: String?, value3: String?, value4: String?, value5: String?, value6: String?, value7: String?, value8: BigDecimal?, value9: Int?, value10: String?, value11: OffsetDateTime?, value12: String?, value13: OffsetDateTime?, value14: String?, value15: Boolean?, value16: String?, value17: Int?, value18: String?, value19: String?, value20: String?): PlanProcessRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        this.value11(value11)
        this.value12(value12)
        this.value13(value13)
        this.value14(value14)
        this.value15(value15)
        this.value16(value16)
        this.value17(value17)
        this.value18(value18)
        this.value19(value19)
        this.value20(value20)
        return this
    }

    /**
     * Create a detached, initialised PlanProcessRecord
     */
    constructor(id: String? = null, planId: String? = null, planProductId: String? = null, processCode: String? = null, processName: String? = null, processConvertCode: String? = null, layerCode: String? = null, completionRate: BigDecimal? = null, inventory: Int? = null, parentId: String? = null, createdDate: OffsetDateTime? = null, createdBy: String? = null, updatedDate: OffsetDateTime? = null, updatedBy: String? = null, isDeleted: Boolean? = null, unit: String? = null, processSequence: Int? = null, processNameJp: String? = null, processGroup: String? = null, processStatisticCode: String? = null): this() {
        this.id = id
        this.planId = planId
        this.planProductId = planProductId
        this.processCode = processCode
        this.processName = processName
        this.processConvertCode = processConvertCode
        this.layerCode = layerCode
        this.completionRate = completionRate
        this.inventory = inventory
        this.parentId = parentId
        this.createdDate = createdDate
        this.createdBy = createdBy
        this.updatedDate = updatedDate
        this.updatedBy = updatedBy
        this.isDeleted = isDeleted
        this.unit = unit
        this.processSequence = processSequence
        this.processNameJp = processNameJp
        this.processGroup = processGroup
        this.processStatisticCode = processStatisticCode
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised PlanProcessRecord
     */
    constructor(value: com.kcvn.spm.model.tables.pojos.PlanProcess?): this() {
        if (value != null) {
            this.id = value.id
            this.planId = value.planId
            this.planProductId = value.planProductId
            this.processCode = value.processCode
            this.processName = value.processName
            this.processConvertCode = value.processConvertCode
            this.layerCode = value.layerCode
            this.completionRate = value.completionRate
            this.inventory = value.inventory
            this.parentId = value.parentId
            this.createdDate = value.createdDate
            this.createdBy = value.createdBy
            this.updatedDate = value.updatedDate
            this.updatedBy = value.updatedBy
            this.isDeleted = value.isDeleted
            this.unit = value.unit
            this.processSequence = value.processSequence
            this.processNameJp = value.processNameJp
            this.processGroup = value.processGroup
            this.processStatisticCode = value.processStatisticCode
            resetChangedOnNotNull()
        }
    }
}
