/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables.records


import com.kcvn.spm.model.tables.ProcessMaster

import java.math.BigDecimal
import java.time.LocalDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ProcessMasterRecord() : UpdatableRecordImpl<ProcessMasterRecord>(ProcessMaster.PROCESS_MASTER) {

    open var id: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var objectId: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var companyCode: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var grpDepartments: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var processCode: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var processName: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var processNameJp: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var grpProcess: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var grpProcessSummary: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    open var productRateByMaterial: BigDecimal?
        set(value): Unit = set(9, value)
        get(): BigDecimal? = get(9) as BigDecimal?

    open var completionRate: BigDecimal?
        set(value): Unit = set(10, value)
        get(): BigDecimal? = get(10) as BigDecimal?

    open var inputSystem: String?
        set(value): Unit = set(11, value)
        get(): String? = get(11) as String?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsActualResult")
    open var isActualResult: String?
        set(value): Unit = set(12, value)
        get(): String? = get(12) as String?

    open var officeCode: String?
        set(value): Unit = set(13, value)
        get(): String? = get(13) as String?

    open var shipmentSize: Int?
        set(value): Unit = set(14, value)
        get(): Int? = get(14) as Int?

    open var conversionFactor: BigDecimal?
        set(value): Unit = set(15, value)
        get(): BigDecimal? = get(15) as BigDecimal?

    open var unitConversionFactor: String?
        set(value): Unit = set(16, value)
        get(): String? = get(16) as String?

    open var conversionFactorsErrorType: String?
        set(value): Unit = set(17, value)
        get(): String? = get(17) as String?

    open var conversionFactorAdjustmentType: String?
        set(value): Unit = set(18, value)
        get(): String? = get(18) as String?

    open var planLeadTimeNormally: BigDecimal?
        set(value): Unit = set(19, value)
        get(): BigDecimal? = get(19) as BigDecimal?

    open var workLeadTimeNormally: BigDecimal?
        set(value): Unit = set(20, value)
        get(): BigDecimal? = get(20) as BigDecimal?

    open var transportLeadTimeNormally: BigDecimal?
        set(value): Unit = set(21, value)
        get(): BigDecimal? = get(21) as BigDecimal?

    open var planLeadTimeUrgently: BigDecimal?
        set(value): Unit = set(22, value)
        get(): BigDecimal? = get(22) as BigDecimal?

    open var workLeadTimeUrgently: BigDecimal?
        set(value): Unit = set(23, value)
        get(): BigDecimal? = get(23) as BigDecimal?

    open var transportLeadTimeUrgently: BigDecimal?
        set(value): Unit = set(24, value)
        get(): BigDecimal? = get(24) as BigDecimal?

    open var productRateByMaterialSetting: BigDecimal?
        set(value): Unit = set(25, value)
        get(): BigDecimal? = get(25) as BigDecimal?

    open var backlogType: String?
        set(value): Unit = set(26, value)
        get(): String? = get(26) as String?

    open var unfinishedProductQuantity: Int?
        set(value): Unit = set(27, value)
        get(): Int? = get(27) as Int?

    open var printType: String?
        set(value): Unit = set(28, value)
        get(): String? = get(28) as String?

    open var unfinishedProcedureType: String?
        set(value): Unit = set(29, value)
        get(): String? = get(29) as String?

    open var standardProcedureType: String?
        set(value): Unit = set(30, value)
        get(): String? = get(30) as String?

    open var checkProcessCode: String?
        set(value): Unit = set(31, value)
        get(): String? = get(31) as String?

    open var actualResultType: String?
        set(value): Unit = set(32, value)
        get(): String? = get(32) as String?

    open var leadTimeMin: BigDecimal?
        set(value): Unit = set(33, value)
        get(): BigDecimal? = get(33) as BigDecimal?

    open var wsType: String?
        set(value): Unit = set(34, value)
        get(): String? = get(34) as String?

    open var wsCode: String?
        set(value): Unit = set(35, value)
        get(): String? = get(35) as String?

    open var persons: Int?
        set(value): Unit = set(36, value)
        get(): Int? = get(36) as Int?

    open var workTime: String?
        set(value): Unit = set(37, value)
        get(): String? = get(37) as String?

    open var grpQuantity: Int?
        set(value): Unit = set(38, value)
        get(): Int? = get(38) as Int?

    open var unit: String?
        set(value): Unit = set(39, value)
        get(): String? = get(39) as String?

    open var neckFlag: String?
        set(value): Unit = set(40, value)
        get(): String? = get(40) as String?

    open var plannedProcessCode: String?
        set(value): Unit = set(41, value)
        get(): String? = get(41) as String?

    open var grpActualResult: String?
        set(value): Unit = set(42, value)
        get(): String? = get(42) as String?

    open var grpCapitalPrice: String?
        set(value): Unit = set(43, value)
        get(): String? = get(43) as String?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsExclusiveOrException")
    open var isExclusiveOrException: Int?
        set(value): Unit = set(44, value)
        get(): Int? = get(44) as Int?

    open var workplaceCode: String?
        set(value): Unit = set(45, value)
        get(): String? = get(45) as String?

    open var createdDate: LocalDateTime?
        set(value): Unit = set(46, value)
        get(): LocalDateTime? = get(46) as LocalDateTime?

    open var createdBy: String?
        set(value): Unit = set(47, value)
        get(): String? = get(47) as String?

    open var updatedDate: LocalDateTime?
        set(value): Unit = set(48, value)
        get(): LocalDateTime? = get(48) as LocalDateTime?

    open var updatedBy: String?
        set(value): Unit = set(49, value)
        get(): String? = get(49) as String?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsDeleted")
    open var isDeleted: Boolean?
        set(value): Unit = set(50, value)
        get(): Boolean? = get(50) as Boolean?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised ProcessMasterRecord
     */
    constructor(id: String? = null, objectId: Int? = null, companyCode: String? = null, grpDepartments: String? = null, processCode: String? = null, processName: String? = null, processNameJp: String? = null, grpProcess: String? = null, grpProcessSummary: String? = null, productRateByMaterial: BigDecimal? = null, completionRate: BigDecimal? = null, inputSystem: String? = null, isActualResult: String? = null, officeCode: String? = null, shipmentSize: Int? = null, conversionFactor: BigDecimal? = null, unitConversionFactor: String? = null, conversionFactorsErrorType: String? = null, conversionFactorAdjustmentType: String? = null, planLeadTimeNormally: BigDecimal? = null, workLeadTimeNormally: BigDecimal? = null, transportLeadTimeNormally: BigDecimal? = null, planLeadTimeUrgently: BigDecimal? = null, workLeadTimeUrgently: BigDecimal? = null, transportLeadTimeUrgently: BigDecimal? = null, productRateByMaterialSetting: BigDecimal? = null, backlogType: String? = null, unfinishedProductQuantity: Int? = null, printType: String? = null, unfinishedProcedureType: String? = null, standardProcedureType: String? = null, checkProcessCode: String? = null, actualResultType: String? = null, leadTimeMin: BigDecimal? = null, wsType: String? = null, wsCode: String? = null, persons: Int? = null, workTime: String? = null, grpQuantity: Int? = null, unit: String? = null, neckFlag: String? = null, plannedProcessCode: String? = null, grpActualResult: String? = null, grpCapitalPrice: String? = null, isExclusiveOrException: Int? = null, workplaceCode: String? = null, createdDate: LocalDateTime? = null, createdBy: String? = null, updatedDate: LocalDateTime? = null, updatedBy: String? = null, isDeleted: Boolean? = null): this() {
        this.id = id
        this.objectId = objectId
        this.companyCode = companyCode
        this.grpDepartments = grpDepartments
        this.processCode = processCode
        this.processName = processName
        this.processNameJp = processNameJp
        this.grpProcess = grpProcess
        this.grpProcessSummary = grpProcessSummary
        this.productRateByMaterial = productRateByMaterial
        this.completionRate = completionRate
        this.inputSystem = inputSystem
        this.isActualResult = isActualResult
        this.officeCode = officeCode
        this.shipmentSize = shipmentSize
        this.conversionFactor = conversionFactor
        this.unitConversionFactor = unitConversionFactor
        this.conversionFactorsErrorType = conversionFactorsErrorType
        this.conversionFactorAdjustmentType = conversionFactorAdjustmentType
        this.planLeadTimeNormally = planLeadTimeNormally
        this.workLeadTimeNormally = workLeadTimeNormally
        this.transportLeadTimeNormally = transportLeadTimeNormally
        this.planLeadTimeUrgently = planLeadTimeUrgently
        this.workLeadTimeUrgently = workLeadTimeUrgently
        this.transportLeadTimeUrgently = transportLeadTimeUrgently
        this.productRateByMaterialSetting = productRateByMaterialSetting
        this.backlogType = backlogType
        this.unfinishedProductQuantity = unfinishedProductQuantity
        this.printType = printType
        this.unfinishedProcedureType = unfinishedProcedureType
        this.standardProcedureType = standardProcedureType
        this.checkProcessCode = checkProcessCode
        this.actualResultType = actualResultType
        this.leadTimeMin = leadTimeMin
        this.wsType = wsType
        this.wsCode = wsCode
        this.persons = persons
        this.workTime = workTime
        this.grpQuantity = grpQuantity
        this.unit = unit
        this.neckFlag = neckFlag
        this.plannedProcessCode = plannedProcessCode
        this.grpActualResult = grpActualResult
        this.grpCapitalPrice = grpCapitalPrice
        this.isExclusiveOrException = isExclusiveOrException
        this.workplaceCode = workplaceCode
        this.createdDate = createdDate
        this.createdBy = createdBy
        this.updatedDate = updatedDate
        this.updatedBy = updatedBy
        this.isDeleted = isDeleted
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised ProcessMasterRecord
     */
    constructor(value: com.kcvn.spm.model.tables.pojos.ProcessMaster?): this() {
        if (value != null) {
            this.id = value.id
            this.objectId = value.objectId
            this.companyCode = value.companyCode
            this.grpDepartments = value.grpDepartments
            this.processCode = value.processCode
            this.processName = value.processName
            this.processNameJp = value.processNameJp
            this.grpProcess = value.grpProcess
            this.grpProcessSummary = value.grpProcessSummary
            this.productRateByMaterial = value.productRateByMaterial
            this.completionRate = value.completionRate
            this.inputSystem = value.inputSystem
            this.isActualResult = value.isActualResult
            this.officeCode = value.officeCode
            this.shipmentSize = value.shipmentSize
            this.conversionFactor = value.conversionFactor
            this.unitConversionFactor = value.unitConversionFactor
            this.conversionFactorsErrorType = value.conversionFactorsErrorType
            this.conversionFactorAdjustmentType = value.conversionFactorAdjustmentType
            this.planLeadTimeNormally = value.planLeadTimeNormally
            this.workLeadTimeNormally = value.workLeadTimeNormally
            this.transportLeadTimeNormally = value.transportLeadTimeNormally
            this.planLeadTimeUrgently = value.planLeadTimeUrgently
            this.workLeadTimeUrgently = value.workLeadTimeUrgently
            this.transportLeadTimeUrgently = value.transportLeadTimeUrgently
            this.productRateByMaterialSetting = value.productRateByMaterialSetting
            this.backlogType = value.backlogType
            this.unfinishedProductQuantity = value.unfinishedProductQuantity
            this.printType = value.printType
            this.unfinishedProcedureType = value.unfinishedProcedureType
            this.standardProcedureType = value.standardProcedureType
            this.checkProcessCode = value.checkProcessCode
            this.actualResultType = value.actualResultType
            this.leadTimeMin = value.leadTimeMin
            this.wsType = value.wsType
            this.wsCode = value.wsCode
            this.persons = value.persons
            this.workTime = value.workTime
            this.grpQuantity = value.grpQuantity
            this.unit = value.unit
            this.neckFlag = value.neckFlag
            this.plannedProcessCode = value.plannedProcessCode
            this.grpActualResult = value.grpActualResult
            this.grpCapitalPrice = value.grpCapitalPrice
            this.isExclusiveOrException = value.isExclusiveOrException
            this.workplaceCode = value.workplaceCode
            this.createdDate = value.createdDate
            this.createdBy = value.createdBy
            this.updatedDate = value.updatedDate
            this.updatedBy = value.updatedBy
            this.isDeleted = value.isDeleted
            resetChangedOnNotNull()
        }
    }
}
