/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables.records


import com.kcvn.spm.model.tables.ProcessMasterData

import java.time.OffsetDateTime

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record11
import org.jooq.Row11
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ProcessMasterDataRecord() : UpdatableRecordImpl<ProcessMasterDataRecord>(ProcessMasterData.PROCESS_MASTER_DATA), Record11<String?, String?, String?, String?, String?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?> {

    open var id: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var processCode: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var groupProcessCode: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var type: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var value: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var unit: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var createdDate: OffsetDateTime?
        set(value): Unit = set(6, value)
        get(): OffsetDateTime? = get(6) as OffsetDateTime?

    open var createdBy: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var updatedDate: OffsetDateTime?
        set(value): Unit = set(8, value)
        get(): OffsetDateTime? = get(8) as OffsetDateTime?

    open var updatedBy: String?
        set(value): Unit = set(9, value)
        get(): String? = get(9) as String?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsDeleted")
    open var isDeleted: Boolean?
        set(value): Unit = set(10, value)
        get(): Boolean? = get(10) as Boolean?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row11<String?, String?, String?, String?, String?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?> = super.fieldsRow() as Row11<String?, String?, String?, String?, String?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?>
    override fun valuesRow(): Row11<String?, String?, String?, String?, String?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?> = super.valuesRow() as Row11<String?, String?, String?, String?, String?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?>
    override fun field1(): Field<String?> = ProcessMasterData.PROCESS_MASTER_DATA.ID
    override fun field2(): Field<String?> = ProcessMasterData.PROCESS_MASTER_DATA.PROCESS_CODE
    override fun field3(): Field<String?> = ProcessMasterData.PROCESS_MASTER_DATA.GROUP_PROCESS_CODE
    override fun field4(): Field<String?> = ProcessMasterData.PROCESS_MASTER_DATA.TYPE
    override fun field5(): Field<String?> = ProcessMasterData.PROCESS_MASTER_DATA.VALUE
    override fun field6(): Field<String?> = ProcessMasterData.PROCESS_MASTER_DATA.UNIT
    override fun field7(): Field<OffsetDateTime?> = ProcessMasterData.PROCESS_MASTER_DATA.CREATED_DATE
    override fun field8(): Field<String?> = ProcessMasterData.PROCESS_MASTER_DATA.CREATED_BY
    override fun field9(): Field<OffsetDateTime?> = ProcessMasterData.PROCESS_MASTER_DATA.UPDATED_DATE
    override fun field10(): Field<String?> = ProcessMasterData.PROCESS_MASTER_DATA.UPDATED_BY
    override fun field11(): Field<Boolean?> = ProcessMasterData.PROCESS_MASTER_DATA.IS_DELETED
    override fun component1(): String? = id
    override fun component2(): String? = processCode
    override fun component3(): String? = groupProcessCode
    override fun component4(): String? = type
    override fun component5(): String? = value
    override fun component6(): String? = unit
    override fun component7(): OffsetDateTime? = createdDate
    override fun component8(): String? = createdBy
    override fun component9(): OffsetDateTime? = updatedDate
    override fun component10(): String? = updatedBy
    override fun component11(): Boolean? = isDeleted
    override fun value1(): String? = id
    override fun value2(): String? = processCode
    override fun value3(): String? = groupProcessCode
    override fun value4(): String? = type
    override fun value5(): String? = value
    override fun value6(): String? = unit
    override fun value7(): OffsetDateTime? = createdDate
    override fun value8(): String? = createdBy
    override fun value9(): OffsetDateTime? = updatedDate
    override fun value10(): String? = updatedBy
    override fun value11(): Boolean? = isDeleted

    override fun value1(value: String?): ProcessMasterDataRecord {
        set(0, value)
        return this
    }

    override fun value2(value: String?): ProcessMasterDataRecord {
        set(1, value)
        return this
    }

    override fun value3(value: String?): ProcessMasterDataRecord {
        set(2, value)
        return this
    }

    override fun value4(value: String?): ProcessMasterDataRecord {
        set(3, value)
        return this
    }

    override fun value5(value: String?): ProcessMasterDataRecord {
        set(4, value)
        return this
    }

    override fun value6(value: String?): ProcessMasterDataRecord {
        set(5, value)
        return this
    }

    override fun value7(value: OffsetDateTime?): ProcessMasterDataRecord {
        set(6, value)
        return this
    }

    override fun value8(value: String?): ProcessMasterDataRecord {
        set(7, value)
        return this
    }

    override fun value9(value: OffsetDateTime?): ProcessMasterDataRecord {
        set(8, value)
        return this
    }

    override fun value10(value: String?): ProcessMasterDataRecord {
        set(9, value)
        return this
    }

    override fun value11(value: Boolean?): ProcessMasterDataRecord {
        set(10, value)
        return this
    }

    override fun values(value1: String?, value2: String?, value3: String?, value4: String?, value5: String?, value6: String?, value7: OffsetDateTime?, value8: String?, value9: OffsetDateTime?, value10: String?, value11: Boolean?): ProcessMasterDataRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        this.value11(value11)
        return this
    }

    /**
     * Create a detached, initialised ProcessMasterDataRecord
     */
    constructor(id: String? = null, processCode: String? = null, groupProcessCode: String? = null, type: String? = null, value: String? = null, unit: String? = null, createdDate: OffsetDateTime? = null, createdBy: String? = null, updatedDate: OffsetDateTime? = null, updatedBy: String? = null, isDeleted: Boolean? = null): this() {
        this.id = id
        this.processCode = processCode
        this.groupProcessCode = groupProcessCode
        this.type = type
        this.value = value
        this.unit = unit
        this.createdDate = createdDate
        this.createdBy = createdBy
        this.updatedDate = updatedDate
        this.updatedBy = updatedBy
        this.isDeleted = isDeleted
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised ProcessMasterDataRecord
     */
    constructor(value: com.kcvn.spm.model.tables.pojos.ProcessMasterData?): this() {
        if (value != null) {
            this.id = value.id
            this.processCode = value.processCode
            this.groupProcessCode = value.groupProcessCode
            this.type = value.type
            this.value = value.value
            this.unit = value.unit
            this.createdDate = value.createdDate
            this.createdBy = value.createdBy
            this.updatedDate = value.updatedDate
            this.updatedBy = value.updatedBy
            this.isDeleted = value.isDeleted
            resetChangedOnNotNull()
        }
    }
}
