/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables.records


import com.kcvn.spm.model.tables.Product

import java.time.OffsetDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ProductRecord() : UpdatableRecordImpl<ProductRecord>(Product.PRODUCT) {

    open var id: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var name: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var exportType: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var size: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var frame_1: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var frame_2: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var mold: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var productLine: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var srNosr: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    open var pcsSh: Int?
        set(value): Unit = set(9, value)
        get(): Int? = get(9) as Int?

    open var shBlock: Int?
        set(value): Unit = set(10, value)
        get(): Int? = get(10) as Int?

    open var layerCount: Int?
        set(value): Unit = set(11, value)
        get(): Int? = get(11) as Int?

    open var ringJig: String?
        set(value): Unit = set(12, value)
        get(): String? = get(12) as String?

    open var process: Int?
        set(value): Unit = set(13, value)
        get(): Int? = get(13) as Int?

    open var snapMold: String?
        set(value): Unit = set(14, value)
        get(): String? = get(14) as String?

    open var tapeCommon: String?
        set(value): Unit = set(15, value)
        get(): String? = get(15) as String?

    open var tapeType: String?
        set(value): Unit = set(16, value)
        get(): String? = get(16) as String?

    open var productLayerDetail: String?
        set(value): Unit = set(17, value)
        get(): String? = get(17) as String?

    open var createdDate: OffsetDateTime?
        set(value): Unit = set(18, value)
        get(): OffsetDateTime? = get(18) as OffsetDateTime?

    open var createdBy: String?
        set(value): Unit = set(19, value)
        get(): String? = get(19) as String?

    open var updatedDate: OffsetDateTime?
        set(value): Unit = set(20, value)
        get(): OffsetDateTime? = get(20) as OffsetDateTime?

    open var updatedBy: String?
        set(value): Unit = set(21, value)
        get(): String? = get(21) as String?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsDeleted")
    open var isDeleted: Boolean?
        set(value): Unit = set(22, value)
        get(): Boolean? = get(22) as Boolean?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised ProductRecord
     */
    constructor(id: String? = null, name: String? = null, exportType: String? = null, size: String? = null, frame_1: String? = null, frame_2: String? = null, mold: String? = null, productLine: String? = null, srNosr: String? = null, pcsSh: Int? = null, shBlock: Int? = null, layerCount: Int? = null, ringJig: String? = null, process: Int? = null, snapMold: String? = null, tapeCommon: String? = null, tapeType: String? = null, productLayerDetail: String? = null, createdDate: OffsetDateTime? = null, createdBy: String? = null, updatedDate: OffsetDateTime? = null, updatedBy: String? = null, isDeleted: Boolean? = null): this() {
        this.id = id
        this.name = name
        this.exportType = exportType
        this.size = size
        this.frame_1 = frame_1
        this.frame_2 = frame_2
        this.mold = mold
        this.productLine = productLine
        this.srNosr = srNosr
        this.pcsSh = pcsSh
        this.shBlock = shBlock
        this.layerCount = layerCount
        this.ringJig = ringJig
        this.process = process
        this.snapMold = snapMold
        this.tapeCommon = tapeCommon
        this.tapeType = tapeType
        this.productLayerDetail = productLayerDetail
        this.createdDate = createdDate
        this.createdBy = createdBy
        this.updatedDate = updatedDate
        this.updatedBy = updatedBy
        this.isDeleted = isDeleted
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised ProductRecord
     */
    constructor(value: com.kcvn.spm.model.tables.pojos.Product?): this() {
        if (value != null) {
            this.id = value.id
            this.name = value.name
            this.exportType = value.exportType
            this.size = value.size
            this.frame_1 = value.frame_1
            this.frame_2 = value.frame_2
            this.mold = value.mold
            this.productLine = value.productLine
            this.srNosr = value.srNosr
            this.pcsSh = value.pcsSh
            this.shBlock = value.shBlock
            this.layerCount = value.layerCount
            this.ringJig = value.ringJig
            this.process = value.process
            this.snapMold = value.snapMold
            this.tapeCommon = value.tapeCommon
            this.tapeType = value.tapeType
            this.productLayerDetail = value.productLayerDetail
            this.createdDate = value.createdDate
            this.createdBy = value.createdBy
            this.updatedDate = value.updatedDate
            this.updatedBy = value.updatedBy
            this.isDeleted = value.isDeleted
            resetChangedOnNotNull()
        }
    }
}
