/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables.records


import com.kcvn.spm.model.tables.ProductProcess

import java.time.LocalDateTime

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record14
import org.jooq.Row14
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ProductProcessRecord() : UpdatableRecordImpl<ProductProcessRecord>(ProductProcess.PRODUCT_PROCESS), Record14<String?, String?, String?, String?, String?, String?, String?, String?, String?, LocalDateTime?, String?, LocalDateTime?, String?, Boolean?> {

    open var id: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var productName: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var layerCode: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var processCode: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var processName: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var processNameJp: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var processConvertCode: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var processStatisticCode: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var processInventoryCode: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    open var createdDate: LocalDateTime?
        set(value): Unit = set(9, value)
        get(): LocalDateTime? = get(9) as LocalDateTime?

    open var createdBy: String?
        set(value): Unit = set(10, value)
        get(): String? = get(10) as String?

    open var updatedDate: LocalDateTime?
        set(value): Unit = set(11, value)
        get(): LocalDateTime? = get(11) as LocalDateTime?

    open var updatedBy: String?
        set(value): Unit = set(12, value)
        get(): String? = get(12) as String?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsDeleted")
    open var isDeleted: Boolean?
        set(value): Unit = set(13, value)
        get(): Boolean? = get(13) as Boolean?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row14<String?, String?, String?, String?, String?, String?, String?, String?, String?, LocalDateTime?, String?, LocalDateTime?, String?, Boolean?> = super.fieldsRow() as Row14<String?, String?, String?, String?, String?, String?, String?, String?, String?, LocalDateTime?, String?, LocalDateTime?, String?, Boolean?>
    override fun valuesRow(): Row14<String?, String?, String?, String?, String?, String?, String?, String?, String?, LocalDateTime?, String?, LocalDateTime?, String?, Boolean?> = super.valuesRow() as Row14<String?, String?, String?, String?, String?, String?, String?, String?, String?, LocalDateTime?, String?, LocalDateTime?, String?, Boolean?>
    override fun field1(): Field<String?> = ProductProcess.PRODUCT_PROCESS.ID
    override fun field2(): Field<String?> = ProductProcess.PRODUCT_PROCESS.PRODUCT_NAME
    override fun field3(): Field<String?> = ProductProcess.PRODUCT_PROCESS.LAYER_CODE
    override fun field4(): Field<String?> = ProductProcess.PRODUCT_PROCESS.PROCESS_CODE
    override fun field5(): Field<String?> = ProductProcess.PRODUCT_PROCESS.PROCESS_NAME
    override fun field6(): Field<String?> = ProductProcess.PRODUCT_PROCESS.PROCESS_NAME_JP
    override fun field7(): Field<String?> = ProductProcess.PRODUCT_PROCESS.PROCESS_CONVERT_CODE
    override fun field8(): Field<String?> = ProductProcess.PRODUCT_PROCESS.PROCESS_STATISTIC_CODE
    override fun field9(): Field<String?> = ProductProcess.PRODUCT_PROCESS.PROCESS_INVENTORY_CODE
    override fun field10(): Field<LocalDateTime?> = ProductProcess.PRODUCT_PROCESS.CREATED_DATE
    override fun field11(): Field<String?> = ProductProcess.PRODUCT_PROCESS.CREATED_BY
    override fun field12(): Field<LocalDateTime?> = ProductProcess.PRODUCT_PROCESS.UPDATED_DATE
    override fun field13(): Field<String?> = ProductProcess.PRODUCT_PROCESS.UPDATED_BY
    override fun field14(): Field<Boolean?> = ProductProcess.PRODUCT_PROCESS.IS_DELETED
    override fun component1(): String? = id
    override fun component2(): String? = productName
    override fun component3(): String? = layerCode
    override fun component4(): String? = processCode
    override fun component5(): String? = processName
    override fun component6(): String? = processNameJp
    override fun component7(): String? = processConvertCode
    override fun component8(): String? = processStatisticCode
    override fun component9(): String? = processInventoryCode
    override fun component10(): LocalDateTime? = createdDate
    override fun component11(): String? = createdBy
    override fun component12(): LocalDateTime? = updatedDate
    override fun component13(): String? = updatedBy
    override fun component14(): Boolean? = isDeleted
    override fun value1(): String? = id
    override fun value2(): String? = productName
    override fun value3(): String? = layerCode
    override fun value4(): String? = processCode
    override fun value5(): String? = processName
    override fun value6(): String? = processNameJp
    override fun value7(): String? = processConvertCode
    override fun value8(): String? = processStatisticCode
    override fun value9(): String? = processInventoryCode
    override fun value10(): LocalDateTime? = createdDate
    override fun value11(): String? = createdBy
    override fun value12(): LocalDateTime? = updatedDate
    override fun value13(): String? = updatedBy
    override fun value14(): Boolean? = isDeleted

    override fun value1(value: String?): ProductProcessRecord {
        set(0, value)
        return this
    }

    override fun value2(value: String?): ProductProcessRecord {
        set(1, value)
        return this
    }

    override fun value3(value: String?): ProductProcessRecord {
        set(2, value)
        return this
    }

    override fun value4(value: String?): ProductProcessRecord {
        set(3, value)
        return this
    }

    override fun value5(value: String?): ProductProcessRecord {
        set(4, value)
        return this
    }

    override fun value6(value: String?): ProductProcessRecord {
        set(5, value)
        return this
    }

    override fun value7(value: String?): ProductProcessRecord {
        set(6, value)
        return this
    }

    override fun value8(value: String?): ProductProcessRecord {
        set(7, value)
        return this
    }

    override fun value9(value: String?): ProductProcessRecord {
        set(8, value)
        return this
    }

    override fun value10(value: LocalDateTime?): ProductProcessRecord {
        set(9, value)
        return this
    }

    override fun value11(value: String?): ProductProcessRecord {
        set(10, value)
        return this
    }

    override fun value12(value: LocalDateTime?): ProductProcessRecord {
        set(11, value)
        return this
    }

    override fun value13(value: String?): ProductProcessRecord {
        set(12, value)
        return this
    }

    override fun value14(value: Boolean?): ProductProcessRecord {
        set(13, value)
        return this
    }

    override fun values(value1: String?, value2: String?, value3: String?, value4: String?, value5: String?, value6: String?, value7: String?, value8: String?, value9: String?, value10: LocalDateTime?, value11: String?, value12: LocalDateTime?, value13: String?, value14: Boolean?): ProductProcessRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        this.value11(value11)
        this.value12(value12)
        this.value13(value13)
        this.value14(value14)
        return this
    }

    /**
     * Create a detached, initialised ProductProcessRecord
     */
    constructor(id: String? = null, productName: String? = null, layerCode: String? = null, processCode: String? = null, processName: String? = null, processNameJp: String? = null, processConvertCode: String? = null, processStatisticCode: String? = null, processInventoryCode: String? = null, createdDate: LocalDateTime? = null, createdBy: String? = null, updatedDate: LocalDateTime? = null, updatedBy: String? = null, isDeleted: Boolean? = null): this() {
        this.id = id
        this.productName = productName
        this.layerCode = layerCode
        this.processCode = processCode
        this.processName = processName
        this.processNameJp = processNameJp
        this.processConvertCode = processConvertCode
        this.processStatisticCode = processStatisticCode
        this.processInventoryCode = processInventoryCode
        this.createdDate = createdDate
        this.createdBy = createdBy
        this.updatedDate = updatedDate
        this.updatedBy = updatedBy
        this.isDeleted = isDeleted
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised ProductProcessRecord
     */
    constructor(value: com.kcvn.spm.model.tables.pojos.ProductProcess?): this() {
        if (value != null) {
            this.id = value.id
            this.productName = value.productName
            this.layerCode = value.layerCode
            this.processCode = value.processCode
            this.processName = value.processName
            this.processNameJp = value.processNameJp
            this.processConvertCode = value.processConvertCode
            this.processStatisticCode = value.processStatisticCode
            this.processInventoryCode = value.processInventoryCode
            this.createdDate = value.createdDate
            this.createdBy = value.createdBy
            this.updatedDate = value.updatedDate
            this.updatedBy = value.updatedBy
            this.isDeleted = value.isDeleted
            resetChangedOnNotNull()
        }
    }
}
