/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables.records


import com.kcvn.spm.model.tables.ReceivingTransactions

import java.math.BigDecimal
import java.time.OffsetDateTime

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record13
import org.jooq.Row13
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ReceivingTransactionsRecord() : UpdatableRecordImpl<ReceivingTransactionsRecord>(ReceivingTransactions.RECEIVING_TRANSACTIONS), Record13<String?, String?, String?, String?, String?, String?, BigDecimal?, Int?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?> {

    open var id: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var sourceLocationCode: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var destLocationCode: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var sourcePackageCode: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var destPackageCode: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var poNumber: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var qty: BigDecimal?
        set(value): Unit = set(6, value)
        get(): BigDecimal? = get(6) as BigDecimal?

    open var seqNo: Int?
        set(value): Unit = set(7, value)
        get(): Int? = get(7) as Int?

    open var createdDate: OffsetDateTime?
        set(value): Unit = set(8, value)
        get(): OffsetDateTime? = get(8) as OffsetDateTime?

    open var createdBy: String?
        set(value): Unit = set(9, value)
        get(): String? = get(9) as String?

    open var updatedDate: OffsetDateTime?
        set(value): Unit = set(10, value)
        get(): OffsetDateTime? = get(10) as OffsetDateTime?

    open var updatedBy: String?
        set(value): Unit = set(11, value)
        get(): String? = get(11) as String?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsCanceled")
    open var isCanceled: Boolean?
        set(value): Unit = set(12, value)
        get(): Boolean? = get(12) as Boolean?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row13<String?, String?, String?, String?, String?, String?, BigDecimal?, Int?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?> = super.fieldsRow() as Row13<String?, String?, String?, String?, String?, String?, BigDecimal?, Int?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?>
    override fun valuesRow(): Row13<String?, String?, String?, String?, String?, String?, BigDecimal?, Int?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?> = super.valuesRow() as Row13<String?, String?, String?, String?, String?, String?, BigDecimal?, Int?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?>
    override fun field1(): Field<String?> = ReceivingTransactions.RECEIVING_TRANSACTIONS.ID
    override fun field2(): Field<String?> = ReceivingTransactions.RECEIVING_TRANSACTIONS.SOURCE_LOCATION_CODE
    override fun field3(): Field<String?> = ReceivingTransactions.RECEIVING_TRANSACTIONS.DEST_LOCATION_CODE
    override fun field4(): Field<String?> = ReceivingTransactions.RECEIVING_TRANSACTIONS.SOURCE_PACKAGE_CODE
    override fun field5(): Field<String?> = ReceivingTransactions.RECEIVING_TRANSACTIONS.DEST_PACKAGE_CODE
    override fun field6(): Field<String?> = ReceivingTransactions.RECEIVING_TRANSACTIONS.PO_NUMBER
    override fun field7(): Field<BigDecimal?> = ReceivingTransactions.RECEIVING_TRANSACTIONS.QTY
    override fun field8(): Field<Int?> = ReceivingTransactions.RECEIVING_TRANSACTIONS.SEQ_NO
    override fun field9(): Field<OffsetDateTime?> = ReceivingTransactions.RECEIVING_TRANSACTIONS.CREATED_DATE
    override fun field10(): Field<String?> = ReceivingTransactions.RECEIVING_TRANSACTIONS.CREATED_BY
    override fun field11(): Field<OffsetDateTime?> = ReceivingTransactions.RECEIVING_TRANSACTIONS.UPDATED_DATE
    override fun field12(): Field<String?> = ReceivingTransactions.RECEIVING_TRANSACTIONS.UPDATED_BY
    override fun field13(): Field<Boolean?> = ReceivingTransactions.RECEIVING_TRANSACTIONS.IS_CANCELED
    override fun component1(): String? = id
    override fun component2(): String? = sourceLocationCode
    override fun component3(): String? = destLocationCode
    override fun component4(): String? = sourcePackageCode
    override fun component5(): String? = destPackageCode
    override fun component6(): String? = poNumber
    override fun component7(): BigDecimal? = qty
    override fun component8(): Int? = seqNo
    override fun component9(): OffsetDateTime? = createdDate
    override fun component10(): String? = createdBy
    override fun component11(): OffsetDateTime? = updatedDate
    override fun component12(): String? = updatedBy
    override fun component13(): Boolean? = isCanceled
    override fun value1(): String? = id
    override fun value2(): String? = sourceLocationCode
    override fun value3(): String? = destLocationCode
    override fun value4(): String? = sourcePackageCode
    override fun value5(): String? = destPackageCode
    override fun value6(): String? = poNumber
    override fun value7(): BigDecimal? = qty
    override fun value8(): Int? = seqNo
    override fun value9(): OffsetDateTime? = createdDate
    override fun value10(): String? = createdBy
    override fun value11(): OffsetDateTime? = updatedDate
    override fun value12(): String? = updatedBy
    override fun value13(): Boolean? = isCanceled

    override fun value1(value: String?): ReceivingTransactionsRecord {
        set(0, value)
        return this
    }

    override fun value2(value: String?): ReceivingTransactionsRecord {
        set(1, value)
        return this
    }

    override fun value3(value: String?): ReceivingTransactionsRecord {
        set(2, value)
        return this
    }

    override fun value4(value: String?): ReceivingTransactionsRecord {
        set(3, value)
        return this
    }

    override fun value5(value: String?): ReceivingTransactionsRecord {
        set(4, value)
        return this
    }

    override fun value6(value: String?): ReceivingTransactionsRecord {
        set(5, value)
        return this
    }

    override fun value7(value: BigDecimal?): ReceivingTransactionsRecord {
        set(6, value)
        return this
    }

    override fun value8(value: Int?): ReceivingTransactionsRecord {
        set(7, value)
        return this
    }

    override fun value9(value: OffsetDateTime?): ReceivingTransactionsRecord {
        set(8, value)
        return this
    }

    override fun value10(value: String?): ReceivingTransactionsRecord {
        set(9, value)
        return this
    }

    override fun value11(value: OffsetDateTime?): ReceivingTransactionsRecord {
        set(10, value)
        return this
    }

    override fun value12(value: String?): ReceivingTransactionsRecord {
        set(11, value)
        return this
    }

    override fun value13(value: Boolean?): ReceivingTransactionsRecord {
        set(12, value)
        return this
    }

    override fun values(value1: String?, value2: String?, value3: String?, value4: String?, value5: String?, value6: String?, value7: BigDecimal?, value8: Int?, value9: OffsetDateTime?, value10: String?, value11: OffsetDateTime?, value12: String?, value13: Boolean?): ReceivingTransactionsRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        this.value11(value11)
        this.value12(value12)
        this.value13(value13)
        return this
    }

    /**
     * Create a detached, initialised ReceivingTransactionsRecord
     */
    constructor(id: String? = null, sourceLocationCode: String? = null, destLocationCode: String? = null, sourcePackageCode: String? = null, destPackageCode: String? = null, poNumber: String? = null, qty: BigDecimal? = null, seqNo: Int? = null, createdDate: OffsetDateTime? = null, createdBy: String? = null, updatedDate: OffsetDateTime? = null, updatedBy: String? = null, isCanceled: Boolean? = null): this() {
        this.id = id
        this.sourceLocationCode = sourceLocationCode
        this.destLocationCode = destLocationCode
        this.sourcePackageCode = sourcePackageCode
        this.destPackageCode = destPackageCode
        this.poNumber = poNumber
        this.qty = qty
        this.seqNo = seqNo
        this.createdDate = createdDate
        this.createdBy = createdBy
        this.updatedDate = updatedDate
        this.updatedBy = updatedBy
        this.isCanceled = isCanceled
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised ReceivingTransactionsRecord
     */
    constructor(value: com.kcvn.spm.model.tables.pojos.ReceivingTransactions?): this() {
        if (value != null) {
            this.id = value.id
            this.sourceLocationCode = value.sourceLocationCode
            this.destLocationCode = value.destLocationCode
            this.sourcePackageCode = value.sourcePackageCode
            this.destPackageCode = value.destPackageCode
            this.poNumber = value.poNumber
            this.qty = value.qty
            this.seqNo = value.seqNo
            this.createdDate = value.createdDate
            this.createdBy = value.createdBy
            this.updatedDate = value.updatedDate
            this.updatedBy = value.updatedBy
            this.isCanceled = value.isCanceled
            resetChangedOnNotNull()
        }
    }
}
