/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables.records


import com.kcvn.spm.model.tables.StockTaking

import java.math.BigDecimal
import java.time.OffsetDateTime

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record11
import org.jooq.Row11
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class StockTakingRecord() : UpdatableRecordImpl<StockTakingRecord>(StockTaking.STOCK_TAKING), Record11<String?, Int?, Int?, String?, String?, BigDecimal?, BigDecimal?, OffsetDateTime?, String?, OffsetDateTime?, String?> {

    open var id: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var yearNumber: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var monthNumber: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    open var locationCode: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var poNumber: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var amoebaQty: BigDecimal?
        set(value): Unit = set(5, value)
        get(): BigDecimal? = get(5) as BigDecimal?

    open var actualQty: BigDecimal?
        set(value): Unit = set(6, value)
        get(): BigDecimal? = get(6) as BigDecimal?

    open var createdDate: OffsetDateTime?
        set(value): Unit = set(7, value)
        get(): OffsetDateTime? = get(7) as OffsetDateTime?

    open var createdBy: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    open var updatedDate: OffsetDateTime?
        set(value): Unit = set(9, value)
        get(): OffsetDateTime? = get(9) as OffsetDateTime?

    open var updatedBy: String?
        set(value): Unit = set(10, value)
        get(): String? = get(10) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row11<String?, Int?, Int?, String?, String?, BigDecimal?, BigDecimal?, OffsetDateTime?, String?, OffsetDateTime?, String?> = super.fieldsRow() as Row11<String?, Int?, Int?, String?, String?, BigDecimal?, BigDecimal?, OffsetDateTime?, String?, OffsetDateTime?, String?>
    override fun valuesRow(): Row11<String?, Int?, Int?, String?, String?, BigDecimal?, BigDecimal?, OffsetDateTime?, String?, OffsetDateTime?, String?> = super.valuesRow() as Row11<String?, Int?, Int?, String?, String?, BigDecimal?, BigDecimal?, OffsetDateTime?, String?, OffsetDateTime?, String?>
    override fun field1(): Field<String?> = StockTaking.STOCK_TAKING.ID
    override fun field2(): Field<Int?> = StockTaking.STOCK_TAKING.YEAR_NUMBER
    override fun field3(): Field<Int?> = StockTaking.STOCK_TAKING.MONTH_NUMBER
    override fun field4(): Field<String?> = StockTaking.STOCK_TAKING.LOCATION_CODE
    override fun field5(): Field<String?> = StockTaking.STOCK_TAKING.PO_NUMBER
    override fun field6(): Field<BigDecimal?> = StockTaking.STOCK_TAKING.AMOEBA_QTY
    override fun field7(): Field<BigDecimal?> = StockTaking.STOCK_TAKING.ACTUAL_QTY
    override fun field8(): Field<OffsetDateTime?> = StockTaking.STOCK_TAKING.CREATED_DATE
    override fun field9(): Field<String?> = StockTaking.STOCK_TAKING.CREATED_BY
    override fun field10(): Field<OffsetDateTime?> = StockTaking.STOCK_TAKING.UPDATED_DATE
    override fun field11(): Field<String?> = StockTaking.STOCK_TAKING.UPDATED_BY
    override fun component1(): String? = id
    override fun component2(): Int? = yearNumber
    override fun component3(): Int? = monthNumber
    override fun component4(): String? = locationCode
    override fun component5(): String? = poNumber
    override fun component6(): BigDecimal? = amoebaQty
    override fun component7(): BigDecimal? = actualQty
    override fun component8(): OffsetDateTime? = createdDate
    override fun component9(): String? = createdBy
    override fun component10(): OffsetDateTime? = updatedDate
    override fun component11(): String? = updatedBy
    override fun value1(): String? = id
    override fun value2(): Int? = yearNumber
    override fun value3(): Int? = monthNumber
    override fun value4(): String? = locationCode
    override fun value5(): String? = poNumber
    override fun value6(): BigDecimal? = amoebaQty
    override fun value7(): BigDecimal? = actualQty
    override fun value8(): OffsetDateTime? = createdDate
    override fun value9(): String? = createdBy
    override fun value10(): OffsetDateTime? = updatedDate
    override fun value11(): String? = updatedBy

    override fun value1(value: String?): StockTakingRecord {
        set(0, value)
        return this
    }

    override fun value2(value: Int?): StockTakingRecord {
        set(1, value)
        return this
    }

    override fun value3(value: Int?): StockTakingRecord {
        set(2, value)
        return this
    }

    override fun value4(value: String?): StockTakingRecord {
        set(3, value)
        return this
    }

    override fun value5(value: String?): StockTakingRecord {
        set(4, value)
        return this
    }

    override fun value6(value: BigDecimal?): StockTakingRecord {
        set(5, value)
        return this
    }

    override fun value7(value: BigDecimal?): StockTakingRecord {
        set(6, value)
        return this
    }

    override fun value8(value: OffsetDateTime?): StockTakingRecord {
        set(7, value)
        return this
    }

    override fun value9(value: String?): StockTakingRecord {
        set(8, value)
        return this
    }

    override fun value10(value: OffsetDateTime?): StockTakingRecord {
        set(9, value)
        return this
    }

    override fun value11(value: String?): StockTakingRecord {
        set(10, value)
        return this
    }

    override fun values(value1: String?, value2: Int?, value3: Int?, value4: String?, value5: String?, value6: BigDecimal?, value7: BigDecimal?, value8: OffsetDateTime?, value9: String?, value10: OffsetDateTime?, value11: String?): StockTakingRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        this.value11(value11)
        return this
    }

    /**
     * Create a detached, initialised StockTakingRecord
     */
    constructor(id: String? = null, yearNumber: Int? = null, monthNumber: Int? = null, locationCode: String? = null, poNumber: String? = null, amoebaQty: BigDecimal? = null, actualQty: BigDecimal? = null, createdDate: OffsetDateTime? = null, createdBy: String? = null, updatedDate: OffsetDateTime? = null, updatedBy: String? = null): this() {
        this.id = id
        this.yearNumber = yearNumber
        this.monthNumber = monthNumber
        this.locationCode = locationCode
        this.poNumber = poNumber
        this.amoebaQty = amoebaQty
        this.actualQty = actualQty
        this.createdDate = createdDate
        this.createdBy = createdBy
        this.updatedDate = updatedDate
        this.updatedBy = updatedBy
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised StockTakingRecord
     */
    constructor(value: com.kcvn.spm.model.tables.pojos.StockTaking?): this() {
        if (value != null) {
            this.id = value.id
            this.yearNumber = value.yearNumber
            this.monthNumber = value.monthNumber
            this.locationCode = value.locationCode
            this.poNumber = value.poNumber
            this.amoebaQty = value.amoebaQty
            this.actualQty = value.actualQty
            this.createdDate = value.createdDate
            this.createdBy = value.createdBy
            this.updatedDate = value.updatedDate
            this.updatedBy = value.updatedBy
            resetChangedOnNotNull()
        }
    }
}
