/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables.records


import com.kcvn.spm.model.tables.StockTakingStatus

import java.time.OffsetDateTime

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record8
import org.jooq.Row8
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class StockTakingStatusRecord() : UpdatableRecordImpl<StockTakingStatusRecord>(StockTakingStatus.STOCK_TAKING_STATUS), Record8<String?, Int?, Int?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?> {

    open var id: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var yearNumber: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var monthNumber: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    open var status: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var createdDate: OffsetDateTime?
        set(value): Unit = set(4, value)
        get(): OffsetDateTime? = get(4) as OffsetDateTime?

    open var createdBy: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var updatedDate: OffsetDateTime?
        set(value): Unit = set(6, value)
        get(): OffsetDateTime? = get(6) as OffsetDateTime?

    open var updatedBy: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row8<String?, Int?, Int?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?> = super.fieldsRow() as Row8<String?, Int?, Int?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?>
    override fun valuesRow(): Row8<String?, Int?, Int?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?> = super.valuesRow() as Row8<String?, Int?, Int?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?>
    override fun field1(): Field<String?> = StockTakingStatus.STOCK_TAKING_STATUS.ID
    override fun field2(): Field<Int?> = StockTakingStatus.STOCK_TAKING_STATUS.YEAR_NUMBER
    override fun field3(): Field<Int?> = StockTakingStatus.STOCK_TAKING_STATUS.MONTH_NUMBER
    override fun field4(): Field<String?> = StockTakingStatus.STOCK_TAKING_STATUS.STATUS
    override fun field5(): Field<OffsetDateTime?> = StockTakingStatus.STOCK_TAKING_STATUS.CREATED_DATE
    override fun field6(): Field<String?> = StockTakingStatus.STOCK_TAKING_STATUS.CREATED_BY
    override fun field7(): Field<OffsetDateTime?> = StockTakingStatus.STOCK_TAKING_STATUS.UPDATED_DATE
    override fun field8(): Field<String?> = StockTakingStatus.STOCK_TAKING_STATUS.UPDATED_BY
    override fun component1(): String? = id
    override fun component2(): Int? = yearNumber
    override fun component3(): Int? = monthNumber
    override fun component4(): String? = status
    override fun component5(): OffsetDateTime? = createdDate
    override fun component6(): String? = createdBy
    override fun component7(): OffsetDateTime? = updatedDate
    override fun component8(): String? = updatedBy
    override fun value1(): String? = id
    override fun value2(): Int? = yearNumber
    override fun value3(): Int? = monthNumber
    override fun value4(): String? = status
    override fun value5(): OffsetDateTime? = createdDate
    override fun value6(): String? = createdBy
    override fun value7(): OffsetDateTime? = updatedDate
    override fun value8(): String? = updatedBy

    override fun value1(value: String?): StockTakingStatusRecord {
        set(0, value)
        return this
    }

    override fun value2(value: Int?): StockTakingStatusRecord {
        set(1, value)
        return this
    }

    override fun value3(value: Int?): StockTakingStatusRecord {
        set(2, value)
        return this
    }

    override fun value4(value: String?): StockTakingStatusRecord {
        set(3, value)
        return this
    }

    override fun value5(value: OffsetDateTime?): StockTakingStatusRecord {
        set(4, value)
        return this
    }

    override fun value6(value: String?): StockTakingStatusRecord {
        set(5, value)
        return this
    }

    override fun value7(value: OffsetDateTime?): StockTakingStatusRecord {
        set(6, value)
        return this
    }

    override fun value8(value: String?): StockTakingStatusRecord {
        set(7, value)
        return this
    }

    override fun values(value1: String?, value2: Int?, value3: Int?, value4: String?, value5: OffsetDateTime?, value6: String?, value7: OffsetDateTime?, value8: String?): StockTakingStatusRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        return this
    }

    /**
     * Create a detached, initialised StockTakingStatusRecord
     */
    constructor(id: String? = null, yearNumber: Int? = null, monthNumber: Int? = null, status: String? = null, createdDate: OffsetDateTime? = null, createdBy: String? = null, updatedDate: OffsetDateTime? = null, updatedBy: String? = null): this() {
        this.id = id
        this.yearNumber = yearNumber
        this.monthNumber = monthNumber
        this.status = status
        this.createdDate = createdDate
        this.createdBy = createdBy
        this.updatedDate = updatedDate
        this.updatedBy = updatedBy
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised StockTakingStatusRecord
     */
    constructor(value: com.kcvn.spm.model.tables.pojos.StockTakingStatus?): this() {
        if (value != null) {
            this.id = value.id
            this.yearNumber = value.yearNumber
            this.monthNumber = value.monthNumber
            this.status = value.status
            this.createdDate = value.createdDate
            this.createdBy = value.createdBy
            this.updatedDate = value.updatedDate
            this.updatedBy = value.updatedBy
            resetChangedOnNotNull()
        }
    }
}
