/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables.records


import com.kcvn.spm.model.tables.SystemLock

import java.time.OffsetDateTime

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record8
import org.jooq.Row8
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SystemLockRecord() : UpdatableRecordImpl<SystemLockRecord>(SystemLock.SYSTEM_LOCK), Record8<String?, String?, Boolean?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?> {

    open var id: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var type: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsLock")
    open var isLock: Boolean?
        set(value): Unit = set(2, value)
        get(): Boolean? = get(2) as Boolean?

    open var createdDate: OffsetDateTime?
        set(value): Unit = set(3, value)
        get(): OffsetDateTime? = get(3) as OffsetDateTime?

    open var createdBy: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var updatedDate: OffsetDateTime?
        set(value): Unit = set(5, value)
        get(): OffsetDateTime? = get(5) as OffsetDateTime?

    open var updatedBy: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsDeleted")
    open var isDeleted: Boolean?
        set(value): Unit = set(7, value)
        get(): Boolean? = get(7) as Boolean?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row8<String?, String?, Boolean?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?> = super.fieldsRow() as Row8<String?, String?, Boolean?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?>
    override fun valuesRow(): Row8<String?, String?, Boolean?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?> = super.valuesRow() as Row8<String?, String?, Boolean?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?>
    override fun field1(): Field<String?> = SystemLock.SYSTEM_LOCK.ID
    override fun field2(): Field<String?> = SystemLock.SYSTEM_LOCK.TYPE
    override fun field3(): Field<Boolean?> = SystemLock.SYSTEM_LOCK.IS_LOCK
    override fun field4(): Field<OffsetDateTime?> = SystemLock.SYSTEM_LOCK.CREATED_DATE
    override fun field5(): Field<String?> = SystemLock.SYSTEM_LOCK.CREATED_BY
    override fun field6(): Field<OffsetDateTime?> = SystemLock.SYSTEM_LOCK.UPDATED_DATE
    override fun field7(): Field<String?> = SystemLock.SYSTEM_LOCK.UPDATED_BY
    override fun field8(): Field<Boolean?> = SystemLock.SYSTEM_LOCK.IS_DELETED
    override fun component1(): String? = id
    override fun component2(): String? = type
    override fun component3(): Boolean? = isLock
    override fun component4(): OffsetDateTime? = createdDate
    override fun component5(): String? = createdBy
    override fun component6(): OffsetDateTime? = updatedDate
    override fun component7(): String? = updatedBy
    override fun component8(): Boolean? = isDeleted
    override fun value1(): String? = id
    override fun value2(): String? = type
    override fun value3(): Boolean? = isLock
    override fun value4(): OffsetDateTime? = createdDate
    override fun value5(): String? = createdBy
    override fun value6(): OffsetDateTime? = updatedDate
    override fun value7(): String? = updatedBy
    override fun value8(): Boolean? = isDeleted

    override fun value1(value: String?): SystemLockRecord {
        set(0, value)
        return this
    }

    override fun value2(value: String?): SystemLockRecord {
        set(1, value)
        return this
    }

    override fun value3(value: Boolean?): SystemLockRecord {
        set(2, value)
        return this
    }

    override fun value4(value: OffsetDateTime?): SystemLockRecord {
        set(3, value)
        return this
    }

    override fun value5(value: String?): SystemLockRecord {
        set(4, value)
        return this
    }

    override fun value6(value: OffsetDateTime?): SystemLockRecord {
        set(5, value)
        return this
    }

    override fun value7(value: String?): SystemLockRecord {
        set(6, value)
        return this
    }

    override fun value8(value: Boolean?): SystemLockRecord {
        set(7, value)
        return this
    }

    override fun values(value1: String?, value2: String?, value3: Boolean?, value4: OffsetDateTime?, value5: String?, value6: OffsetDateTime?, value7: String?, value8: Boolean?): SystemLockRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        return this
    }

    /**
     * Create a detached, initialised SystemLockRecord
     */
    constructor(id: String? = null, type: String? = null, isLock: Boolean? = null, createdDate: OffsetDateTime? = null, createdBy: String? = null, updatedDate: OffsetDateTime? = null, updatedBy: String? = null, isDeleted: Boolean? = null): this() {
        this.id = id
        this.type = type
        this.isLock = isLock
        this.createdDate = createdDate
        this.createdBy = createdBy
        this.updatedDate = updatedDate
        this.updatedBy = updatedBy
        this.isDeleted = isDeleted
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised SystemLockRecord
     */
    constructor(value: com.kcvn.spm.model.tables.pojos.SystemLock?): this() {
        if (value != null) {
            this.id = value.id
            this.type = value.type
            this.isLock = value.isLock
            this.createdDate = value.createdDate
            this.createdBy = value.createdBy
            this.updatedDate = value.updatedDate
            this.updatedBy = value.updatedBy
            this.isDeleted = value.isDeleted
            resetChangedOnNotNull()
        }
    }
}
