/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables.records


import com.kcvn.spm.model.tables.TapeInventory

import java.time.OffsetDateTime

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record13
import org.jooq.Row13
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class TapeInventoryRecord() : UpdatableRecordImpl<TapeInventoryRecord>(TapeInventory.TAPE_INVENTORY), Record13<String?, String?, String?, String?, Int?, Int?, Int?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?, OffsetDateTime?> {

    open var id: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var exportType: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var productName: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var productNameShortCut: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var tapeInWarehouse: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var tapeInDepartment: Int?
        set(value): Unit = set(5, value)
        get(): Int? = get(5) as Int?

    open var tapeNg: Int?
        set(value): Unit = set(6, value)
        get(): Int? = get(6) as Int?

    open var createdDate: OffsetDateTime?
        set(value): Unit = set(7, value)
        get(): OffsetDateTime? = get(7) as OffsetDateTime?

    open var createdBy: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    open var updatedDate: OffsetDateTime?
        set(value): Unit = set(9, value)
        get(): OffsetDateTime? = get(9) as OffsetDateTime?

    open var updatedBy: String?
        set(value): Unit = set(10, value)
        get(): String? = get(10) as String?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsDeleted")
    open var isDeleted: Boolean?
        set(value): Unit = set(11, value)
        get(): Boolean? = get(11) as Boolean?

    open var stocktakingDay: OffsetDateTime?
        set(value): Unit = set(12, value)
        get(): OffsetDateTime? = get(12) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row13<String?, String?, String?, String?, Int?, Int?, Int?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?, OffsetDateTime?> = super.fieldsRow() as Row13<String?, String?, String?, String?, Int?, Int?, Int?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?, OffsetDateTime?>
    override fun valuesRow(): Row13<String?, String?, String?, String?, Int?, Int?, Int?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?, OffsetDateTime?> = super.valuesRow() as Row13<String?, String?, String?, String?, Int?, Int?, Int?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?, OffsetDateTime?>
    override fun field1(): Field<String?> = TapeInventory.TAPE_INVENTORY.ID
    override fun field2(): Field<String?> = TapeInventory.TAPE_INVENTORY.EXPORT_TYPE
    override fun field3(): Field<String?> = TapeInventory.TAPE_INVENTORY.PRODUCT_NAME
    override fun field4(): Field<String?> = TapeInventory.TAPE_INVENTORY.PRODUCT_NAME_SHORT_CUT
    override fun field5(): Field<Int?> = TapeInventory.TAPE_INVENTORY.TAPE_IN_WAREHOUSE
    override fun field6(): Field<Int?> = TapeInventory.TAPE_INVENTORY.TAPE_IN_DEPARTMENT
    override fun field7(): Field<Int?> = TapeInventory.TAPE_INVENTORY.TAPE_NG
    override fun field8(): Field<OffsetDateTime?> = TapeInventory.TAPE_INVENTORY.CREATED_DATE
    override fun field9(): Field<String?> = TapeInventory.TAPE_INVENTORY.CREATED_BY
    override fun field10(): Field<OffsetDateTime?> = TapeInventory.TAPE_INVENTORY.UPDATED_DATE
    override fun field11(): Field<String?> = TapeInventory.TAPE_INVENTORY.UPDATED_BY
    override fun field12(): Field<Boolean?> = TapeInventory.TAPE_INVENTORY.IS_DELETED
    override fun field13(): Field<OffsetDateTime?> = TapeInventory.TAPE_INVENTORY.STOCKTAKING_DAY
    override fun component1(): String? = id
    override fun component2(): String? = exportType
    override fun component3(): String? = productName
    override fun component4(): String? = productNameShortCut
    override fun component5(): Int? = tapeInWarehouse
    override fun component6(): Int? = tapeInDepartment
    override fun component7(): Int? = tapeNg
    override fun component8(): OffsetDateTime? = createdDate
    override fun component9(): String? = createdBy
    override fun component10(): OffsetDateTime? = updatedDate
    override fun component11(): String? = updatedBy
    override fun component12(): Boolean? = isDeleted
    override fun component13(): OffsetDateTime? = stocktakingDay
    override fun value1(): String? = id
    override fun value2(): String? = exportType
    override fun value3(): String? = productName
    override fun value4(): String? = productNameShortCut
    override fun value5(): Int? = tapeInWarehouse
    override fun value6(): Int? = tapeInDepartment
    override fun value7(): Int? = tapeNg
    override fun value8(): OffsetDateTime? = createdDate
    override fun value9(): String? = createdBy
    override fun value10(): OffsetDateTime? = updatedDate
    override fun value11(): String? = updatedBy
    override fun value12(): Boolean? = isDeleted
    override fun value13(): OffsetDateTime? = stocktakingDay

    override fun value1(value: String?): TapeInventoryRecord {
        set(0, value)
        return this
    }

    override fun value2(value: String?): TapeInventoryRecord {
        set(1, value)
        return this
    }

    override fun value3(value: String?): TapeInventoryRecord {
        set(2, value)
        return this
    }

    override fun value4(value: String?): TapeInventoryRecord {
        set(3, value)
        return this
    }

    override fun value5(value: Int?): TapeInventoryRecord {
        set(4, value)
        return this
    }

    override fun value6(value: Int?): TapeInventoryRecord {
        set(5, value)
        return this
    }

    override fun value7(value: Int?): TapeInventoryRecord {
        set(6, value)
        return this
    }

    override fun value8(value: OffsetDateTime?): TapeInventoryRecord {
        set(7, value)
        return this
    }

    override fun value9(value: String?): TapeInventoryRecord {
        set(8, value)
        return this
    }

    override fun value10(value: OffsetDateTime?): TapeInventoryRecord {
        set(9, value)
        return this
    }

    override fun value11(value: String?): TapeInventoryRecord {
        set(10, value)
        return this
    }

    override fun value12(value: Boolean?): TapeInventoryRecord {
        set(11, value)
        return this
    }

    override fun value13(value: OffsetDateTime?): TapeInventoryRecord {
        set(12, value)
        return this
    }

    override fun values(value1: String?, value2: String?, value3: String?, value4: String?, value5: Int?, value6: Int?, value7: Int?, value8: OffsetDateTime?, value9: String?, value10: OffsetDateTime?, value11: String?, value12: Boolean?, value13: OffsetDateTime?): TapeInventoryRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        this.value11(value11)
        this.value12(value12)
        this.value13(value13)
        return this
    }

    /**
     * Create a detached, initialised TapeInventoryRecord
     */
    constructor(id: String? = null, exportType: String? = null, productName: String? = null, productNameShortCut: String? = null, tapeInWarehouse: Int? = null, tapeInDepartment: Int? = null, tapeNg: Int? = null, createdDate: OffsetDateTime? = null, createdBy: String? = null, updatedDate: OffsetDateTime? = null, updatedBy: String? = null, isDeleted: Boolean? = null, stocktakingDay: OffsetDateTime? = null): this() {
        this.id = id
        this.exportType = exportType
        this.productName = productName
        this.productNameShortCut = productNameShortCut
        this.tapeInWarehouse = tapeInWarehouse
        this.tapeInDepartment = tapeInDepartment
        this.tapeNg = tapeNg
        this.createdDate = createdDate
        this.createdBy = createdBy
        this.updatedDate = updatedDate
        this.updatedBy = updatedBy
        this.isDeleted = isDeleted
        this.stocktakingDay = stocktakingDay
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised TapeInventoryRecord
     */
    constructor(value: com.kcvn.spm.model.tables.pojos.TapeInventory?): this() {
        if (value != null) {
            this.id = value.id
            this.exportType = value.exportType
            this.productName = value.productName
            this.productNameShortCut = value.productNameShortCut
            this.tapeInWarehouse = value.tapeInWarehouse
            this.tapeInDepartment = value.tapeInDepartment
            this.tapeNg = value.tapeNg
            this.createdDate = value.createdDate
            this.createdBy = value.createdBy
            this.updatedDate = value.updatedDate
            this.updatedBy = value.updatedBy
            this.isDeleted = value.isDeleted
            this.stocktakingDay = value.stocktakingDay
            resetChangedOnNotNull()
        }
    }
}
