/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables.records


import com.kcvn.spm.model.tables.TempSendingTransactions

import java.math.BigDecimal
import java.time.LocalDate
import java.time.OffsetDateTime

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record19
import org.jooq.Row19
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class TempSendingTransactionsRecord() : UpdatableRecordImpl<TempSendingTransactionsRecord>(TempSendingTransactions.TEMP_SENDING_TRANSACTIONS), Record19<String?, String?, String?, String?, String?, String?, String?, BigDecimal?, Int?, String?, LocalDate?, LocalDate?, Boolean?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?, Boolean?> {

    open var id: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var formCode: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var sourceLocationCode: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var destLocationCode: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var sourcePackageCode: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var destPackageCode: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var poNumber: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var qty: BigDecimal?
        set(value): Unit = set(7, value)
        get(): BigDecimal? = get(7) as BigDecimal?

    open var seqNo: Int?
        set(value): Unit = set(8, value)
        get(): Int? = get(8) as Int?

    open var transactionType: String?
        set(value): Unit = set(9, value)
        get(): String? = get(9) as String?

    open var receivingDate: LocalDate?
        set(value): Unit = set(10, value)
        get(): LocalDate? = get(10) as LocalDate?

    open var inspectionDate: LocalDate?
        set(value): Unit = set(11, value)
        get(): LocalDate? = get(11) as LocalDate?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsUpdatedAmoeba")
    open var isUpdatedAmoeba: Boolean?
        set(value): Unit = set(12, value)
        get(): Boolean? = get(12) as Boolean?

    open var createdDate: OffsetDateTime?
        set(value): Unit = set(13, value)
        get(): OffsetDateTime? = get(13) as OffsetDateTime?

    open var createdBy: String?
        set(value): Unit = set(14, value)
        get(): String? = get(14) as String?

    open var updatedDate: OffsetDateTime?
        set(value): Unit = set(15, value)
        get(): OffsetDateTime? = get(15) as OffsetDateTime?

    open var updatedBy: String?
        set(value): Unit = set(16, value)
        get(): String? = get(16) as String?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsCanceled")
    open var isCanceled: Boolean?
        set(value): Unit = set(17, value)
        get(): Boolean? = get(17) as Boolean?

    open var notMinusBoxQty: Boolean?
        set(value): Unit = set(18, value)
        get(): Boolean? = get(18) as Boolean?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    // -------------------------------------------------------------------------
    // Record19 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row19<String?, String?, String?, String?, String?, String?, String?, BigDecimal?, Int?, String?, LocalDate?, LocalDate?, Boolean?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?, Boolean?> = super.fieldsRow() as Row19<String?, String?, String?, String?, String?, String?, String?, BigDecimal?, Int?, String?, LocalDate?, LocalDate?, Boolean?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?, Boolean?>
    override fun valuesRow(): Row19<String?, String?, String?, String?, String?, String?, String?, BigDecimal?, Int?, String?, LocalDate?, LocalDate?, Boolean?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?, Boolean?> = super.valuesRow() as Row19<String?, String?, String?, String?, String?, String?, String?, BigDecimal?, Int?, String?, LocalDate?, LocalDate?, Boolean?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?, Boolean?>
    override fun field1(): Field<String?> = TempSendingTransactions.TEMP_SENDING_TRANSACTIONS.ID
    override fun field2(): Field<String?> = TempSendingTransactions.TEMP_SENDING_TRANSACTIONS.FORM_CODE
    override fun field3(): Field<String?> = TempSendingTransactions.TEMP_SENDING_TRANSACTIONS.SOURCE_LOCATION_CODE
    override fun field4(): Field<String?> = TempSendingTransactions.TEMP_SENDING_TRANSACTIONS.DEST_LOCATION_CODE
    override fun field5(): Field<String?> = TempSendingTransactions.TEMP_SENDING_TRANSACTIONS.SOURCE_PACKAGE_CODE
    override fun field6(): Field<String?> = TempSendingTransactions.TEMP_SENDING_TRANSACTIONS.DEST_PACKAGE_CODE
    override fun field7(): Field<String?> = TempSendingTransactions.TEMP_SENDING_TRANSACTIONS.PO_NUMBER
    override fun field8(): Field<BigDecimal?> = TempSendingTransactions.TEMP_SENDING_TRANSACTIONS.QTY
    override fun field9(): Field<Int?> = TempSendingTransactions.TEMP_SENDING_TRANSACTIONS.SEQ_NO
    override fun field10(): Field<String?> = TempSendingTransactions.TEMP_SENDING_TRANSACTIONS.TRANSACTION_TYPE
    override fun field11(): Field<LocalDate?> = TempSendingTransactions.TEMP_SENDING_TRANSACTIONS.RECEIVING_DATE
    override fun field12(): Field<LocalDate?> = TempSendingTransactions.TEMP_SENDING_TRANSACTIONS.INSPECTION_DATE
    override fun field13(): Field<Boolean?> = TempSendingTransactions.TEMP_SENDING_TRANSACTIONS.IS_UPDATED_AMOEBA
    override fun field14(): Field<OffsetDateTime?> = TempSendingTransactions.TEMP_SENDING_TRANSACTIONS.CREATED_DATE
    override fun field15(): Field<String?> = TempSendingTransactions.TEMP_SENDING_TRANSACTIONS.CREATED_BY
    override fun field16(): Field<OffsetDateTime?> = TempSendingTransactions.TEMP_SENDING_TRANSACTIONS.UPDATED_DATE
    override fun field17(): Field<String?> = TempSendingTransactions.TEMP_SENDING_TRANSACTIONS.UPDATED_BY
    override fun field18(): Field<Boolean?> = TempSendingTransactions.TEMP_SENDING_TRANSACTIONS.IS_CANCELED
    override fun field19(): Field<Boolean?> = TempSendingTransactions.TEMP_SENDING_TRANSACTIONS.NOT_MINUS_BOX_QTY
    override fun component1(): String? = id
    override fun component2(): String? = formCode
    override fun component3(): String? = sourceLocationCode
    override fun component4(): String? = destLocationCode
    override fun component5(): String? = sourcePackageCode
    override fun component6(): String? = destPackageCode
    override fun component7(): String? = poNumber
    override fun component8(): BigDecimal? = qty
    override fun component9(): Int? = seqNo
    override fun component10(): String? = transactionType
    override fun component11(): LocalDate? = receivingDate
    override fun component12(): LocalDate? = inspectionDate
    override fun component13(): Boolean? = isUpdatedAmoeba
    override fun component14(): OffsetDateTime? = createdDate
    override fun component15(): String? = createdBy
    override fun component16(): OffsetDateTime? = updatedDate
    override fun component17(): String? = updatedBy
    override fun component18(): Boolean? = isCanceled
    override fun component19(): Boolean? = notMinusBoxQty
    override fun value1(): String? = id
    override fun value2(): String? = formCode
    override fun value3(): String? = sourceLocationCode
    override fun value4(): String? = destLocationCode
    override fun value5(): String? = sourcePackageCode
    override fun value6(): String? = destPackageCode
    override fun value7(): String? = poNumber
    override fun value8(): BigDecimal? = qty
    override fun value9(): Int? = seqNo
    override fun value10(): String? = transactionType
    override fun value11(): LocalDate? = receivingDate
    override fun value12(): LocalDate? = inspectionDate
    override fun value13(): Boolean? = isUpdatedAmoeba
    override fun value14(): OffsetDateTime? = createdDate
    override fun value15(): String? = createdBy
    override fun value16(): OffsetDateTime? = updatedDate
    override fun value17(): String? = updatedBy
    override fun value18(): Boolean? = isCanceled
    override fun value19(): Boolean? = notMinusBoxQty

    override fun value1(value: String?): TempSendingTransactionsRecord {
        set(0, value)
        return this
    }

    override fun value2(value: String?): TempSendingTransactionsRecord {
        set(1, value)
        return this
    }

    override fun value3(value: String?): TempSendingTransactionsRecord {
        set(2, value)
        return this
    }

    override fun value4(value: String?): TempSendingTransactionsRecord {
        set(3, value)
        return this
    }

    override fun value5(value: String?): TempSendingTransactionsRecord {
        set(4, value)
        return this
    }

    override fun value6(value: String?): TempSendingTransactionsRecord {
        set(5, value)
        return this
    }

    override fun value7(value: String?): TempSendingTransactionsRecord {
        set(6, value)
        return this
    }

    override fun value8(value: BigDecimal?): TempSendingTransactionsRecord {
        set(7, value)
        return this
    }

    override fun value9(value: Int?): TempSendingTransactionsRecord {
        set(8, value)
        return this
    }

    override fun value10(value: String?): TempSendingTransactionsRecord {
        set(9, value)
        return this
    }

    override fun value11(value: LocalDate?): TempSendingTransactionsRecord {
        set(10, value)
        return this
    }

    override fun value12(value: LocalDate?): TempSendingTransactionsRecord {
        set(11, value)
        return this
    }

    override fun value13(value: Boolean?): TempSendingTransactionsRecord {
        set(12, value)
        return this
    }

    override fun value14(value: OffsetDateTime?): TempSendingTransactionsRecord {
        set(13, value)
        return this
    }

    override fun value15(value: String?): TempSendingTransactionsRecord {
        set(14, value)
        return this
    }

    override fun value16(value: OffsetDateTime?): TempSendingTransactionsRecord {
        set(15, value)
        return this
    }

    override fun value17(value: String?): TempSendingTransactionsRecord {
        set(16, value)
        return this
    }

    override fun value18(value: Boolean?): TempSendingTransactionsRecord {
        set(17, value)
        return this
    }

    override fun value19(value: Boolean?): TempSendingTransactionsRecord {
        set(18, value)
        return this
    }

    override fun values(value1: String?, value2: String?, value3: String?, value4: String?, value5: String?, value6: String?, value7: String?, value8: BigDecimal?, value9: Int?, value10: String?, value11: LocalDate?, value12: LocalDate?, value13: Boolean?, value14: OffsetDateTime?, value15: String?, value16: OffsetDateTime?, value17: String?, value18: Boolean?, value19: Boolean?): TempSendingTransactionsRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        this.value11(value11)
        this.value12(value12)
        this.value13(value13)
        this.value14(value14)
        this.value15(value15)
        this.value16(value16)
        this.value17(value17)
        this.value18(value18)
        this.value19(value19)
        return this
    }

    /**
     * Create a detached, initialised TempSendingTransactionsRecord
     */
    constructor(id: String? = null, formCode: String? = null, sourceLocationCode: String? = null, destLocationCode: String? = null, sourcePackageCode: String? = null, destPackageCode: String? = null, poNumber: String? = null, qty: BigDecimal? = null, seqNo: Int? = null, transactionType: String? = null, receivingDate: LocalDate? = null, inspectionDate: LocalDate? = null, isUpdatedAmoeba: Boolean? = null, createdDate: OffsetDateTime? = null, createdBy: String? = null, updatedDate: OffsetDateTime? = null, updatedBy: String? = null, isCanceled: Boolean? = null, notMinusBoxQty: Boolean? = null): this() {
        this.id = id
        this.formCode = formCode
        this.sourceLocationCode = sourceLocationCode
        this.destLocationCode = destLocationCode
        this.sourcePackageCode = sourcePackageCode
        this.destPackageCode = destPackageCode
        this.poNumber = poNumber
        this.qty = qty
        this.seqNo = seqNo
        this.transactionType = transactionType
        this.receivingDate = receivingDate
        this.inspectionDate = inspectionDate
        this.isUpdatedAmoeba = isUpdatedAmoeba
        this.createdDate = createdDate
        this.createdBy = createdBy
        this.updatedDate = updatedDate
        this.updatedBy = updatedBy
        this.isCanceled = isCanceled
        this.notMinusBoxQty = notMinusBoxQty
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised TempSendingTransactionsRecord
     */
    constructor(value: com.kcvn.spm.model.tables.pojos.TempSendingTransactions?): this() {
        if (value != null) {
            this.id = value.id
            this.formCode = value.formCode
            this.sourceLocationCode = value.sourceLocationCode
            this.destLocationCode = value.destLocationCode
            this.sourcePackageCode = value.sourcePackageCode
            this.destPackageCode = value.destPackageCode
            this.poNumber = value.poNumber
            this.qty = value.qty
            this.seqNo = value.seqNo
            this.transactionType = value.transactionType
            this.receivingDate = value.receivingDate
            this.inspectionDate = value.inspectionDate
            this.isUpdatedAmoeba = value.isUpdatedAmoeba
            this.createdDate = value.createdDate
            this.createdBy = value.createdBy
            this.updatedDate = value.updatedDate
            this.updatedBy = value.updatedBy
            this.isCanceled = value.isCanceled
            this.notMinusBoxQty = value.notMinusBoxQty
            resetChangedOnNotNull()
        }
    }
}
