flyway.url=jdbc:postgresql://localhost:5433/kcvn_spm
flyway.user=postgres
flyway.password=password

spring.datasource.url=${flyway.url}
spring.datasource.username=${flyway.user}
spring.datasource.password=${flyway.password}

spring.jooq.sql-dialect=Postgres
# Uncomment below line to show jooq query
#logging.level.org.jooq.tools.LoggerListener=DEBUG

spring.mvc.format.date=iso
spring.mvc.format.date-time=iso

# App Properties
kcvn.spm.jwtSecret=====================23=KCVN=SPM=BE=SECRET====================
kcvn.spm.jwtExpirationMs=86400000

# Skip Flyway migration when start application
spring.flyway.enabled=false

# change server port
#server.port=8081
