flyway.url=jdbc:postgresql://db:5432/postgres
flyway.user=pd1plansys
flyway.password=pd1plansys

spring.datasource.url=jdbc:postgresql://db:5432/postgres
spring.datasource.username=pd1plansys
spring.datasource.password=pd1plansys

#Sync db connection config
trans_am_db.url=jdbc:oracle:thin:@//10.79.48.15:1521/KVCSC001
trans_am_db.user=KVCREADONLY
trans_am_db.password=Kvcdb010
trans_am_db.schema=KVC
trans_am_db.hasSchema=Y
#


# Uncomment below line to show jooq query
#logging.level.org.jooq.tools.LoggerListener=DEBUG

spring.mvc.format.date=iso
spring.mvc.format.date-time=iso

# App Properties
kcvn.spm.jwtSecret=====================23=KCVN=SPM=BE=SECRET====================
kcvn.spm.jwtExpirationMs=86400000

# Skip Flyway migration when start application
spring.flyway.enabled=false

# change server port
#server.port=8081

################### JavaMail Configuration ##########################
support.email=canh.nd@3si.vn
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.protocol=smtps
spring.mail.username=canh.nd@3si.vn
spring.mail.password=canhnd@12345
spring.mail.properties.mail.transport.protocol=smtps
spring.mail.properties.mail.smtps.auth=true
spring.mail.properties.mail.smtps.starttls.enable=true
spring.mail.properties.mail.smtps.timeout=8000

spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB