flyway.url=jdbc:postgresql://localhost:5433/kcvn_spm
flyway.user=postgres
flyway.password=password

spring.datasource.url=${flyway.url}
spring.datasource.username=${flyway.user}
spring.datasource.password=${flyway.password}

spring.jooq.sql-dialect=Postgres
logging.level.org.jooq.tools.LoggerListener=DEBUG

# App Properties
kcvn.spm.jwtSecret=====================23=KCVN=SPM=BE=SECRET====================
kcvn.spm.jwtExpirationMs=86400000

# Skip Flyway migration when start application
spring.flyway.enabled=false
