/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables.pojos


import java.io.Serializable
import java.time.LocalDate
import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class AuthUser(
    var id: String? = null,
    var username: String? = null,
    var password: String? = null,
    var employeeCode: String? = null,
    var email: String? = null,
    var phoneNumber: String? = null,
    var fullName: String? = null,
    var fullNameUnsigned: String? = null,
    var dateOfBirth: LocalDate? = null,
    var avatar: String? = null,
    var status: Short? = null,
    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsSuperAdmin")
    var isSuperAdmin: Boolean? = null,
    var createdDate: OffsetDateTime? = null,
    var createdBy: String? = null,
    var updatedDate: OffsetDateTime? = null,
    var updatedBy: String? = null,
    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsDeleted")
    var isDeleted: Boolean? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: AuthUser = other as AuthUser
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.username == null) {
            if (o.username != null)
                return false
        }
        else if (this.username != o.username)
            return false
        if (this.password == null) {
            if (o.password != null)
                return false
        }
        else if (this.password != o.password)
            return false
        if (this.employeeCode == null) {
            if (o.employeeCode != null)
                return false
        }
        else if (this.employeeCode != o.employeeCode)
            return false
        if (this.email == null) {
            if (o.email != null)
                return false
        }
        else if (this.email != o.email)
            return false
        if (this.phoneNumber == null) {
            if (o.phoneNumber != null)
                return false
        }
        else if (this.phoneNumber != o.phoneNumber)
            return false
        if (this.fullName == null) {
            if (o.fullName != null)
                return false
        }
        else if (this.fullName != o.fullName)
            return false
        if (this.fullNameUnsigned == null) {
            if (o.fullNameUnsigned != null)
                return false
        }
        else if (this.fullNameUnsigned != o.fullNameUnsigned)
            return false
        if (this.dateOfBirth == null) {
            if (o.dateOfBirth != null)
                return false
        }
        else if (this.dateOfBirth != o.dateOfBirth)
            return false
        if (this.avatar == null) {
            if (o.avatar != null)
                return false
        }
        else if (this.avatar != o.avatar)
            return false
        if (this.status == null) {
            if (o.status != null)
                return false
        }
        else if (this.status != o.status)
            return false
        if (this.isSuperAdmin == null) {
            if (o.isSuperAdmin != null)
                return false
        }
        else if (this.isSuperAdmin != o.isSuperAdmin)
            return false
        if (this.createdDate == null) {
            if (o.createdDate != null)
                return false
        }
        else if (this.createdDate != o.createdDate)
            return false
        if (this.createdBy == null) {
            if (o.createdBy != null)
                return false
        }
        else if (this.createdBy != o.createdBy)
            return false
        if (this.updatedDate == null) {
            if (o.updatedDate != null)
                return false
        }
        else if (this.updatedDate != o.updatedDate)
            return false
        if (this.updatedBy == null) {
            if (o.updatedBy != null)
                return false
        }
        else if (this.updatedBy != o.updatedBy)
            return false
        if (this.isDeleted == null) {
            if (o.isDeleted != null)
                return false
        }
        else if (this.isDeleted != o.isDeleted)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + (if (this.username == null) 0 else this.username.hashCode())
        result = prime * result + (if (this.password == null) 0 else this.password.hashCode())
        result = prime * result + (if (this.employeeCode == null) 0 else this.employeeCode.hashCode())
        result = prime * result + (if (this.email == null) 0 else this.email.hashCode())
        result = prime * result + (if (this.phoneNumber == null) 0 else this.phoneNumber.hashCode())
        result = prime * result + (if (this.fullName == null) 0 else this.fullName.hashCode())
        result = prime * result + (if (this.fullNameUnsigned == null) 0 else this.fullNameUnsigned.hashCode())
        result = prime * result + (if (this.dateOfBirth == null) 0 else this.dateOfBirth.hashCode())
        result = prime * result + (if (this.avatar == null) 0 else this.avatar.hashCode())
        result = prime * result + (if (this.status == null) 0 else this.status.hashCode())
        result = prime * result + (if (this.isSuperAdmin == null) 0 else this.isSuperAdmin.hashCode())
        result = prime * result + (if (this.createdDate == null) 0 else this.createdDate.hashCode())
        result = prime * result + (if (this.createdBy == null) 0 else this.createdBy.hashCode())
        result = prime * result + (if (this.updatedDate == null) 0 else this.updatedDate.hashCode())
        result = prime * result + (if (this.updatedBy == null) 0 else this.updatedBy.hashCode())
        result = prime * result + (if (this.isDeleted == null) 0 else this.isDeleted.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("AuthUser (")

        sb.append(id)
        sb.append(", ").append(username)
        sb.append(", ").append(password)
        sb.append(", ").append(employeeCode)
        sb.append(", ").append(email)
        sb.append(", ").append(phoneNumber)
        sb.append(", ").append(fullName)
        sb.append(", ").append(fullNameUnsigned)
        sb.append(", ").append(dateOfBirth)
        sb.append(", ").append(avatar)
        sb.append(", ").append(status)
        sb.append(", ").append(isSuperAdmin)
        sb.append(", ").append(createdDate)
        sb.append(", ").append(createdBy)
        sb.append(", ").append(updatedDate)
        sb.append(", ").append(updatedBy)
        sb.append(", ").append(isDeleted)

        sb.append(")")
        return sb.toString()
    }
}
