/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables.pojos


import java.io.Serializable
import java.math.BigDecimal
import java.time.LocalDate
import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class BacklogWhHistory(
    var id: String? = null,
    var locationCode: String? = null,
    var poNumber: String? = null,
    var packageCode: String? = null,
    var backlogQty: BigDecimal? = null,
    var boxQty: Int? = null,
    var receivingDate: LocalDate? = null,
    var inspectionDate: LocalDate? = null,
    var transactionType: String? = null,
    var createdDate: OffsetDateTime? = null,
    var createdBy: String? = null,
    var updatedDate: OffsetDateTime? = null,
    var updatedBy: String? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: BacklogWhHistory = other as BacklogWhHistory
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.locationCode == null) {
            if (o.locationCode != null)
                return false
        }
        else if (this.locationCode != o.locationCode)
            return false
        if (this.poNumber == null) {
            if (o.poNumber != null)
                return false
        }
        else if (this.poNumber != o.poNumber)
            return false
        if (this.packageCode == null) {
            if (o.packageCode != null)
                return false
        }
        else if (this.packageCode != o.packageCode)
            return false
        if (this.backlogQty == null) {
            if (o.backlogQty != null)
                return false
        }
        else if (this.backlogQty != o.backlogQty)
            return false
        if (this.boxQty == null) {
            if (o.boxQty != null)
                return false
        }
        else if (this.boxQty != o.boxQty)
            return false
        if (this.receivingDate == null) {
            if (o.receivingDate != null)
                return false
        }
        else if (this.receivingDate != o.receivingDate)
            return false
        if (this.inspectionDate == null) {
            if (o.inspectionDate != null)
                return false
        }
        else if (this.inspectionDate != o.inspectionDate)
            return false
        if (this.transactionType == null) {
            if (o.transactionType != null)
                return false
        }
        else if (this.transactionType != o.transactionType)
            return false
        if (this.createdDate == null) {
            if (o.createdDate != null)
                return false
        }
        else if (this.createdDate != o.createdDate)
            return false
        if (this.createdBy == null) {
            if (o.createdBy != null)
                return false
        }
        else if (this.createdBy != o.createdBy)
            return false
        if (this.updatedDate == null) {
            if (o.updatedDate != null)
                return false
        }
        else if (this.updatedDate != o.updatedDate)
            return false
        if (this.updatedBy == null) {
            if (o.updatedBy != null)
                return false
        }
        else if (this.updatedBy != o.updatedBy)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + (if (this.locationCode == null) 0 else this.locationCode.hashCode())
        result = prime * result + (if (this.poNumber == null) 0 else this.poNumber.hashCode())
        result = prime * result + (if (this.packageCode == null) 0 else this.packageCode.hashCode())
        result = prime * result + (if (this.backlogQty == null) 0 else this.backlogQty.hashCode())
        result = prime * result + (if (this.boxQty == null) 0 else this.boxQty.hashCode())
        result = prime * result + (if (this.receivingDate == null) 0 else this.receivingDate.hashCode())
        result = prime * result + (if (this.inspectionDate == null) 0 else this.inspectionDate.hashCode())
        result = prime * result + (if (this.transactionType == null) 0 else this.transactionType.hashCode())
        result = prime * result + (if (this.createdDate == null) 0 else this.createdDate.hashCode())
        result = prime * result + (if (this.createdBy == null) 0 else this.createdBy.hashCode())
        result = prime * result + (if (this.updatedDate == null) 0 else this.updatedDate.hashCode())
        result = prime * result + (if (this.updatedBy == null) 0 else this.updatedBy.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("BacklogWhHistory (")

        sb.append(id)
        sb.append(", ").append(locationCode)
        sb.append(", ").append(poNumber)
        sb.append(", ").append(packageCode)
        sb.append(", ").append(backlogQty)
        sb.append(", ").append(boxQty)
        sb.append(", ").append(receivingDate)
        sb.append(", ").append(inspectionDate)
        sb.append(", ").append(transactionType)
        sb.append(", ").append(createdDate)
        sb.append(", ").append(createdBy)
        sb.append(", ").append(updatedDate)
        sb.append(", ").append(updatedBy)

        sb.append(")")
        return sb.toString()
    }
}
