/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables.pojos


import java.io.Serializable
import java.math.BigDecimal
import java.time.LocalDate
import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class CheckingHistory(
    var id: String? = null,
    var scanDate: LocalDate? = null,
    var poNumber: String? = null,
    var importQty: BigDecimal? = null,
    var scanQty: BigDecimal? = null,
    var seqNo: Int? = null,
    var createdDate: OffsetDateTime? = null,
    var createdBy: String? = null,
    var updatedDate: OffsetDateTime? = null,
    var updatedBy: String? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: CheckingHistory = other as CheckingHistory
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.scanDate == null) {
            if (o.scanDate != null)
                return false
        }
        else if (this.scanDate != o.scanDate)
            return false
        if (this.poNumber == null) {
            if (o.poNumber != null)
                return false
        }
        else if (this.poNumber != o.poNumber)
            return false
        if (this.importQty == null) {
            if (o.importQty != null)
                return false
        }
        else if (this.importQty != o.importQty)
            return false
        if (this.scanQty == null) {
            if (o.scanQty != null)
                return false
        }
        else if (this.scanQty != o.scanQty)
            return false
        if (this.seqNo == null) {
            if (o.seqNo != null)
                return false
        }
        else if (this.seqNo != o.seqNo)
            return false
        if (this.createdDate == null) {
            if (o.createdDate != null)
                return false
        }
        else if (this.createdDate != o.createdDate)
            return false
        if (this.createdBy == null) {
            if (o.createdBy != null)
                return false
        }
        else if (this.createdBy != o.createdBy)
            return false
        if (this.updatedDate == null) {
            if (o.updatedDate != null)
                return false
        }
        else if (this.updatedDate != o.updatedDate)
            return false
        if (this.updatedBy == null) {
            if (o.updatedBy != null)
                return false
        }
        else if (this.updatedBy != o.updatedBy)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + (if (this.scanDate == null) 0 else this.scanDate.hashCode())
        result = prime * result + (if (this.poNumber == null) 0 else this.poNumber.hashCode())
        result = prime * result + (if (this.importQty == null) 0 else this.importQty.hashCode())
        result = prime * result + (if (this.scanQty == null) 0 else this.scanQty.hashCode())
        result = prime * result + (if (this.seqNo == null) 0 else this.seqNo.hashCode())
        result = prime * result + (if (this.createdDate == null) 0 else this.createdDate.hashCode())
        result = prime * result + (if (this.createdBy == null) 0 else this.createdBy.hashCode())
        result = prime * result + (if (this.updatedDate == null) 0 else this.updatedDate.hashCode())
        result = prime * result + (if (this.updatedBy == null) 0 else this.updatedBy.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("CheckingHistory (")

        sb.append(id)
        sb.append(", ").append(scanDate)
        sb.append(", ").append(poNumber)
        sb.append(", ").append(importQty)
        sb.append(", ").append(scanQty)
        sb.append(", ").append(seqNo)
        sb.append(", ").append(createdDate)
        sb.append(", ").append(createdBy)
        sb.append(", ").append(updatedDate)
        sb.append(", ").append(updatedBy)

        sb.append(")")
        return sb.toString()
    }
}
