/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables.pojos


import java.io.Serializable
import java.math.BigDecimal
import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class EquipmentProductivity(
    var id: String? = null,
    var equipmentCode: String? = null,
    var description: String? = null,
    var frame_1: String? = null,
    var grpProcess: String? = null,
    var mold: String? = null,
    var operatingRate: BigDecimal? = null,
    var time: Int? = null,
    var count: BigDecimal? = null,
    var task: BigDecimal? = null,
    var sheetHour_100: BigDecimal? = null,
    var blockSh: BigDecimal? = null,
    var sltbHour: BigDecimal? = null,
    var sltbSheet: BigDecimal? = null,
    var sltbSet: BigDecimal? = null,
    var sltbBlock: BigDecimal? = null,
    var createdDate: OffsetDateTime? = null,
    var createdBy: String? = null,
    var updatedDate: OffsetDateTime? = null,
    var updatedBy: String? = null,
    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsDeleted")
    var isDeleted: Boolean? = null,
    var capHour: BigDecimal? = null,
    var capSheet: BigDecimal? = null,
    var capSet: BigDecimal? = null,
    var capBlock: BigDecimal? = null,
    var machineNumber: Int? = null,
    var processCode: String? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: EquipmentProductivity = other as EquipmentProductivity
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.equipmentCode == null) {
            if (o.equipmentCode != null)
                return false
        }
        else if (this.equipmentCode != o.equipmentCode)
            return false
        if (this.description == null) {
            if (o.description != null)
                return false
        }
        else if (this.description != o.description)
            return false
        if (this.frame_1 == null) {
            if (o.frame_1 != null)
                return false
        }
        else if (this.frame_1 != o.frame_1)
            return false
        if (this.grpProcess == null) {
            if (o.grpProcess != null)
                return false
        }
        else if (this.grpProcess != o.grpProcess)
            return false
        if (this.mold == null) {
            if (o.mold != null)
                return false
        }
        else if (this.mold != o.mold)
            return false
        if (this.operatingRate == null) {
            if (o.operatingRate != null)
                return false
        }
        else if (this.operatingRate != o.operatingRate)
            return false
        if (this.time == null) {
            if (o.time != null)
                return false
        }
        else if (this.time != o.time)
            return false
        if (this.count == null) {
            if (o.count != null)
                return false
        }
        else if (this.count != o.count)
            return false
        if (this.task == null) {
            if (o.task != null)
                return false
        }
        else if (this.task != o.task)
            return false
        if (this.sheetHour_100 == null) {
            if (o.sheetHour_100 != null)
                return false
        }
        else if (this.sheetHour_100 != o.sheetHour_100)
            return false
        if (this.blockSh == null) {
            if (o.blockSh != null)
                return false
        }
        else if (this.blockSh != o.blockSh)
            return false
        if (this.sltbHour == null) {
            if (o.sltbHour != null)
                return false
        }
        else if (this.sltbHour != o.sltbHour)
            return false
        if (this.sltbSheet == null) {
            if (o.sltbSheet != null)
                return false
        }
        else if (this.sltbSheet != o.sltbSheet)
            return false
        if (this.sltbSet == null) {
            if (o.sltbSet != null)
                return false
        }
        else if (this.sltbSet != o.sltbSet)
            return false
        if (this.sltbBlock == null) {
            if (o.sltbBlock != null)
                return false
        }
        else if (this.sltbBlock != o.sltbBlock)
            return false
        if (this.createdDate == null) {
            if (o.createdDate != null)
                return false
        }
        else if (this.createdDate != o.createdDate)
            return false
        if (this.createdBy == null) {
            if (o.createdBy != null)
                return false
        }
        else if (this.createdBy != o.createdBy)
            return false
        if (this.updatedDate == null) {
            if (o.updatedDate != null)
                return false
        }
        else if (this.updatedDate != o.updatedDate)
            return false
        if (this.updatedBy == null) {
            if (o.updatedBy != null)
                return false
        }
        else if (this.updatedBy != o.updatedBy)
            return false
        if (this.isDeleted == null) {
            if (o.isDeleted != null)
                return false
        }
        else if (this.isDeleted != o.isDeleted)
            return false
        if (this.capHour == null) {
            if (o.capHour != null)
                return false
        }
        else if (this.capHour != o.capHour)
            return false
        if (this.capSheet == null) {
            if (o.capSheet != null)
                return false
        }
        else if (this.capSheet != o.capSheet)
            return false
        if (this.capSet == null) {
            if (o.capSet != null)
                return false
        }
        else if (this.capSet != o.capSet)
            return false
        if (this.capBlock == null) {
            if (o.capBlock != null)
                return false
        }
        else if (this.capBlock != o.capBlock)
            return false
        if (this.machineNumber == null) {
            if (o.machineNumber != null)
                return false
        }
        else if (this.machineNumber != o.machineNumber)
            return false
        if (this.processCode == null) {
            if (o.processCode != null)
                return false
        }
        else if (this.processCode != o.processCode)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + (if (this.equipmentCode == null) 0 else this.equipmentCode.hashCode())
        result = prime * result + (if (this.description == null) 0 else this.description.hashCode())
        result = prime * result + (if (this.frame_1 == null) 0 else this.frame_1.hashCode())
        result = prime * result + (if (this.grpProcess == null) 0 else this.grpProcess.hashCode())
        result = prime * result + (if (this.mold == null) 0 else this.mold.hashCode())
        result = prime * result + (if (this.operatingRate == null) 0 else this.operatingRate.hashCode())
        result = prime * result + (if (this.time == null) 0 else this.time.hashCode())
        result = prime * result + (if (this.count == null) 0 else this.count.hashCode())
        result = prime * result + (if (this.task == null) 0 else this.task.hashCode())
        result = prime * result + (if (this.sheetHour_100 == null) 0 else this.sheetHour_100.hashCode())
        result = prime * result + (if (this.blockSh == null) 0 else this.blockSh.hashCode())
        result = prime * result + (if (this.sltbHour == null) 0 else this.sltbHour.hashCode())
        result = prime * result + (if (this.sltbSheet == null) 0 else this.sltbSheet.hashCode())
        result = prime * result + (if (this.sltbSet == null) 0 else this.sltbSet.hashCode())
        result = prime * result + (if (this.sltbBlock == null) 0 else this.sltbBlock.hashCode())
        result = prime * result + (if (this.createdDate == null) 0 else this.createdDate.hashCode())
        result = prime * result + (if (this.createdBy == null) 0 else this.createdBy.hashCode())
        result = prime * result + (if (this.updatedDate == null) 0 else this.updatedDate.hashCode())
        result = prime * result + (if (this.updatedBy == null) 0 else this.updatedBy.hashCode())
        result = prime * result + (if (this.isDeleted == null) 0 else this.isDeleted.hashCode())
        result = prime * result + (if (this.capHour == null) 0 else this.capHour.hashCode())
        result = prime * result + (if (this.capSheet == null) 0 else this.capSheet.hashCode())
        result = prime * result + (if (this.capSet == null) 0 else this.capSet.hashCode())
        result = prime * result + (if (this.capBlock == null) 0 else this.capBlock.hashCode())
        result = prime * result + (if (this.machineNumber == null) 0 else this.machineNumber.hashCode())
        result = prime * result + (if (this.processCode == null) 0 else this.processCode.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("EquipmentProductivity (")

        sb.append(id)
        sb.append(", ").append(equipmentCode)
        sb.append(", ").append(description)
        sb.append(", ").append(frame_1)
        sb.append(", ").append(grpProcess)
        sb.append(", ").append(mold)
        sb.append(", ").append(operatingRate)
        sb.append(", ").append(time)
        sb.append(", ").append(count)
        sb.append(", ").append(task)
        sb.append(", ").append(sheetHour_100)
        sb.append(", ").append(blockSh)
        sb.append(", ").append(sltbHour)
        sb.append(", ").append(sltbSheet)
        sb.append(", ").append(sltbSet)
        sb.append(", ").append(sltbBlock)
        sb.append(", ").append(createdDate)
        sb.append(", ").append(createdBy)
        sb.append(", ").append(updatedDate)
        sb.append(", ").append(updatedBy)
        sb.append(", ").append(isDeleted)
        sb.append(", ").append(capHour)
        sb.append(", ").append(capSheet)
        sb.append(", ").append(capSet)
        sb.append(", ").append(capBlock)
        sb.append(", ").append(machineNumber)
        sb.append(", ").append(processCode)

        sb.append(")")
        return sb.toString()
    }
}
