/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables.pojos


import java.io.Serializable
import java.math.BigDecimal
import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class InformationCalculateQuantityDetail(
    var id: String? = null,
    var monthReport: OffsetDateTime? = null,
    var productName: String? = null,
    var processStatisticCode: String? = null,
    var quantityProcessStatistic: Int? = null,
    var completionRate: BigDecimal? = null,
    var orderDate: OffsetDateTime? = null,
    var processCount: Int? = null,
    var blockSh: Int? = null,
    var blockQuantity: Int? = null,
    var informationCalculateQuantityId: String? = null,
    var createdDate: OffsetDateTime? = null,
    var createdBy: String? = null,
    var updatedDate: OffsetDateTime? = null,
    var updatedBy: String? = null,
    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsDeleted")
    var isDeleted: Boolean? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: InformationCalculateQuantityDetail = other as InformationCalculateQuantityDetail
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.monthReport == null) {
            if (o.monthReport != null)
                return false
        }
        else if (this.monthReport != o.monthReport)
            return false
        if (this.productName == null) {
            if (o.productName != null)
                return false
        }
        else if (this.productName != o.productName)
            return false
        if (this.processStatisticCode == null) {
            if (o.processStatisticCode != null)
                return false
        }
        else if (this.processStatisticCode != o.processStatisticCode)
            return false
        if (this.quantityProcessStatistic == null) {
            if (o.quantityProcessStatistic != null)
                return false
        }
        else if (this.quantityProcessStatistic != o.quantityProcessStatistic)
            return false
        if (this.completionRate == null) {
            if (o.completionRate != null)
                return false
        }
        else if (this.completionRate != o.completionRate)
            return false
        if (this.orderDate == null) {
            if (o.orderDate != null)
                return false
        }
        else if (this.orderDate != o.orderDate)
            return false
        if (this.processCount == null) {
            if (o.processCount != null)
                return false
        }
        else if (this.processCount != o.processCount)
            return false
        if (this.blockSh == null) {
            if (o.blockSh != null)
                return false
        }
        else if (this.blockSh != o.blockSh)
            return false
        if (this.blockQuantity == null) {
            if (o.blockQuantity != null)
                return false
        }
        else if (this.blockQuantity != o.blockQuantity)
            return false
        if (this.informationCalculateQuantityId == null) {
            if (o.informationCalculateQuantityId != null)
                return false
        }
        else if (this.informationCalculateQuantityId != o.informationCalculateQuantityId)
            return false
        if (this.createdDate == null) {
            if (o.createdDate != null)
                return false
        }
        else if (this.createdDate != o.createdDate)
            return false
        if (this.createdBy == null) {
            if (o.createdBy != null)
                return false
        }
        else if (this.createdBy != o.createdBy)
            return false
        if (this.updatedDate == null) {
            if (o.updatedDate != null)
                return false
        }
        else if (this.updatedDate != o.updatedDate)
            return false
        if (this.updatedBy == null) {
            if (o.updatedBy != null)
                return false
        }
        else if (this.updatedBy != o.updatedBy)
            return false
        if (this.isDeleted == null) {
            if (o.isDeleted != null)
                return false
        }
        else if (this.isDeleted != o.isDeleted)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + (if (this.monthReport == null) 0 else this.monthReport.hashCode())
        result = prime * result + (if (this.productName == null) 0 else this.productName.hashCode())
        result = prime * result + (if (this.processStatisticCode == null) 0 else this.processStatisticCode.hashCode())
        result = prime * result + (if (this.quantityProcessStatistic == null) 0 else this.quantityProcessStatistic.hashCode())
        result = prime * result + (if (this.completionRate == null) 0 else this.completionRate.hashCode())
        result = prime * result + (if (this.orderDate == null) 0 else this.orderDate.hashCode())
        result = prime * result + (if (this.processCount == null) 0 else this.processCount.hashCode())
        result = prime * result + (if (this.blockSh == null) 0 else this.blockSh.hashCode())
        result = prime * result + (if (this.blockQuantity == null) 0 else this.blockQuantity.hashCode())
        result = prime * result + (if (this.informationCalculateQuantityId == null) 0 else this.informationCalculateQuantityId.hashCode())
        result = prime * result + (if (this.createdDate == null) 0 else this.createdDate.hashCode())
        result = prime * result + (if (this.createdBy == null) 0 else this.createdBy.hashCode())
        result = prime * result + (if (this.updatedDate == null) 0 else this.updatedDate.hashCode())
        result = prime * result + (if (this.updatedBy == null) 0 else this.updatedBy.hashCode())
        result = prime * result + (if (this.isDeleted == null) 0 else this.isDeleted.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("InformationCalculateQuantityDetail (")

        sb.append(id)
        sb.append(", ").append(monthReport)
        sb.append(", ").append(productName)
        sb.append(", ").append(processStatisticCode)
        sb.append(", ").append(quantityProcessStatistic)
        sb.append(", ").append(completionRate)
        sb.append(", ").append(orderDate)
        sb.append(", ").append(processCount)
        sb.append(", ").append(blockSh)
        sb.append(", ").append(blockQuantity)
        sb.append(", ").append(informationCalculateQuantityId)
        sb.append(", ").append(createdDate)
        sb.append(", ").append(createdBy)
        sb.append(", ").append(updatedDate)
        sb.append(", ").append(updatedBy)
        sb.append(", ").append(isDeleted)

        sb.append(")")
        return sb.toString()
    }
}
