/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables.pojos


import java.io.Serializable
import java.math.BigDecimal
import java.time.LocalDate
import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class NewCheckingTransaction(
    var id: String? = null,
    var invoiceNumber: String? = null,
    var poNumber: String? = null,
    var scanQty: BigDecimal? = null,
    var lotNo: String? = null,
    var checkTimes: Int? = null,
    var receivingDate: LocalDate? = null,
    var specifyInvoice: Boolean? = null,
    var createdDate: OffsetDateTime? = null,
    var createdBy: String? = null,
    var updatedDate: OffsetDateTime? = null,
    var updatedBy: String? = null,
    var formCode: String? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: NewCheckingTransaction = other as NewCheckingTransaction
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.invoiceNumber == null) {
            if (o.invoiceNumber != null)
                return false
        }
        else if (this.invoiceNumber != o.invoiceNumber)
            return false
        if (this.poNumber == null) {
            if (o.poNumber != null)
                return false
        }
        else if (this.poNumber != o.poNumber)
            return false
        if (this.scanQty == null) {
            if (o.scanQty != null)
                return false
        }
        else if (this.scanQty != o.scanQty)
            return false
        if (this.lotNo == null) {
            if (o.lotNo != null)
                return false
        }
        else if (this.lotNo != o.lotNo)
            return false
        if (this.checkTimes == null) {
            if (o.checkTimes != null)
                return false
        }
        else if (this.checkTimes != o.checkTimes)
            return false
        if (this.receivingDate == null) {
            if (o.receivingDate != null)
                return false
        }
        else if (this.receivingDate != o.receivingDate)
            return false
        if (this.specifyInvoice == null) {
            if (o.specifyInvoice != null)
                return false
        }
        else if (this.specifyInvoice != o.specifyInvoice)
            return false
        if (this.createdDate == null) {
            if (o.createdDate != null)
                return false
        }
        else if (this.createdDate != o.createdDate)
            return false
        if (this.createdBy == null) {
            if (o.createdBy != null)
                return false
        }
        else if (this.createdBy != o.createdBy)
            return false
        if (this.updatedDate == null) {
            if (o.updatedDate != null)
                return false
        }
        else if (this.updatedDate != o.updatedDate)
            return false
        if (this.updatedBy == null) {
            if (o.updatedBy != null)
                return false
        }
        else if (this.updatedBy != o.updatedBy)
            return false
        if (this.formCode == null) {
            if (o.formCode != null)
                return false
        }
        else if (this.formCode != o.formCode)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + (if (this.invoiceNumber == null) 0 else this.invoiceNumber.hashCode())
        result = prime * result + (if (this.poNumber == null) 0 else this.poNumber.hashCode())
        result = prime * result + (if (this.scanQty == null) 0 else this.scanQty.hashCode())
        result = prime * result + (if (this.lotNo == null) 0 else this.lotNo.hashCode())
        result = prime * result + (if (this.checkTimes == null) 0 else this.checkTimes.hashCode())
        result = prime * result + (if (this.receivingDate == null) 0 else this.receivingDate.hashCode())
        result = prime * result + (if (this.specifyInvoice == null) 0 else this.specifyInvoice.hashCode())
        result = prime * result + (if (this.createdDate == null) 0 else this.createdDate.hashCode())
        result = prime * result + (if (this.createdBy == null) 0 else this.createdBy.hashCode())
        result = prime * result + (if (this.updatedDate == null) 0 else this.updatedDate.hashCode())
        result = prime * result + (if (this.updatedBy == null) 0 else this.updatedBy.hashCode())
        result = prime * result + (if (this.formCode == null) 0 else this.formCode.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("NewCheckingTransaction (")

        sb.append(id)
        sb.append(", ").append(invoiceNumber)
        sb.append(", ").append(poNumber)
        sb.append(", ").append(scanQty)
        sb.append(", ").append(lotNo)
        sb.append(", ").append(checkTimes)
        sb.append(", ").append(receivingDate)
        sb.append(", ").append(specifyInvoice)
        sb.append(", ").append(createdDate)
        sb.append(", ").append(createdBy)
        sb.append(", ").append(updatedDate)
        sb.append(", ").append(updatedBy)
        sb.append(", ").append(formCode)

        sb.append(")")
        return sb.toString()
    }
}
