/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables.pojos


import java.io.Serializable
import java.math.BigDecimal
import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class PlanProcessTemp(
    var id: String? = null,
    var planId: String? = null,
    var planProductId: String? = null,
    var processCode: String? = null,
    var processName: String? = null,
    var processConvertCode: String? = null,
    var layerCode: String? = null,
    var completionRate: BigDecimal? = null,
    var inventory: Int? = null,
    var parentId: String? = null,
    var unit: String? = null,
    var processSequence: Int? = null,
    var processNameJp: String? = null,
    var processGroup: String? = null,
    var processStatisticCode: String? = null,
    var createdDate: OffsetDateTime? = null,
    var createdBy: String? = null,
    var updatedDate: OffsetDateTime? = null,
    var updatedBy: String? = null,
    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsDeleted")
    var isDeleted: Boolean? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: PlanProcessTemp = other as PlanProcessTemp
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.planId == null) {
            if (o.planId != null)
                return false
        }
        else if (this.planId != o.planId)
            return false
        if (this.planProductId == null) {
            if (o.planProductId != null)
                return false
        }
        else if (this.planProductId != o.planProductId)
            return false
        if (this.processCode == null) {
            if (o.processCode != null)
                return false
        }
        else if (this.processCode != o.processCode)
            return false
        if (this.processName == null) {
            if (o.processName != null)
                return false
        }
        else if (this.processName != o.processName)
            return false
        if (this.processConvertCode == null) {
            if (o.processConvertCode != null)
                return false
        }
        else if (this.processConvertCode != o.processConvertCode)
            return false
        if (this.layerCode == null) {
            if (o.layerCode != null)
                return false
        }
        else if (this.layerCode != o.layerCode)
            return false
        if (this.completionRate == null) {
            if (o.completionRate != null)
                return false
        }
        else if (this.completionRate != o.completionRate)
            return false
        if (this.inventory == null) {
            if (o.inventory != null)
                return false
        }
        else if (this.inventory != o.inventory)
            return false
        if (this.parentId == null) {
            if (o.parentId != null)
                return false
        }
        else if (this.parentId != o.parentId)
            return false
        if (this.unit == null) {
            if (o.unit != null)
                return false
        }
        else if (this.unit != o.unit)
            return false
        if (this.processSequence == null) {
            if (o.processSequence != null)
                return false
        }
        else if (this.processSequence != o.processSequence)
            return false
        if (this.processNameJp == null) {
            if (o.processNameJp != null)
                return false
        }
        else if (this.processNameJp != o.processNameJp)
            return false
        if (this.processGroup == null) {
            if (o.processGroup != null)
                return false
        }
        else if (this.processGroup != o.processGroup)
            return false
        if (this.processStatisticCode == null) {
            if (o.processStatisticCode != null)
                return false
        }
        else if (this.processStatisticCode != o.processStatisticCode)
            return false
        if (this.createdDate == null) {
            if (o.createdDate != null)
                return false
        }
        else if (this.createdDate != o.createdDate)
            return false
        if (this.createdBy == null) {
            if (o.createdBy != null)
                return false
        }
        else if (this.createdBy != o.createdBy)
            return false
        if (this.updatedDate == null) {
            if (o.updatedDate != null)
                return false
        }
        else if (this.updatedDate != o.updatedDate)
            return false
        if (this.updatedBy == null) {
            if (o.updatedBy != null)
                return false
        }
        else if (this.updatedBy != o.updatedBy)
            return false
        if (this.isDeleted == null) {
            if (o.isDeleted != null)
                return false
        }
        else if (this.isDeleted != o.isDeleted)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + (if (this.planId == null) 0 else this.planId.hashCode())
        result = prime * result + (if (this.planProductId == null) 0 else this.planProductId.hashCode())
        result = prime * result + (if (this.processCode == null) 0 else this.processCode.hashCode())
        result = prime * result + (if (this.processName == null) 0 else this.processName.hashCode())
        result = prime * result + (if (this.processConvertCode == null) 0 else this.processConvertCode.hashCode())
        result = prime * result + (if (this.layerCode == null) 0 else this.layerCode.hashCode())
        result = prime * result + (if (this.completionRate == null) 0 else this.completionRate.hashCode())
        result = prime * result + (if (this.inventory == null) 0 else this.inventory.hashCode())
        result = prime * result + (if (this.parentId == null) 0 else this.parentId.hashCode())
        result = prime * result + (if (this.unit == null) 0 else this.unit.hashCode())
        result = prime * result + (if (this.processSequence == null) 0 else this.processSequence.hashCode())
        result = prime * result + (if (this.processNameJp == null) 0 else this.processNameJp.hashCode())
        result = prime * result + (if (this.processGroup == null) 0 else this.processGroup.hashCode())
        result = prime * result + (if (this.processStatisticCode == null) 0 else this.processStatisticCode.hashCode())
        result = prime * result + (if (this.createdDate == null) 0 else this.createdDate.hashCode())
        result = prime * result + (if (this.createdBy == null) 0 else this.createdBy.hashCode())
        result = prime * result + (if (this.updatedDate == null) 0 else this.updatedDate.hashCode())
        result = prime * result + (if (this.updatedBy == null) 0 else this.updatedBy.hashCode())
        result = prime * result + (if (this.isDeleted == null) 0 else this.isDeleted.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("PlanProcessTemp (")

        sb.append(id)
        sb.append(", ").append(planId)
        sb.append(", ").append(planProductId)
        sb.append(", ").append(processCode)
        sb.append(", ").append(processName)
        sb.append(", ").append(processConvertCode)
        sb.append(", ").append(layerCode)
        sb.append(", ").append(completionRate)
        sb.append(", ").append(inventory)
        sb.append(", ").append(parentId)
        sb.append(", ").append(unit)
        sb.append(", ").append(processSequence)
        sb.append(", ").append(processNameJp)
        sb.append(", ").append(processGroup)
        sb.append(", ").append(processStatisticCode)
        sb.append(", ").append(createdDate)
        sb.append(", ").append(createdBy)
        sb.append(", ").append(updatedDate)
        sb.append(", ").append(updatedBy)
        sb.append(", ").append(isDeleted)

        sb.append(")")
        return sb.toString()
    }
}
