/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables.pojos


import java.io.Serializable
import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Plan(
    var id: String? = null,
    var startDate: OffsetDateTime? = null,
    var endDate: OffsetDateTime? = null,
    var version: Int? = null,
    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsActive")
    var isActive: Boolean? = null,
    var createdDate: OffsetDateTime? = null,
    var createdBy: String? = null,
    var updatedDate: OffsetDateTime? = null,
    var updatedBy: String? = null,
    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsDeleted")
    var isDeleted: Boolean? = null,
    var planCode: String? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Plan = other as Plan
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.startDate == null) {
            if (o.startDate != null)
                return false
        }
        else if (this.startDate != o.startDate)
            return false
        if (this.endDate == null) {
            if (o.endDate != null)
                return false
        }
        else if (this.endDate != o.endDate)
            return false
        if (this.version == null) {
            if (o.version != null)
                return false
        }
        else if (this.version != o.version)
            return false
        if (this.isActive == null) {
            if (o.isActive != null)
                return false
        }
        else if (this.isActive != o.isActive)
            return false
        if (this.createdDate == null) {
            if (o.createdDate != null)
                return false
        }
        else if (this.createdDate != o.createdDate)
            return false
        if (this.createdBy == null) {
            if (o.createdBy != null)
                return false
        }
        else if (this.createdBy != o.createdBy)
            return false
        if (this.updatedDate == null) {
            if (o.updatedDate != null)
                return false
        }
        else if (this.updatedDate != o.updatedDate)
            return false
        if (this.updatedBy == null) {
            if (o.updatedBy != null)
                return false
        }
        else if (this.updatedBy != o.updatedBy)
            return false
        if (this.isDeleted == null) {
            if (o.isDeleted != null)
                return false
        }
        else if (this.isDeleted != o.isDeleted)
            return false
        if (this.planCode == null) {
            if (o.planCode != null)
                return false
        }
        else if (this.planCode != o.planCode)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + (if (this.startDate == null) 0 else this.startDate.hashCode())
        result = prime * result + (if (this.endDate == null) 0 else this.endDate.hashCode())
        result = prime * result + (if (this.version == null) 0 else this.version.hashCode())
        result = prime * result + (if (this.isActive == null) 0 else this.isActive.hashCode())
        result = prime * result + (if (this.createdDate == null) 0 else this.createdDate.hashCode())
        result = prime * result + (if (this.createdBy == null) 0 else this.createdBy.hashCode())
        result = prime * result + (if (this.updatedDate == null) 0 else this.updatedDate.hashCode())
        result = prime * result + (if (this.updatedBy == null) 0 else this.updatedBy.hashCode())
        result = prime * result + (if (this.isDeleted == null) 0 else this.isDeleted.hashCode())
        result = prime * result + (if (this.planCode == null) 0 else this.planCode.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Plan (")

        sb.append(id)
        sb.append(", ").append(startDate)
        sb.append(", ").append(endDate)
        sb.append(", ").append(version)
        sb.append(", ").append(isActive)
        sb.append(", ").append(createdDate)
        sb.append(", ").append(createdBy)
        sb.append(", ").append(updatedDate)
        sb.append(", ").append(updatedBy)
        sb.append(", ").append(isDeleted)
        sb.append(", ").append(planCode)

        sb.append(")")
        return sb.toString()
    }
}
