/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class ProductProcess(
    var id: String? = null,
    var processName: String? = null,
    var processNameJp: String? = null,
    var processConvertCode: String? = null,
    var processStatisticCode: String? = null,
    var processInventoryCode: String? = null,
    var createdDate: LocalDateTime? = null,
    var createdBy: String? = null,
    var updatedDate: LocalDateTime? = null,
    var updatedBy: String? = null,
    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsDeleted")
    var isDeleted: Boolean? = null,
    var processProcedureStructureId: String? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: ProductProcess = other as ProductProcess
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.processName == null) {
            if (o.processName != null)
                return false
        }
        else if (this.processName != o.processName)
            return false
        if (this.processNameJp == null) {
            if (o.processNameJp != null)
                return false
        }
        else if (this.processNameJp != o.processNameJp)
            return false
        if (this.processConvertCode == null) {
            if (o.processConvertCode != null)
                return false
        }
        else if (this.processConvertCode != o.processConvertCode)
            return false
        if (this.processStatisticCode == null) {
            if (o.processStatisticCode != null)
                return false
        }
        else if (this.processStatisticCode != o.processStatisticCode)
            return false
        if (this.processInventoryCode == null) {
            if (o.processInventoryCode != null)
                return false
        }
        else if (this.processInventoryCode != o.processInventoryCode)
            return false
        if (this.createdDate == null) {
            if (o.createdDate != null)
                return false
        }
        else if (this.createdDate != o.createdDate)
            return false
        if (this.createdBy == null) {
            if (o.createdBy != null)
                return false
        }
        else if (this.createdBy != o.createdBy)
            return false
        if (this.updatedDate == null) {
            if (o.updatedDate != null)
                return false
        }
        else if (this.updatedDate != o.updatedDate)
            return false
        if (this.updatedBy == null) {
            if (o.updatedBy != null)
                return false
        }
        else if (this.updatedBy != o.updatedBy)
            return false
        if (this.isDeleted == null) {
            if (o.isDeleted != null)
                return false
        }
        else if (this.isDeleted != o.isDeleted)
            return false
        if (this.processProcedureStructureId == null) {
            if (o.processProcedureStructureId != null)
                return false
        }
        else if (this.processProcedureStructureId != o.processProcedureStructureId)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + (if (this.processName == null) 0 else this.processName.hashCode())
        result = prime * result + (if (this.processNameJp == null) 0 else this.processNameJp.hashCode())
        result = prime * result + (if (this.processConvertCode == null) 0 else this.processConvertCode.hashCode())
        result = prime * result + (if (this.processStatisticCode == null) 0 else this.processStatisticCode.hashCode())
        result = prime * result + (if (this.processInventoryCode == null) 0 else this.processInventoryCode.hashCode())
        result = prime * result + (if (this.createdDate == null) 0 else this.createdDate.hashCode())
        result = prime * result + (if (this.createdBy == null) 0 else this.createdBy.hashCode())
        result = prime * result + (if (this.updatedDate == null) 0 else this.updatedDate.hashCode())
        result = prime * result + (if (this.updatedBy == null) 0 else this.updatedBy.hashCode())
        result = prime * result + (if (this.isDeleted == null) 0 else this.isDeleted.hashCode())
        result = prime * result + (if (this.processProcedureStructureId == null) 0 else this.processProcedureStructureId.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("ProductProcess (")

        sb.append(id)
        sb.append(", ").append(processName)
        sb.append(", ").append(processNameJp)
        sb.append(", ").append(processConvertCode)
        sb.append(", ").append(processStatisticCode)
        sb.append(", ").append(processInventoryCode)
        sb.append(", ").append(createdDate)
        sb.append(", ").append(createdBy)
        sb.append(", ").append(updatedDate)
        sb.append(", ").append(updatedBy)
        sb.append(", ").append(isDeleted)
        sb.append(", ").append(processProcedureStructureId)

        sb.append(")")
        return sb.toString()
    }
}
