/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables.pojos


import java.io.Serializable
import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class TapeInventory(
    var id: String? = null,
    var exportType: String? = null,
    var productName: String? = null,
    var productNameShortCut: String? = null,
    var tapeInWarehouse: Int? = null,
    var tapeInDepartment: Int? = null,
    var tapeNg: Int? = null,
    var createdDate: OffsetDateTime? = null,
    var createdBy: String? = null,
    var updatedDate: OffsetDateTime? = null,
    var updatedBy: String? = null,
    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsDeleted")
    var isDeleted: Boolean? = null,
    var stocktakingDay: OffsetDateTime? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: TapeInventory = other as TapeInventory
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.exportType == null) {
            if (o.exportType != null)
                return false
        }
        else if (this.exportType != o.exportType)
            return false
        if (this.productName == null) {
            if (o.productName != null)
                return false
        }
        else if (this.productName != o.productName)
            return false
        if (this.productNameShortCut == null) {
            if (o.productNameShortCut != null)
                return false
        }
        else if (this.productNameShortCut != o.productNameShortCut)
            return false
        if (this.tapeInWarehouse == null) {
            if (o.tapeInWarehouse != null)
                return false
        }
        else if (this.tapeInWarehouse != o.tapeInWarehouse)
            return false
        if (this.tapeInDepartment == null) {
            if (o.tapeInDepartment != null)
                return false
        }
        else if (this.tapeInDepartment != o.tapeInDepartment)
            return false
        if (this.tapeNg == null) {
            if (o.tapeNg != null)
                return false
        }
        else if (this.tapeNg != o.tapeNg)
            return false
        if (this.createdDate == null) {
            if (o.createdDate != null)
                return false
        }
        else if (this.createdDate != o.createdDate)
            return false
        if (this.createdBy == null) {
            if (o.createdBy != null)
                return false
        }
        else if (this.createdBy != o.createdBy)
            return false
        if (this.updatedDate == null) {
            if (o.updatedDate != null)
                return false
        }
        else if (this.updatedDate != o.updatedDate)
            return false
        if (this.updatedBy == null) {
            if (o.updatedBy != null)
                return false
        }
        else if (this.updatedBy != o.updatedBy)
            return false
        if (this.isDeleted == null) {
            if (o.isDeleted != null)
                return false
        }
        else if (this.isDeleted != o.isDeleted)
            return false
        if (this.stocktakingDay == null) {
            if (o.stocktakingDay != null)
                return false
        }
        else if (this.stocktakingDay != o.stocktakingDay)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + (if (this.exportType == null) 0 else this.exportType.hashCode())
        result = prime * result + (if (this.productName == null) 0 else this.productName.hashCode())
        result = prime * result + (if (this.productNameShortCut == null) 0 else this.productNameShortCut.hashCode())
        result = prime * result + (if (this.tapeInWarehouse == null) 0 else this.tapeInWarehouse.hashCode())
        result = prime * result + (if (this.tapeInDepartment == null) 0 else this.tapeInDepartment.hashCode())
        result = prime * result + (if (this.tapeNg == null) 0 else this.tapeNg.hashCode())
        result = prime * result + (if (this.createdDate == null) 0 else this.createdDate.hashCode())
        result = prime * result + (if (this.createdBy == null) 0 else this.createdBy.hashCode())
        result = prime * result + (if (this.updatedDate == null) 0 else this.updatedDate.hashCode())
        result = prime * result + (if (this.updatedBy == null) 0 else this.updatedBy.hashCode())
        result = prime * result + (if (this.isDeleted == null) 0 else this.isDeleted.hashCode())
        result = prime * result + (if (this.stocktakingDay == null) 0 else this.stocktakingDay.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("TapeInventory (")

        sb.append(id)
        sb.append(", ").append(exportType)
        sb.append(", ").append(productName)
        sb.append(", ").append(productNameShortCut)
        sb.append(", ").append(tapeInWarehouse)
        sb.append(", ").append(tapeInDepartment)
        sb.append(", ").append(tapeNg)
        sb.append(", ").append(createdDate)
        sb.append(", ").append(createdBy)
        sb.append(", ").append(updatedDate)
        sb.append(", ").append(updatedBy)
        sb.append(", ").append(isDeleted)
        sb.append(", ").append(stocktakingDay)

        sb.append(")")
        return sb.toString()
    }
}
