/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class WestFactoryLayout(
    var id: String? = null,
    var rowNum: Int? = null,
    var column1: String? = null,
    var column2: String? = null,
    var column3: String? = null,
    var column4: String? = null,
    var column5: String? = null,
    var column6: String? = null,
    var column7: String? = null,
    var column8: String? = null,
    var column9: String? = null,
    var column10: String? = null,
    var column11: String? = null,
    var column12: String? = null,
    var column13: String? = null,
    var column14: String? = null,
    var column15: String? = null,
    var column16: String? = null,
    var column17: String? = null,
    var column18: String? = null,
    var column19: String? = null,
    var column20: String? = null,
    var column21: String? = null,
    var column22: String? = null,
    var column23: String? = null,
    var column24: String? = null,
    var column25: String? = null,
    var column26: String? = null,
    var column27: String? = null,
    var column28: String? = null,
    var column29: String? = null,
    var column30: String? = null,
    var column31: String? = null,
    var column32: String? = null,
    var column33: String? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: WestFactoryLayout = other as WestFactoryLayout
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.rowNum == null) {
            if (o.rowNum != null)
                return false
        }
        else if (this.rowNum != o.rowNum)
            return false
        if (this.column1 == null) {
            if (o.column1 != null)
                return false
        }
        else if (this.column1 != o.column1)
            return false
        if (this.column2 == null) {
            if (o.column2 != null)
                return false
        }
        else if (this.column2 != o.column2)
            return false
        if (this.column3 == null) {
            if (o.column3 != null)
                return false
        }
        else if (this.column3 != o.column3)
            return false
        if (this.column4 == null) {
            if (o.column4 != null)
                return false
        }
        else if (this.column4 != o.column4)
            return false
        if (this.column5 == null) {
            if (o.column5 != null)
                return false
        }
        else if (this.column5 != o.column5)
            return false
        if (this.column6 == null) {
            if (o.column6 != null)
                return false
        }
        else if (this.column6 != o.column6)
            return false
        if (this.column7 == null) {
            if (o.column7 != null)
                return false
        }
        else if (this.column7 != o.column7)
            return false
        if (this.column8 == null) {
            if (o.column8 != null)
                return false
        }
        else if (this.column8 != o.column8)
            return false
        if (this.column9 == null) {
            if (o.column9 != null)
                return false
        }
        else if (this.column9 != o.column9)
            return false
        if (this.column10 == null) {
            if (o.column10 != null)
                return false
        }
        else if (this.column10 != o.column10)
            return false
        if (this.column11 == null) {
            if (o.column11 != null)
                return false
        }
        else if (this.column11 != o.column11)
            return false
        if (this.column12 == null) {
            if (o.column12 != null)
                return false
        }
        else if (this.column12 != o.column12)
            return false
        if (this.column13 == null) {
            if (o.column13 != null)
                return false
        }
        else if (this.column13 != o.column13)
            return false
        if (this.column14 == null) {
            if (o.column14 != null)
                return false
        }
        else if (this.column14 != o.column14)
            return false
        if (this.column15 == null) {
            if (o.column15 != null)
                return false
        }
        else if (this.column15 != o.column15)
            return false
        if (this.column16 == null) {
            if (o.column16 != null)
                return false
        }
        else if (this.column16 != o.column16)
            return false
        if (this.column17 == null) {
            if (o.column17 != null)
                return false
        }
        else if (this.column17 != o.column17)
            return false
        if (this.column18 == null) {
            if (o.column18 != null)
                return false
        }
        else if (this.column18 != o.column18)
            return false
        if (this.column19 == null) {
            if (o.column19 != null)
                return false
        }
        else if (this.column19 != o.column19)
            return false
        if (this.column20 == null) {
            if (o.column20 != null)
                return false
        }
        else if (this.column20 != o.column20)
            return false
        if (this.column21 == null) {
            if (o.column21 != null)
                return false
        }
        else if (this.column21 != o.column21)
            return false
        if (this.column22 == null) {
            if (o.column22 != null)
                return false
        }
        else if (this.column22 != o.column22)
            return false
        if (this.column23 == null) {
            if (o.column23 != null)
                return false
        }
        else if (this.column23 != o.column23)
            return false
        if (this.column24 == null) {
            if (o.column24 != null)
                return false
        }
        else if (this.column24 != o.column24)
            return false
        if (this.column25 == null) {
            if (o.column25 != null)
                return false
        }
        else if (this.column25 != o.column25)
            return false
        if (this.column26 == null) {
            if (o.column26 != null)
                return false
        }
        else if (this.column26 != o.column26)
            return false
        if (this.column27 == null) {
            if (o.column27 != null)
                return false
        }
        else if (this.column27 != o.column27)
            return false
        if (this.column28 == null) {
            if (o.column28 != null)
                return false
        }
        else if (this.column28 != o.column28)
            return false
        if (this.column29 == null) {
            if (o.column29 != null)
                return false
        }
        else if (this.column29 != o.column29)
            return false
        if (this.column30 == null) {
            if (o.column30 != null)
                return false
        }
        else if (this.column30 != o.column30)
            return false
        if (this.column31 == null) {
            if (o.column31 != null)
                return false
        }
        else if (this.column31 != o.column31)
            return false
        if (this.column32 == null) {
            if (o.column32 != null)
                return false
        }
        else if (this.column32 != o.column32)
            return false
        if (this.column33 == null) {
            if (o.column33 != null)
                return false
        }
        else if (this.column33 != o.column33)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + (if (this.rowNum == null) 0 else this.rowNum.hashCode())
        result = prime * result + (if (this.column1 == null) 0 else this.column1.hashCode())
        result = prime * result + (if (this.column2 == null) 0 else this.column2.hashCode())
        result = prime * result + (if (this.column3 == null) 0 else this.column3.hashCode())
        result = prime * result + (if (this.column4 == null) 0 else this.column4.hashCode())
        result = prime * result + (if (this.column5 == null) 0 else this.column5.hashCode())
        result = prime * result + (if (this.column6 == null) 0 else this.column6.hashCode())
        result = prime * result + (if (this.column7 == null) 0 else this.column7.hashCode())
        result = prime * result + (if (this.column8 == null) 0 else this.column8.hashCode())
        result = prime * result + (if (this.column9 == null) 0 else this.column9.hashCode())
        result = prime * result + (if (this.column10 == null) 0 else this.column10.hashCode())
        result = prime * result + (if (this.column11 == null) 0 else this.column11.hashCode())
        result = prime * result + (if (this.column12 == null) 0 else this.column12.hashCode())
        result = prime * result + (if (this.column13 == null) 0 else this.column13.hashCode())
        result = prime * result + (if (this.column14 == null) 0 else this.column14.hashCode())
        result = prime * result + (if (this.column15 == null) 0 else this.column15.hashCode())
        result = prime * result + (if (this.column16 == null) 0 else this.column16.hashCode())
        result = prime * result + (if (this.column17 == null) 0 else this.column17.hashCode())
        result = prime * result + (if (this.column18 == null) 0 else this.column18.hashCode())
        result = prime * result + (if (this.column19 == null) 0 else this.column19.hashCode())
        result = prime * result + (if (this.column20 == null) 0 else this.column20.hashCode())
        result = prime * result + (if (this.column21 == null) 0 else this.column21.hashCode())
        result = prime * result + (if (this.column22 == null) 0 else this.column22.hashCode())
        result = prime * result + (if (this.column23 == null) 0 else this.column23.hashCode())
        result = prime * result + (if (this.column24 == null) 0 else this.column24.hashCode())
        result = prime * result + (if (this.column25 == null) 0 else this.column25.hashCode())
        result = prime * result + (if (this.column26 == null) 0 else this.column26.hashCode())
        result = prime * result + (if (this.column27 == null) 0 else this.column27.hashCode())
        result = prime * result + (if (this.column28 == null) 0 else this.column28.hashCode())
        result = prime * result + (if (this.column29 == null) 0 else this.column29.hashCode())
        result = prime * result + (if (this.column30 == null) 0 else this.column30.hashCode())
        result = prime * result + (if (this.column31 == null) 0 else this.column31.hashCode())
        result = prime * result + (if (this.column32 == null) 0 else this.column32.hashCode())
        result = prime * result + (if (this.column33 == null) 0 else this.column33.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("WestFactoryLayout (")

        sb.append(id)
        sb.append(", ").append(rowNum)
        sb.append(", ").append(column1)
        sb.append(", ").append(column2)
        sb.append(", ").append(column3)
        sb.append(", ").append(column4)
        sb.append(", ").append(column5)
        sb.append(", ").append(column6)
        sb.append(", ").append(column7)
        sb.append(", ").append(column8)
        sb.append(", ").append(column9)
        sb.append(", ").append(column10)
        sb.append(", ").append(column11)
        sb.append(", ").append(column12)
        sb.append(", ").append(column13)
        sb.append(", ").append(column14)
        sb.append(", ").append(column15)
        sb.append(", ").append(column16)
        sb.append(", ").append(column17)
        sb.append(", ").append(column18)
        sb.append(", ").append(column19)
        sb.append(", ").append(column20)
        sb.append(", ").append(column21)
        sb.append(", ").append(column22)
        sb.append(", ").append(column23)
        sb.append(", ").append(column24)
        sb.append(", ").append(column25)
        sb.append(", ").append(column26)
        sb.append(", ").append(column27)
        sb.append(", ").append(column28)
        sb.append(", ").append(column29)
        sb.append(", ").append(column30)
        sb.append(", ").append(column31)
        sb.append(", ").append(column32)
        sb.append(", ").append(column33)

        sb.append(")")
        return sb.toString()
    }
}
