/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables


import com.kcvn.spm.model.Public
import com.kcvn.spm.model.keys.LOCATIONS_KEY_1
import com.kcvn.spm.model.keys.LOCATIONS_PKEY_1
import com.kcvn.spm.model.tables.records.ApkVersionRecord

import java.time.OffsetDateTime
import java.util.UUID
import java.util.function.Function

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row9
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ApkVersion(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, ApkVersionRecord>?,
    aliased: Table<ApkVersionRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<ApkVersionRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.apk_version</code>
         */
        val APK_VERSION: ApkVersion = ApkVersion()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ApkVersionRecord> = ApkVersionRecord::class.java

    /**
     * The column <code>public.apk_version.id</code>.
     */
    val ID: TableField<ApkVersionRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.apk_version.ip_add</code>.
     */
    val IP_ADD: TableField<ApkVersionRecord, String?> = createField(DSL.name("ip_add"), SQLDataType.VARCHAR(20), this, "")

    /**
     * The column <code>public.apk_version.device_name</code>.
     */
    val DEVICE_NAME: TableField<ApkVersionRecord, String?> = createField(DSL.name("device_name"), SQLDataType.VARCHAR(50), this, "")

    /**
     * The column <code>public.apk_version.current_version</code>.
     */
    val CURRENT_VERSION: TableField<ApkVersionRecord, String?> = createField(DSL.name("current_version"), SQLDataType.VARCHAR(20), this, "")

    /**
     * The column <code>public.apk_version.new_version</code>.
     */
    val NEW_VERSION: TableField<ApkVersionRecord, String?> = createField(DSL.name("new_version"), SQLDataType.VARCHAR(20), this, "")

    /**
     * The column <code>public.apk_version.created_by</code>.
     */
    val CREATED_BY: TableField<ApkVersionRecord, String?> = createField(DSL.name("created_by"), SQLDataType.VARCHAR(20), this, "")

    /**
     * The column <code>public.apk_version.updated_by</code>.
     */
    val UPDATED_BY: TableField<ApkVersionRecord, String?> = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(20), this, "")

    /**
     * The column <code>public.apk_version.created_time</code>.
     */
    val CREATED_TIME: TableField<ApkVersionRecord, OffsetDateTime?> = createField(DSL.name("created_time"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.apk_version.updated_time</code>.
     */
    val UPDATED_TIME: TableField<ApkVersionRecord, OffsetDateTime?> = createField(DSL.name("updated_time"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    private constructor(alias: Name, aliased: Table<ApkVersionRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<ApkVersionRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.apk_version</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.apk_version</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.apk_version</code> table reference
     */
    constructor(): this(DSL.name("apk_version"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, ApkVersionRecord>): this(Internal.createPathAlias(child, key), child, key, APK_VERSION, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<ApkVersionRecord> = LOCATIONS_PKEY_1
    override fun getUniqueKeys(): List<UniqueKey<ApkVersionRecord>> = listOf(LOCATIONS_KEY_1)
    override fun `as`(alias: String): ApkVersion = ApkVersion(DSL.name(alias), this)
    override fun `as`(alias: Name): ApkVersion = ApkVersion(alias, this)
    override fun `as`(alias: Table<*>): ApkVersion = ApkVersion(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): ApkVersion = ApkVersion(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): ApkVersion = ApkVersion(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): ApkVersion = ApkVersion(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row9<UUID?, String?, String?, String?, String?, String?, String?, OffsetDateTime?, OffsetDateTime?> = super.fieldsRow() as Row9<UUID?, String?, String?, String?, String?, String?, String?, OffsetDateTime?, OffsetDateTime?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (UUID?, String?, String?, String?, String?, String?, String?, OffsetDateTime?, OffsetDateTime?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (UUID?, String?, String?, String?, String?, String?, String?, OffsetDateTime?, OffsetDateTime?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
