/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables


import com.kcvn.spm.model.Public
import com.kcvn.spm.model.keys.AUTH_USER_PKEY
import com.kcvn.spm.model.tables.records.AuthUserRecord

import java.time.LocalDate
import java.time.OffsetDateTime
import java.util.function.Function

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row17
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class AuthUser(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, AuthUserRecord>?,
    aliased: Table<AuthUserRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<AuthUserRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.auth_user</code>
         */
        val AUTH_USER: AuthUser = AuthUser()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<AuthUserRecord> = AuthUserRecord::class.java

    /**
     * The column <code>public.auth_user.id</code>.
     */
    val ID: TableField<AuthUserRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR(50).nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>public.auth_user.username</code>.
     */
    val USERNAME: TableField<AuthUserRecord, String?> = createField(DSL.name("username"), SQLDataType.VARCHAR(100).nullable(false), this, "")

    /**
     * The column <code>public.auth_user.password</code>.
     */
    val PASSWORD: TableField<AuthUserRecord, String?> = createField(DSL.name("password"), SQLDataType.VARCHAR(100).nullable(false), this, "")

    /**
     * The column <code>public.auth_user.employee_code</code>.
     */
    val EMPLOYEE_CODE: TableField<AuthUserRecord, String?> = createField(DSL.name("employee_code"), SQLDataType.VARCHAR(20), this, "")

    /**
     * The column <code>public.auth_user.email</code>.
     */
    val EMAIL: TableField<AuthUserRecord, String?> = createField(DSL.name("email"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.auth_user.phone_number</code>.
     */
    val PHONE_NUMBER: TableField<AuthUserRecord, String?> = createField(DSL.name("phone_number"), SQLDataType.VARCHAR(20), this, "")

    /**
     * The column <code>public.auth_user.full_name</code>.
     */
    val FULL_NAME: TableField<AuthUserRecord, String?> = createField(DSL.name("full_name"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.auth_user.full_name_unsigned</code>.
     */
    val FULL_NAME_UNSIGNED: TableField<AuthUserRecord, String?> = createField(DSL.name("full_name_unsigned"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.auth_user.date_of_birth</code>.
     */
    val DATE_OF_BIRTH: TableField<AuthUserRecord, LocalDate?> = createField(DSL.name("date_of_birth"), SQLDataType.LOCALDATE, this, "")

    /**
     * The column <code>public.auth_user.avatar</code>.
     */
    val AVATAR: TableField<AuthUserRecord, String?> = createField(DSL.name("avatar"), SQLDataType.VARCHAR(1000), this, "")

    /**
     * The column <code>public.auth_user.status</code>.
     */
    val STATUS: TableField<AuthUserRecord, Short?> = createField(DSL.name("status"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.SMALLINT)), this, "")

    /**
     * The column <code>public.auth_user.is_super_admin</code>.
     */
    val IS_SUPER_ADMIN: TableField<AuthUserRecord, Boolean?> = createField(DSL.name("is_super_admin"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "")

    /**
     * The column <code>public.auth_user.created_date</code>.
     */
    val CREATED_DATE: TableField<AuthUserRecord, OffsetDateTime?> = createField(DSL.name("created_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.auth_user.created_by</code>.
     */
    val CREATED_BY: TableField<AuthUserRecord, String?> = createField(DSL.name("created_by"), SQLDataType.VARCHAR(100).nullable(false), this, "")

    /**
     * The column <code>public.auth_user.updated_date</code>.
     */
    val UPDATED_DATE: TableField<AuthUserRecord, OffsetDateTime?> = createField(DSL.name("updated_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.auth_user.updated_by</code>.
     */
    val UPDATED_BY: TableField<AuthUserRecord, String?> = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.auth_user.is_deleted</code>.
     */
    val IS_DELETED: TableField<AuthUserRecord, Boolean?> = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "")

    private constructor(alias: Name, aliased: Table<AuthUserRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<AuthUserRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.auth_user</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.auth_user</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.auth_user</code> table reference
     */
    constructor(): this(DSL.name("auth_user"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, AuthUserRecord>): this(Internal.createPathAlias(child, key), child, key, AUTH_USER, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<AuthUserRecord> = AUTH_USER_PKEY
    override fun `as`(alias: String): AuthUser = AuthUser(DSL.name(alias), this)
    override fun `as`(alias: Name): AuthUser = AuthUser(alias, this)
    override fun `as`(alias: Table<*>): AuthUser = AuthUser(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): AuthUser = AuthUser(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): AuthUser = AuthUser(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): AuthUser = AuthUser(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row17 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row17<String?, String?, String?, String?, String?, String?, String?, String?, LocalDate?, String?, Short?, Boolean?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?> = super.fieldsRow() as Row17<String?, String?, String?, String?, String?, String?, String?, String?, LocalDate?, String?, Short?, Boolean?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (String?, String?, String?, String?, String?, String?, String?, String?, LocalDate?, String?, Short?, Boolean?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (String?, String?, String?, String?, String?, String?, String?, String?, LocalDate?, String?, Short?, Boolean?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
