/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables


import com.kcvn.spm.model.Public
import com.kcvn.spm.model.keys.AUTH_PASSWORD_RESET_TOKEN_PKEY
import com.kcvn.spm.model.keys.AUTH_PASSWORD_RESET_TOKEN__AUTH_PASSWORD_RESET_TOKEN_AUTH_USER_ID_FK
import com.kcvn.spm.model.tables.records.AuthPasswordResetTokenRecord

import java.time.OffsetDateTime
import java.util.function.Function

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row9
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class AuthPasswordResetToken(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, AuthPasswordResetTokenRecord>?,
    aliased: Table<AuthPasswordResetTokenRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<AuthPasswordResetTokenRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of
         * <code>public.auth_password_reset_token</code>
         */
        val AUTH_PASSWORD_RESET_TOKEN: AuthPasswordResetToken = AuthPasswordResetToken()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<AuthPasswordResetTokenRecord> = AuthPasswordResetTokenRecord::class.java

    /**
     * The column <code>public.auth_password_reset_token.id</code>.
     */
    val ID: TableField<AuthPasswordResetTokenRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>public.auth_password_reset_token.user_id</code>.
     */
    val USER_ID: TableField<AuthPasswordResetTokenRecord, String?> = createField(DSL.name("user_id"), SQLDataType.VARCHAR.nullable(false), this, "")

    /**
     * The column <code>public.auth_password_reset_token.token</code>.
     */
    val TOKEN: TableField<AuthPasswordResetTokenRecord, String?> = createField(DSL.name("token"), SQLDataType.VARCHAR.nullable(false), this, "")

    /**
     * The column <code>public.auth_password_reset_token.expired_date</code>.
     */
    val EXPIRED_DATE: TableField<AuthPasswordResetTokenRecord, OffsetDateTime?> = createField(DSL.name("expired_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

    /**
     * The column <code>public.auth_password_reset_token.created_date</code>.
     */
    val CREATED_DATE: TableField<AuthPasswordResetTokenRecord, OffsetDateTime?> = createField(DSL.name("created_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.auth_password_reset_token.created_by</code>.
     */
    val CREATED_BY: TableField<AuthPasswordResetTokenRecord, String?> = createField(DSL.name("created_by"), SQLDataType.VARCHAR.nullable(false), this, "")

    /**
     * The column <code>public.auth_password_reset_token.updated_date</code>.
     */
    val UPDATED_DATE: TableField<AuthPasswordResetTokenRecord, OffsetDateTime?> = createField(DSL.name("updated_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.auth_password_reset_token.updated_by</code>.
     */
    val UPDATED_BY: TableField<AuthPasswordResetTokenRecord, String?> = createField(DSL.name("updated_by"), SQLDataType.VARCHAR, this, "")

    /**
     * The column <code>public.auth_password_reset_token.is_deleted</code>.
     */
    val IS_DELETED: TableField<AuthPasswordResetTokenRecord, Boolean?> = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "")

    private constructor(alias: Name, aliased: Table<AuthPasswordResetTokenRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<AuthPasswordResetTokenRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.auth_password_reset_token</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.auth_password_reset_token</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.auth_password_reset_token</code> table reference
     */
    constructor(): this(DSL.name("auth_password_reset_token"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, AuthPasswordResetTokenRecord>): this(Internal.createPathAlias(child, key), child, key, AUTH_PASSWORD_RESET_TOKEN, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<AuthPasswordResetTokenRecord> = AUTH_PASSWORD_RESET_TOKEN_PKEY
    override fun getReferences(): List<ForeignKey<AuthPasswordResetTokenRecord, *>> = listOf(AUTH_PASSWORD_RESET_TOKEN__AUTH_PASSWORD_RESET_TOKEN_AUTH_USER_ID_FK)

    private lateinit var _authUser: AuthUser

    /**
     * Get the implicit join path to the <code>public.auth_user</code> table.
     */
    fun authUser(): AuthUser {
        if (!this::_authUser.isInitialized)
            _authUser = AuthUser(this, AUTH_PASSWORD_RESET_TOKEN__AUTH_PASSWORD_RESET_TOKEN_AUTH_USER_ID_FK)

        return _authUser;
    }

    val authUser: AuthUser
        get(): AuthUser = authUser()
    override fun `as`(alias: String): AuthPasswordResetToken = AuthPasswordResetToken(DSL.name(alias), this)
    override fun `as`(alias: Name): AuthPasswordResetToken = AuthPasswordResetToken(alias, this)
    override fun `as`(alias: Table<*>): AuthPasswordResetToken = AuthPasswordResetToken(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): AuthPasswordResetToken = AuthPasswordResetToken(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): AuthPasswordResetToken = AuthPasswordResetToken(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): AuthPasswordResetToken = AuthPasswordResetToken(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row9<String?, String?, String?, OffsetDateTime?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?> = super.fieldsRow() as Row9<String?, String?, String?, OffsetDateTime?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (String?, String?, String?, OffsetDateTime?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (String?, String?, String?, OffsetDateTime?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
