/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables


import com.kcvn.spm.model.Public
import com.kcvn.spm.model.keys.AUTH_ROLE_CLAIM_PKEY
import com.kcvn.spm.model.keys.AUTH_ROLE_CLAIM__AUTH_ROLE_CLAIM_AUTH_ROLE_ID_FK
import com.kcvn.spm.model.tables.AuthRole.AuthRolePath
import com.kcvn.spm.model.tables.records.AuthRoleClaimRecord

import java.time.OffsetDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class AuthRoleClaim(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, AuthRoleClaimRecord>?,
    parentPath: InverseForeignKey<out Record, AuthRoleClaimRecord>?,
    aliased: Table<AuthRoleClaimRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<AuthRoleClaimRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.auth_role_claim</code>
         */
        val AUTH_ROLE_CLAIM: AuthRoleClaim = AuthRoleClaim()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<AuthRoleClaimRecord> = AuthRoleClaimRecord::class.java

    /**
     * The column <code>public.auth_role_claim.id</code>.
     */
    val ID: TableField<AuthRoleClaimRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR(50).nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>public.auth_role_claim.role_id</code>.
     */
    val ROLE_ID: TableField<AuthRoleClaimRecord, String?> = createField(DSL.name("role_id"), SQLDataType.VARCHAR(50).nullable(false), this, "")

    /**
     * The column <code>public.auth_role_claim.claim_type</code>.
     */
    val CLAIM_TYPE: TableField<AuthRoleClaimRecord, String?> = createField(DSL.name("claim_type"), SQLDataType.VARCHAR(50).nullable(false), this, "")

    /**
     * The column <code>public.auth_role_claim.claim_value</code>.
     */
    val CLAIM_VALUE: TableField<AuthRoleClaimRecord, String?> = createField(DSL.name("claim_value"), SQLDataType.VARCHAR, this, "")

    /**
     * The column <code>public.auth_role_claim.created_date</code>.
     */
    val CREATED_DATE: TableField<AuthRoleClaimRecord, OffsetDateTime?> = createField(DSL.name("created_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.auth_role_claim.created_by</code>.
     */
    val CREATED_BY: TableField<AuthRoleClaimRecord, String?> = createField(DSL.name("created_by"), SQLDataType.VARCHAR(100).nullable(false), this, "")

    /**
     * The column <code>public.auth_role_claim.updated_date</code>.
     */
    val UPDATED_DATE: TableField<AuthRoleClaimRecord, OffsetDateTime?> = createField(DSL.name("updated_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.auth_role_claim.updated_by</code>.
     */
    val UPDATED_BY: TableField<AuthRoleClaimRecord, String?> = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.auth_role_claim.is_deleted</code>.
     */
    val IS_DELETED: TableField<AuthRoleClaimRecord, Boolean?> = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "")

    private constructor(alias: Name, aliased: Table<AuthRoleClaimRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<AuthRoleClaimRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<AuthRoleClaimRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.auth_role_claim</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.auth_role_claim</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.auth_role_claim</code> table reference
     */
    constructor(): this(DSL.name("auth_role_claim"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, AuthRoleClaimRecord>?, parentPath: InverseForeignKey<out Record, AuthRoleClaimRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, AUTH_ROLE_CLAIM, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class AuthRoleClaimPath : AuthRoleClaim, Path<AuthRoleClaimRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, AuthRoleClaimRecord>?, parentPath: InverseForeignKey<out Record, AuthRoleClaimRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<AuthRoleClaimRecord>): super(alias, aliased)
        override fun `as`(alias: String): AuthRoleClaimPath = AuthRoleClaimPath(DSL.name(alias), this)
        override fun `as`(alias: Name): AuthRoleClaimPath = AuthRoleClaimPath(alias, this)
        override fun `as`(alias: Table<*>): AuthRoleClaimPath = AuthRoleClaimPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<AuthRoleClaimRecord> = AUTH_ROLE_CLAIM_PKEY
    override fun getReferences(): List<ForeignKey<AuthRoleClaimRecord, *>> = listOf(AUTH_ROLE_CLAIM__AUTH_ROLE_CLAIM_AUTH_ROLE_ID_FK)

    private lateinit var _authRole: AuthRolePath

    /**
     * Get the implicit join path to the <code>public.auth_role</code> table.
     */
    fun authRole(): AuthRolePath {
        if (!this::_authRole.isInitialized)
            _authRole = AuthRolePath(this, AUTH_ROLE_CLAIM__AUTH_ROLE_CLAIM_AUTH_ROLE_ID_FK, null)

        return _authRole;
    }

    val authRole: AuthRolePath
        get(): AuthRolePath = authRole()
    override fun `as`(alias: String): AuthRoleClaim = AuthRoleClaim(DSL.name(alias), this)
    override fun `as`(alias: Name): AuthRoleClaim = AuthRoleClaim(alias, this)
    override fun `as`(alias: Table<*>): AuthRoleClaim = AuthRoleClaim(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): AuthRoleClaim = AuthRoleClaim(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): AuthRoleClaim = AuthRoleClaim(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): AuthRoleClaim = AuthRoleClaim(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): AuthRoleClaim = AuthRoleClaim(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): AuthRoleClaim = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): AuthRoleClaim = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): AuthRoleClaim = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): AuthRoleClaim = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): AuthRoleClaim = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): AuthRoleClaim = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): AuthRoleClaim = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): AuthRoleClaim = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): AuthRoleClaim = where(DSL.notExists(select))
}
