/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables


import com.kcvn.spm.model.Public
import com.kcvn.spm.model.keys.BACKLOG_WH_HISTORY_PKEY
import com.kcvn.spm.model.tables.records.BacklogWhHistoryRecord

import java.math.BigDecimal
import java.time.LocalDate
import java.time.OffsetDateTime
import java.util.function.Function

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row13
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class BacklogWhHistory(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, BacklogWhHistoryRecord>?,
    aliased: Table<BacklogWhHistoryRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<BacklogWhHistoryRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.backlog_wh_history</code>
         */
        val BACKLOG_WH_HISTORY: BacklogWhHistory = BacklogWhHistory()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<BacklogWhHistoryRecord> = BacklogWhHistoryRecord::class.java

    /**
     * The column <code>public.backlog_wh_history.id</code>.
     */
    val ID: TableField<BacklogWhHistoryRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR(50).nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>public.backlog_wh_history.location_code</code>.
     */
    val LOCATION_CODE: TableField<BacklogWhHistoryRecord, String?> = createField(DSL.name("location_code"), SQLDataType.VARCHAR(6).nullable(false), this, "")

    /**
     * The column <code>public.backlog_wh_history.po_number</code>.
     */
    val PO_NUMBER: TableField<BacklogWhHistoryRecord, String?> = createField(DSL.name("po_number"), SQLDataType.VARCHAR(30).nullable(false), this, "")

    /**
     * The column <code>public.backlog_wh_history.package_code</code>.
     */
    val PACKAGE_CODE: TableField<BacklogWhHistoryRecord, String?> = createField(DSL.name("package_code"), SQLDataType.VARCHAR(30).nullable(false), this, "")

    /**
     * The column <code>public.backlog_wh_history.backlog_qty</code>.
     */
    val BACKLOG_QTY: TableField<BacklogWhHistoryRecord, BigDecimal?> = createField(DSL.name("backlog_qty"), SQLDataType.NUMERIC, this, "")

    /**
     * The column <code>public.backlog_wh_history.box_qty</code>.
     */
    val BOX_QTY: TableField<BacklogWhHistoryRecord, Int?> = createField(DSL.name("box_qty"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "")

    /**
     * The column <code>public.backlog_wh_history.receiving_date</code>.
     */
    val RECEIVING_DATE: TableField<BacklogWhHistoryRecord, LocalDate?> = createField(DSL.name("receiving_date"), SQLDataType.LOCALDATE.nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_DATE"), SQLDataType.LOCALDATE)), this, "")

    /**
     * The column <code>public.backlog_wh_history.issue_date</code>.
     */
    val ISSUE_DATE: TableField<BacklogWhHistoryRecord, LocalDate?> = createField(DSL.name("issue_date"), SQLDataType.LOCALDATE, this, "")

    /**
     * The column <code>public.backlog_wh_history.transaction_type</code>.
     */
    val TRANSACTION_TYPE: TableField<BacklogWhHistoryRecord, String?> = createField(DSL.name("transaction_type"), SQLDataType.VARCHAR(20).nullable(false), this, "")

    /**
     * The column <code>public.backlog_wh_history.created_date</code>.
     */
    val CREATED_DATE: TableField<BacklogWhHistoryRecord, OffsetDateTime?> = createField(DSL.name("created_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.backlog_wh_history.created_by</code>.
     */
    val CREATED_BY: TableField<BacklogWhHistoryRecord, String?> = createField(DSL.name("created_by"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.backlog_wh_history.updated_date</code>.
     */
    val UPDATED_DATE: TableField<BacklogWhHistoryRecord, OffsetDateTime?> = createField(DSL.name("updated_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.backlog_wh_history.updated_by</code>.
     */
    val UPDATED_BY: TableField<BacklogWhHistoryRecord, String?> = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(100), this, "")

    private constructor(alias: Name, aliased: Table<BacklogWhHistoryRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<BacklogWhHistoryRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.backlog_wh_history</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.backlog_wh_history</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.backlog_wh_history</code> table reference
     */
    constructor(): this(DSL.name("backlog_wh_history"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, BacklogWhHistoryRecord>): this(Internal.createPathAlias(child, key), child, key, BACKLOG_WH_HISTORY, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<BacklogWhHistoryRecord> = BACKLOG_WH_HISTORY_PKEY
    override fun `as`(alias: String): BacklogWhHistory = BacklogWhHistory(DSL.name(alias), this)
    override fun `as`(alias: Name): BacklogWhHistory = BacklogWhHistory(alias, this)
    override fun `as`(alias: Table<*>): BacklogWhHistory = BacklogWhHistory(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): BacklogWhHistory = BacklogWhHistory(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): BacklogWhHistory = BacklogWhHistory(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): BacklogWhHistory = BacklogWhHistory(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row13 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row13<String?, String?, String?, String?, BigDecimal?, Int?, LocalDate?, LocalDate?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?> = super.fieldsRow() as Row13<String?, String?, String?, String?, BigDecimal?, Int?, LocalDate?, LocalDate?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (String?, String?, String?, String?, BigDecimal?, Int?, LocalDate?, LocalDate?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (String?, String?, String?, String?, BigDecimal?, Int?, LocalDate?, LocalDate?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
