/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables


import com.kcvn.spm.model.Public
import com.kcvn.spm.model.keys.CHECKING_PKEY
import com.kcvn.spm.model.tables.records.CheckingRecord

import java.math.BigDecimal
import java.time.OffsetDateTime

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Checking(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CheckingRecord>?,
    parentPath: InverseForeignKey<out Record, CheckingRecord>?,
    aliased: Table<CheckingRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<CheckingRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.checking</code>
         */
        val CHECKING: Checking = Checking()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CheckingRecord> = CheckingRecord::class.java

    /**
     * The column <code>public.checking.id</code>.
     */
    val ID: TableField<CheckingRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR(50).nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>public.checking.po_number</code>.
     */
    val PO_NUMBER: TableField<CheckingRecord, String?> = createField(DSL.name("po_number"), SQLDataType.VARCHAR(30).nullable(false), this, "")

    /**
     * The column <code>public.checking.package_code</code>.
     */
    val PACKAGE_CODE: TableField<CheckingRecord, String?> = createField(DSL.name("package_code"), SQLDataType.VARCHAR(30).nullable(false), this, "")

    /**
     * The column <code>public.checking.qty</code>.
     */
    val QTY: TableField<CheckingRecord, BigDecimal?> = createField(DSL.name("qty"), SQLDataType.NUMERIC, this, "")

    /**
     * The column <code>public.checking.seq_no</code>.
     */
    val SEQ_NO: TableField<CheckingRecord, Int?> = createField(DSL.name("seq_no"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "")

    /**
     * The column <code>public.checking.created_date</code>.
     */
    val CREATED_DATE: TableField<CheckingRecord, OffsetDateTime?> = createField(DSL.name("created_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.checking.created_by</code>.
     */
    val CREATED_BY: TableField<CheckingRecord, String?> = createField(DSL.name("created_by"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.checking.updated_date</code>.
     */
    val UPDATED_DATE: TableField<CheckingRecord, OffsetDateTime?> = createField(DSL.name("updated_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.checking.updated_by</code>.
     */
    val UPDATED_BY: TableField<CheckingRecord, String?> = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.checking.lot_no</code>.
     */
    val LOT_NO: TableField<CheckingRecord, String?> = createField(DSL.name("lot_no"), SQLDataType.VARCHAR(10000), this, "")

    /**
     * The column <code>public.checking.issue_date</code>.
     */
    val ISSUE_DATE: TableField<CheckingRecord, String?> = createField(DSL.name("issue_date"), SQLDataType.VARCHAR(200), this, "")

    private constructor(alias: Name, aliased: Table<CheckingRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<CheckingRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<CheckingRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.checking</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.checking</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.checking</code> table reference
     */
    constructor(): this(DSL.name("checking"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<CheckingRecord> = CHECKING_PKEY
    override fun `as`(alias: String): Checking = Checking(DSL.name(alias), this)
    override fun `as`(alias: Name): Checking = Checking(alias, this)
    override fun `as`(alias: Table<*>): Checking = Checking(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Checking = Checking(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Checking = Checking(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Checking = Checking(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Checking = Checking(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Checking = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Checking = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Checking = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Checking = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Checking = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Checking = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Checking = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Checking = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Checking = where(DSL.notExists(select))
}
