/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables


import com.kcvn.spm.model.Public
import com.kcvn.spm.model.keys.PLAN_PRODUCT_PKEY
import com.kcvn.spm.model.keys.PLAN_PRODUCT__PLAN_PRODUCT_FKEY
import com.kcvn.spm.model.tables.records.PlanProductRecord

import java.time.OffsetDateTime
import java.util.function.Function

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row12
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PlanProduct(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, PlanProductRecord>?,
    aliased: Table<PlanProductRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<PlanProductRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.plan_product</code>
         */
        val PLAN_PRODUCT: PlanProduct = PlanProduct()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<PlanProductRecord> = PlanProductRecord::class.java

    /**
     * The column <code>public.plan_product.id</code>.
     */
    val ID: TableField<PlanProductRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR(50).nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>public.plan_product.plan_id</code>.
     */
    val PLAN_ID: TableField<PlanProductRecord, String?> = createField(DSL.name("plan_id"), SQLDataType.VARCHAR(50).nullable(false), this, "")

    /**
     * The column <code>public.plan_product.product_name</code>.
     */
    val PRODUCT_NAME: TableField<PlanProductRecord, String?> = createField(DSL.name("product_name"), SQLDataType.VARCHAR(30).nullable(false), this, "")

    /**
     * The column <code>public.plan_product.frame_1</code>.
     */
    val FRAME_1: TableField<PlanProductRecord, String?> = createField(DSL.name("frame_1"), SQLDataType.VARCHAR(10).nullable(false), this, "")

    /**
     * The column <code>public.plan_product.mold</code>.
     */
    val MOLD: TableField<PlanProductRecord, String?> = createField(DSL.name("mold"), SQLDataType.VARCHAR(10).nullable(false), this, "")

    /**
     * The column <code>public.plan_product.pcs_sh</code>.
     */
    val PCS_SH: TableField<PlanProductRecord, Int?> = createField(DSL.name("pcs_sh"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "")

    /**
     * The column <code>public.plan_product.block_sh</code>.
     */
    val BLOCK_SH: TableField<PlanProductRecord, Int?> = createField(DSL.name("block_sh"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "")

    /**
     * The column <code>public.plan_product.created_date</code>.
     */
    val CREATED_DATE: TableField<PlanProductRecord, OffsetDateTime?> = createField(DSL.name("created_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.plan_product.created_by</code>.
     */
    val CREATED_BY: TableField<PlanProductRecord, String?> = createField(DSL.name("created_by"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.plan_product.updated_date</code>.
     */
    val UPDATED_DATE: TableField<PlanProductRecord, OffsetDateTime?> = createField(DSL.name("updated_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.plan_product.updated_by</code>.
     */
    val UPDATED_BY: TableField<PlanProductRecord, String?> = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.plan_product.is_deleted</code>.
     */
    val IS_DELETED: TableField<PlanProductRecord, Boolean?> = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "")

    private constructor(alias: Name, aliased: Table<PlanProductRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<PlanProductRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.plan_product</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.plan_product</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.plan_product</code> table reference
     */
    constructor(): this(DSL.name("plan_product"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, PlanProductRecord>): this(Internal.createPathAlias(child, key), child, key, PLAN_PRODUCT, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<PlanProductRecord> = PLAN_PRODUCT_PKEY
    override fun getReferences(): List<ForeignKey<PlanProductRecord, *>> = listOf(PLAN_PRODUCT__PLAN_PRODUCT_FKEY)

    private lateinit var _plan: Plan

    /**
     * Get the implicit join path to the <code>public.plan</code> table.
     */
    fun plan(): Plan {
        if (!this::_plan.isInitialized)
            _plan = Plan(this, PLAN_PRODUCT__PLAN_PRODUCT_FKEY)

        return _plan;
    }

    val plan: Plan
        get(): Plan = plan()
    override fun `as`(alias: String): PlanProduct = PlanProduct(DSL.name(alias), this)
    override fun `as`(alias: Name): PlanProduct = PlanProduct(alias, this)
    override fun `as`(alias: Table<*>): PlanProduct = PlanProduct(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): PlanProduct = PlanProduct(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): PlanProduct = PlanProduct(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): PlanProduct = PlanProduct(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row12 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row12<String?, String?, String?, String?, String?, Int?, Int?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?> = super.fieldsRow() as Row12<String?, String?, String?, String?, String?, Int?, Int?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (String?, String?, String?, String?, String?, Int?, Int?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (String?, String?, String?, String?, String?, Int?, Int?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
