/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables


import com.kcvn.spm.model.Public
import com.kcvn.spm.model.keys.PLAN_CALENDAR_CONFIG_PKEY
import com.kcvn.spm.model.tables.records.PlanCalendarConfigRecord

import java.time.OffsetDateTime
import java.util.function.Function

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row10
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PlanCalendarConfig(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, PlanCalendarConfigRecord>?,
    aliased: Table<PlanCalendarConfigRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<PlanCalendarConfigRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.plan_calendar_config</code>
         */
        val PLAN_CALENDAR_CONFIG: PlanCalendarConfig = PlanCalendarConfig()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<PlanCalendarConfigRecord> = PlanCalendarConfigRecord::class.java

    /**
     * The column <code>public.plan_calendar_config.id</code>.
     */
    val ID: TableField<PlanCalendarConfigRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR(50).nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>public.plan_calendar_config.month</code>.
     */
    val MONTH: TableField<PlanCalendarConfigRecord, Int?> = createField(DSL.name("month"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.plan_calendar_config.year</code>.
     */
    val YEAR: TableField<PlanCalendarConfigRecord, Int?> = createField(DSL.name("year"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.plan_calendar_config.start_date</code>.
     */
    val START_DATE: TableField<PlanCalendarConfigRecord, OffsetDateTime?> = createField(DSL.name("start_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

    /**
     * The column <code>public.plan_calendar_config.end_date</code>.
     */
    val END_DATE: TableField<PlanCalendarConfigRecord, OffsetDateTime?> = createField(DSL.name("end_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

    /**
     * The column <code>public.plan_calendar_config.created_date</code>.
     */
    val CREATED_DATE: TableField<PlanCalendarConfigRecord, OffsetDateTime?> = createField(DSL.name("created_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.plan_calendar_config.created_by</code>.
     */
    val CREATED_BY: TableField<PlanCalendarConfigRecord, String?> = createField(DSL.name("created_by"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.plan_calendar_config.updated_date</code>.
     */
    val UPDATED_DATE: TableField<PlanCalendarConfigRecord, OffsetDateTime?> = createField(DSL.name("updated_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.plan_calendar_config.updated_by</code>.
     */
    val UPDATED_BY: TableField<PlanCalendarConfigRecord, String?> = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.plan_calendar_config.is_deleted</code>.
     */
    val IS_DELETED: TableField<PlanCalendarConfigRecord, Boolean?> = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "")

    private constructor(alias: Name, aliased: Table<PlanCalendarConfigRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<PlanCalendarConfigRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.plan_calendar_config</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.plan_calendar_config</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.plan_calendar_config</code> table reference
     */
    constructor(): this(DSL.name("plan_calendar_config"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, PlanCalendarConfigRecord>): this(Internal.createPathAlias(child, key), child, key, PLAN_CALENDAR_CONFIG, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<PlanCalendarConfigRecord> = PLAN_CALENDAR_CONFIG_PKEY
    override fun `as`(alias: String): PlanCalendarConfig = PlanCalendarConfig(DSL.name(alias), this)
    override fun `as`(alias: Name): PlanCalendarConfig = PlanCalendarConfig(alias, this)
    override fun `as`(alias: Table<*>): PlanCalendarConfig = PlanCalendarConfig(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): PlanCalendarConfig = PlanCalendarConfig(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): PlanCalendarConfig = PlanCalendarConfig(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): PlanCalendarConfig = PlanCalendarConfig(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row10<String?, Int?, Int?, OffsetDateTime?, OffsetDateTime?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?> = super.fieldsRow() as Row10<String?, Int?, Int?, OffsetDateTime?, OffsetDateTime?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (String?, Int?, Int?, OffsetDateTime?, OffsetDateTime?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (String?, Int?, Int?, OffsetDateTime?, OffsetDateTime?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
