/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables


import com.kcvn.spm.model.Public
import com.kcvn.spm.model.keys.PLAN_PROCESS_TEMP_PKEY
import com.kcvn.spm.model.keys.PLAN_PROCESS_TEMP__PLAN_PROCESS_TEMP_FKEY
import com.kcvn.spm.model.tables.records.PlanProcessTempRecord

import java.math.BigDecimal
import java.time.OffsetDateTime
import java.util.function.Function

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row20
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PlanProcessTemp(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, PlanProcessTempRecord>?,
    aliased: Table<PlanProcessTempRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<PlanProcessTempRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.plan_process_temp</code>
         */
        val PLAN_PROCESS_TEMP: PlanProcessTemp = PlanProcessTemp()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<PlanProcessTempRecord> = PlanProcessTempRecord::class.java

    /**
     * The column <code>public.plan_process_temp.id</code>.
     */
    val ID: TableField<PlanProcessTempRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR(50).nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>public.plan_process_temp.plan_id</code>.
     */
    val PLAN_ID: TableField<PlanProcessTempRecord, String?> = createField(DSL.name("plan_id"), SQLDataType.VARCHAR(50).nullable(false), this, "")

    /**
     * The column <code>public.plan_process_temp.plan_product_id</code>.
     */
    val PLAN_PRODUCT_ID: TableField<PlanProcessTempRecord, String?> = createField(DSL.name("plan_product_id"), SQLDataType.VARCHAR(50).nullable(false), this, "")

    /**
     * The column <code>public.plan_process_temp.process_code</code>.
     */
    val PROCESS_CODE: TableField<PlanProcessTempRecord, String?> = createField(DSL.name("process_code"), SQLDataType.VARCHAR(6).nullable(false), this, "")

    /**
     * The column <code>public.plan_process_temp.process_name</code>.
     */
    val PROCESS_NAME: TableField<PlanProcessTempRecord, String?> = createField(DSL.name("process_name"), SQLDataType.VARCHAR(60), this, "")

    /**
     * The column <code>public.plan_process_temp.process_convert_code</code>.
     */
    val PROCESS_CONVERT_CODE: TableField<PlanProcessTempRecord, String?> = createField(DSL.name("process_convert_code"), SQLDataType.VARCHAR(10), this, "")

    /**
     * The column <code>public.plan_process_temp.layer_code</code>.
     */
    val LAYER_CODE: TableField<PlanProcessTempRecord, String?> = createField(DSL.name("layer_code"), SQLDataType.VARCHAR(2), this, "")

    /**
     * The column <code>public.plan_process_temp.completion_rate</code>.
     */
    val COMPLETION_RATE: TableField<PlanProcessTempRecord, BigDecimal?> = createField(DSL.name("completion_rate"), SQLDataType.NUMERIC(5, 2), this, "")

    /**
     * The column <code>public.plan_process_temp.inventory</code>.
     */
    val INVENTORY: TableField<PlanProcessTempRecord, Int?> = createField(DSL.name("inventory"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.plan_process_temp.parent_id</code>.
     */
    val PARENT_ID: TableField<PlanProcessTempRecord, String?> = createField(DSL.name("parent_id"), SQLDataType.VARCHAR(50), this, "")

    /**
     * The column <code>public.plan_process_temp.unit</code>.
     */
    val UNIT: TableField<PlanProcessTempRecord, String?> = createField(DSL.name("unit"), SQLDataType.VARCHAR(20), this, "")

    /**
     * The column <code>public.plan_process_temp.process_sequence</code>.
     */
    val PROCESS_SEQUENCE: TableField<PlanProcessTempRecord, Int?> = createField(DSL.name("process_sequence"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.plan_process_temp.process_name_jp</code>.
     */
    val PROCESS_NAME_JP: TableField<PlanProcessTempRecord, String?> = createField(DSL.name("process_name_jp"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.plan_process_temp.process_group</code>.
     */
    val PROCESS_GROUP: TableField<PlanProcessTempRecord, String?> = createField(DSL.name("process_group"), SQLDataType.VARCHAR(5), this, "")

    /**
     * The column <code>public.plan_process_temp.process_statistic_code</code>.
     */
    val PROCESS_STATISTIC_CODE: TableField<PlanProcessTempRecord, String?> = createField(DSL.name("process_statistic_code"), SQLDataType.VARCHAR(10), this, "")

    /**
     * The column <code>public.plan_process_temp.created_date</code>.
     */
    val CREATED_DATE: TableField<PlanProcessTempRecord, OffsetDateTime?> = createField(DSL.name("created_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.plan_process_temp.created_by</code>.
     */
    val CREATED_BY: TableField<PlanProcessTempRecord, String?> = createField(DSL.name("created_by"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.plan_process_temp.updated_date</code>.
     */
    val UPDATED_DATE: TableField<PlanProcessTempRecord, OffsetDateTime?> = createField(DSL.name("updated_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.plan_process_temp.updated_by</code>.
     */
    val UPDATED_BY: TableField<PlanProcessTempRecord, String?> = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.plan_process_temp.is_deleted</code>.
     */
    val IS_DELETED: TableField<PlanProcessTempRecord, Boolean?> = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "")

    private constructor(alias: Name, aliased: Table<PlanProcessTempRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<PlanProcessTempRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.plan_process_temp</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.plan_process_temp</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.plan_process_temp</code> table reference
     */
    constructor(): this(DSL.name("plan_process_temp"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, PlanProcessTempRecord>): this(Internal.createPathAlias(child, key), child, key, PLAN_PROCESS_TEMP, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<PlanProcessTempRecord> = PLAN_PROCESS_TEMP_PKEY
    override fun getReferences(): List<ForeignKey<PlanProcessTempRecord, *>> = listOf(PLAN_PROCESS_TEMP__PLAN_PROCESS_TEMP_FKEY)

    private lateinit var _planProductTemp: PlanProductTemp

    /**
     * Get the implicit join path to the <code>public.plan_product_temp</code>
     * table.
     */
    fun planProductTemp(): PlanProductTemp {
        if (!this::_planProductTemp.isInitialized)
            _planProductTemp = PlanProductTemp(this, PLAN_PROCESS_TEMP__PLAN_PROCESS_TEMP_FKEY)

        return _planProductTemp;
    }

    val planProductTemp: PlanProductTemp
        get(): PlanProductTemp = planProductTemp()
    override fun `as`(alias: String): PlanProcessTemp = PlanProcessTemp(DSL.name(alias), this)
    override fun `as`(alias: Name): PlanProcessTemp = PlanProcessTemp(alias, this)
    override fun `as`(alias: Table<*>): PlanProcessTemp = PlanProcessTemp(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): PlanProcessTemp = PlanProcessTemp(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): PlanProcessTemp = PlanProcessTemp(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): PlanProcessTemp = PlanProcessTemp(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row20 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row20<String?, String?, String?, String?, String?, String?, String?, BigDecimal?, Int?, String?, String?, Int?, String?, String?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?> = super.fieldsRow() as Row20<String?, String?, String?, String?, String?, String?, String?, BigDecimal?, Int?, String?, String?, Int?, String?, String?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (String?, String?, String?, String?, String?, String?, String?, BigDecimal?, Int?, String?, String?, Int?, String?, String?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (String?, String?, String?, String?, String?, String?, String?, BigDecimal?, Int?, String?, String?, Int?, String?, String?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
