/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables


import com.kcvn.spm.model.Public
import com.kcvn.spm.model.tables.records.SendingPickingListRecord

import java.math.BigDecimal
import java.time.LocalDate
import java.time.OffsetDateTime

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SendingPickingList(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, SendingPickingListRecord>?,
    parentPath: InverseForeignKey<out Record, SendingPickingListRecord>?,
    aliased: Table<SendingPickingListRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<SendingPickingListRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.sending_picking_list</code>
         */
        val SENDING_PICKING_LIST: SendingPickingList = SendingPickingList()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<SendingPickingListRecord> = SendingPickingListRecord::class.java

    /**
     * The column <code>public.sending_picking_list.id</code>.
     */
    val ID: TableField<SendingPickingListRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR(50).nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>public.sending_picking_list.sending_request_id</code>.
     */
    val SENDING_REQUEST_ID: TableField<SendingPickingListRecord, String?> = createField(DSL.name("sending_request_id"), SQLDataType.VARCHAR(50).nullable(false), this, "")

    /**
     * The column <code>public.sending_picking_list.receiving_date</code>.
     */
    val RECEIVING_DATE: TableField<SendingPickingListRecord, LocalDate?> = createField(DSL.name("receiving_date"), SQLDataType.LOCALDATE.nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_DATE"), SQLDataType.LOCALDATE)), this, "")

    /**
     * The column <code>public.sending_picking_list.form_code</code>.
     */
    val FORM_CODE: TableField<SendingPickingListRecord, String?> = createField(DSL.name("form_code"), SQLDataType.VARCHAR(30).nullable(false), this, "")

    /**
     * The column <code>public.sending_picking_list.po_number</code>.
     */
    val PO_NUMBER: TableField<SendingPickingListRecord, String?> = createField(DSL.name("po_number"), SQLDataType.VARCHAR(30).nullable(false), this, "")

    /**
     * The column <code>public.sending_picking_list.package_code</code>.
     */
    val PACKAGE_CODE: TableField<SendingPickingListRecord, String?> = createField(DSL.name("package_code"), SQLDataType.VARCHAR(30).nullable(false), this, "")

    /**
     * The column <code>public.sending_picking_list.request_qty</code>.
     */
    val REQUEST_QTY: TableField<SendingPickingListRecord, BigDecimal?> = createField(DSL.name("request_qty"), SQLDataType.NUMERIC, this, "")

    /**
     * The column <code>public.sending_picking_list.item_code</code>.
     */
    val ITEM_CODE: TableField<SendingPickingListRecord, String?> = createField(DSL.name("item_code"), SQLDataType.VARCHAR(30).nullable(false), this, "")

    /**
     * The column <code>public.sending_picking_list.item_name</code>.
     */
    val ITEM_NAME: TableField<SendingPickingListRecord, String?> = createField(DSL.name("item_name"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.sending_picking_list.production_group</code>.
     */
    val PRODUCTION_GROUP: TableField<SendingPickingListRecord, String?> = createField(DSL.name("production_group"), SQLDataType.VARCHAR(30).nullable(false), this, "")

    /**
     * The column <code>public.sending_picking_list.lot_no</code>.
     */
    val LOT_NO: TableField<SendingPickingListRecord, String?> = createField(DSL.name("lot_no"), SQLDataType.VARCHAR(10000), this, "")

    /**
     * The column <code>public.sending_picking_list.issue_date</code>.
     */
    val ISSUE_DATE: TableField<SendingPickingListRecord, String?> = createField(DSL.name("issue_date"), SQLDataType.VARCHAR(1000), this, "")

    /**
     * The column <code>public.sending_picking_list.is_deleted</code>.
     */
    val IS_DELETED: TableField<SendingPickingListRecord, Boolean?> = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN, this, "")

    /**
     * The column <code>public.sending_picking_list.created_date</code>.
     */
    val CREATED_DATE: TableField<SendingPickingListRecord, OffsetDateTime?> = createField(DSL.name("created_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.sending_picking_list.created_by</code>.
     */
    val CREATED_BY: TableField<SendingPickingListRecord, String?> = createField(DSL.name("created_by"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.sending_picking_list.updated_date</code>.
     */
    val UPDATED_DATE: TableField<SendingPickingListRecord, OffsetDateTime?> = createField(DSL.name("updated_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.sending_picking_list.updated_by</code>.
     */
    val UPDATED_BY: TableField<SendingPickingListRecord, String?> = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(100), this, "")

    private constructor(alias: Name, aliased: Table<SendingPickingListRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<SendingPickingListRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<SendingPickingListRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.sending_picking_list</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.sending_picking_list</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.sending_picking_list</code> table reference
     */
    constructor(): this(DSL.name("sending_picking_list"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun `as`(alias: String): SendingPickingList = SendingPickingList(DSL.name(alias), this)
    override fun `as`(alias: Name): SendingPickingList = SendingPickingList(alias, this)
    override fun `as`(alias: Table<*>): SendingPickingList = SendingPickingList(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): SendingPickingList = SendingPickingList(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): SendingPickingList = SendingPickingList(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): SendingPickingList = SendingPickingList(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): SendingPickingList = SendingPickingList(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): SendingPickingList = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): SendingPickingList = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): SendingPickingList = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): SendingPickingList = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): SendingPickingList = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): SendingPickingList = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): SendingPickingList = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): SendingPickingList = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): SendingPickingList = where(DSL.notExists(select))
}
