/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables


import com.kcvn.spm.model.Public
import com.kcvn.spm.model.keys.STOCK_TAKING_PKEY_1_1
import com.kcvn.spm.model.tables.records.StockTakingCheckingRecord

import java.math.BigDecimal
import java.time.OffsetDateTime

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class StockTakingChecking(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, StockTakingCheckingRecord>?,
    parentPath: InverseForeignKey<out Record, StockTakingCheckingRecord>?,
    aliased: Table<StockTakingCheckingRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<StockTakingCheckingRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.stock_taking_checking</code>
         */
        val STOCK_TAKING_CHECKING: StockTakingChecking = StockTakingChecking()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<StockTakingCheckingRecord> = StockTakingCheckingRecord::class.java

    /**
     * The column <code>public.stock_taking_checking.id</code>.
     */
    val ID: TableField<StockTakingCheckingRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR(50).nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>public.stock_taking_checking.year_number</code>.
     */
    val YEAR_NUMBER: TableField<StockTakingCheckingRecord, Int?> = createField(DSL.name("year_number"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.stock_taking_checking.month_number</code>.
     */
    val MONTH_NUMBER: TableField<StockTakingCheckingRecord, Int?> = createField(DSL.name("month_number"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.stock_taking_checking.po_number</code>.
     */
    val PO_NUMBER: TableField<StockTakingCheckingRecord, String?> = createField(DSL.name("po_number"), SQLDataType.VARCHAR(30).nullable(false), this, "")

    /**
     * The column <code>public.stock_taking_checking.package_code</code>.
     */
    val PACKAGE_CODE: TableField<StockTakingCheckingRecord, String?> = createField(DSL.name("package_code"), SQLDataType.VARCHAR(30).nullable(false), this, "")

    /**
     * The column
     * <code>public.stock_taking_checking.system_location_code</code>.
     */
    val SYSTEM_LOCATION_CODE: TableField<StockTakingCheckingRecord, String?> = createField(DSL.name("system_location_code"), SQLDataType.VARCHAR(6), this, "")

    /**
     * The column
     * <code>public.stock_taking_checking.actual_location_code</code>.
     */
    val ACTUAL_LOCATION_CODE: TableField<StockTakingCheckingRecord, String?> = createField(DSL.name("actual_location_code"), SQLDataType.VARCHAR(6), this, "")

    /**
     * The column <code>public.stock_taking_checking.system_qty</code>.
     */
    val SYSTEM_QTY: TableField<StockTakingCheckingRecord, BigDecimal?> = createField(DSL.name("system_qty"), SQLDataType.NUMERIC, this, "")

    /**
     * The column <code>public.stock_taking_checking.actual_qty</code>.
     */
    val ACTUAL_QTY: TableField<StockTakingCheckingRecord, BigDecimal?> = createField(DSL.name("actual_qty"), SQLDataType.NUMERIC, this, "")

    /**
     * The column <code>public.stock_taking_checking.system_box_qty</code>.
     */
    val SYSTEM_BOX_QTY: TableField<StockTakingCheckingRecord, Int?> = createField(DSL.name("system_box_qty"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.stock_taking_checking.actual_box_qty</code>.
     */
    val ACTUAL_BOX_QTY: TableField<StockTakingCheckingRecord, Int?> = createField(DSL.name("actual_box_qty"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.stock_taking_checking.created_date</code>.
     */
    val CREATED_DATE: TableField<StockTakingCheckingRecord, OffsetDateTime?> = createField(DSL.name("created_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.stock_taking_checking.created_by</code>.
     */
    val CREATED_BY: TableField<StockTakingCheckingRecord, String?> = createField(DSL.name("created_by"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.stock_taking_checking.updated_date</code>.
     */
    val UPDATED_DATE: TableField<StockTakingCheckingRecord, OffsetDateTime?> = createField(DSL.name("updated_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.stock_taking_checking.updated_by</code>.
     */
    val UPDATED_BY: TableField<StockTakingCheckingRecord, String?> = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(100), this, "")

    private constructor(alias: Name, aliased: Table<StockTakingCheckingRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<StockTakingCheckingRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<StockTakingCheckingRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.stock_taking_checking</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.stock_taking_checking</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.stock_taking_checking</code> table reference
     */
    constructor(): this(DSL.name("stock_taking_checking"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<StockTakingCheckingRecord> = STOCK_TAKING_PKEY_1_1
    override fun `as`(alias: String): StockTakingChecking = StockTakingChecking(DSL.name(alias), this)
    override fun `as`(alias: Name): StockTakingChecking = StockTakingChecking(alias, this)
    override fun `as`(alias: Table<*>): StockTakingChecking = StockTakingChecking(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): StockTakingChecking = StockTakingChecking(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): StockTakingChecking = StockTakingChecking(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): StockTakingChecking = StockTakingChecking(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): StockTakingChecking = StockTakingChecking(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): StockTakingChecking = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): StockTakingChecking = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): StockTakingChecking = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): StockTakingChecking = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): StockTakingChecking = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): StockTakingChecking = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): StockTakingChecking = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): StockTakingChecking = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): StockTakingChecking = where(DSL.notExists(select))
}
