/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables


import com.kcvn.spm.model.Public
import com.kcvn.spm.model.keys.SYNC_HISTORY_PKEY
import com.kcvn.spm.model.tables.records.SyncHistoryRecord

import java.time.OffsetDateTime
import java.util.function.Function

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row9
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SyncHistory(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, SyncHistoryRecord>?,
    aliased: Table<SyncHistoryRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<SyncHistoryRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.sync_history</code>
         */
        val SYNC_HISTORY: SyncHistory = SyncHistory()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<SyncHistoryRecord> = SyncHistoryRecord::class.java

    /**
     * The column <code>public.sync_history.id</code>.
     */
    val ID: TableField<SyncHistoryRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR(50).nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>public.sync_history.source</code>.
     */
    val SOURCE: TableField<SyncHistoryRecord, String?> = createField(DSL.name("source"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.sync_history.destination</code>.
     */
    val DESTINATION: TableField<SyncHistoryRecord, String?> = createField(DSL.name("destination"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.sync_history.type</code>.
     */
    val TYPE: TableField<SyncHistoryRecord, String?> = createField(DSL.name("type"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.sync_history.created_date</code>.
     */
    val CREATED_DATE: TableField<SyncHistoryRecord, OffsetDateTime?> = createField(DSL.name("created_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.sync_history.created_by</code>.
     */
    val CREATED_BY: TableField<SyncHistoryRecord, String?> = createField(DSL.name("created_by"), SQLDataType.VARCHAR(100).nullable(false), this, "")

    /**
     * The column <code>public.sync_history.updated_date</code>.
     */
    val UPDATED_DATE: TableField<SyncHistoryRecord, OffsetDateTime?> = createField(DSL.name("updated_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.sync_history.updated_by</code>.
     */
    val UPDATED_BY: TableField<SyncHistoryRecord, String?> = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.sync_history.is_deleted</code>.
     */
    val IS_DELETED: TableField<SyncHistoryRecord, Boolean?> = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "")

    private constructor(alias: Name, aliased: Table<SyncHistoryRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<SyncHistoryRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.sync_history</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.sync_history</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.sync_history</code> table reference
     */
    constructor(): this(DSL.name("sync_history"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, SyncHistoryRecord>): this(Internal.createPathAlias(child, key), child, key, SYNC_HISTORY, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<SyncHistoryRecord> = SYNC_HISTORY_PKEY
    override fun `as`(alias: String): SyncHistory = SyncHistory(DSL.name(alias), this)
    override fun `as`(alias: Name): SyncHistory = SyncHistory(alias, this)
    override fun `as`(alias: Table<*>): SyncHistory = SyncHistory(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): SyncHistory = SyncHistory(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): SyncHistory = SyncHistory(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): SyncHistory = SyncHistory(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row9<String?, String?, String?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?> = super.fieldsRow() as Row9<String?, String?, String?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (String?, String?, String?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (String?, String?, String?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
