/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables


import com.kcvn.spm.model.Public
import com.kcvn.spm.model.keys.SYSTEM_LOCK_PKEY
import com.kcvn.spm.model.tables.records.SystemLockRecord

import java.time.OffsetDateTime
import java.util.function.Function

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row8
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SystemLock(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, SystemLockRecord>?,
    aliased: Table<SystemLockRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<SystemLockRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.system_lock</code>
         */
        val SYSTEM_LOCK: SystemLock = SystemLock()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<SystemLockRecord> = SystemLockRecord::class.java

    /**
     * The column <code>public.system_lock.id</code>.
     */
    val ID: TableField<SystemLockRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR(50).nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>public.system_lock.type</code>.
     */
    val TYPE: TableField<SystemLockRecord, String?> = createField(DSL.name("type"), SQLDataType.VARCHAR(50).nullable(false), this, "")

    /**
     * The column <code>public.system_lock.is_lock</code>.
     */
    val IS_LOCK: TableField<SystemLockRecord, Boolean?> = createField(DSL.name("is_lock"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "")

    /**
     * The column <code>public.system_lock.created_date</code>.
     */
    val CREATED_DATE: TableField<SystemLockRecord, OffsetDateTime?> = createField(DSL.name("created_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.system_lock.created_by</code>.
     */
    val CREATED_BY: TableField<SystemLockRecord, String?> = createField(DSL.name("created_by"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.system_lock.updated_date</code>.
     */
    val UPDATED_DATE: TableField<SystemLockRecord, OffsetDateTime?> = createField(DSL.name("updated_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.system_lock.updated_by</code>.
     */
    val UPDATED_BY: TableField<SystemLockRecord, String?> = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.system_lock.is_deleted</code>.
     */
    val IS_DELETED: TableField<SystemLockRecord, Boolean?> = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "")

    private constructor(alias: Name, aliased: Table<SystemLockRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<SystemLockRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.system_lock</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.system_lock</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.system_lock</code> table reference
     */
    constructor(): this(DSL.name("system_lock"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, SystemLockRecord>): this(Internal.createPathAlias(child, key), child, key, SYSTEM_LOCK, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<SystemLockRecord> = SYSTEM_LOCK_PKEY
    override fun `as`(alias: String): SystemLock = SystemLock(DSL.name(alias), this)
    override fun `as`(alias: Name): SystemLock = SystemLock(alias, this)
    override fun `as`(alias: Table<*>): SystemLock = SystemLock(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): SystemLock = SystemLock(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): SystemLock = SystemLock(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): SystemLock = SystemLock(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row8<String?, String?, Boolean?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?> = super.fieldsRow() as Row8<String?, String?, Boolean?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (String?, String?, Boolean?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (String?, String?, Boolean?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
