/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables


import com.kcvn.spm.model.Public
import com.kcvn.spm.model.keys.TAPE_EN_ROUTE_PKEY
import com.kcvn.spm.model.tables.records.TapeEnRouteRecord

import java.time.OffsetDateTime
import java.util.function.Function

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row22
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class TapeEnRoute(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, TapeEnRouteRecord>?,
    aliased: Table<TapeEnRouteRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<TapeEnRouteRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.tape_en_route</code>
         */
        val TAPE_EN_ROUTE: TapeEnRoute = TapeEnRoute()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TapeEnRouteRecord> = TapeEnRouteRecord::class.java

    /**
     * The column <code>public.tape_en_route.id</code>.
     */
    val ID: TableField<TapeEnRouteRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR(50).nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>public.tape_en_route.export_type</code>.
     */
    val EXPORT_TYPE: TableField<TapeEnRouteRecord, String?> = createField(DSL.name("export_type"), SQLDataType.VARCHAR(10).nullable(false), this, "")

    /**
     * The column <code>public.tape_en_route.purchase_order</code>.
     */
    val PURCHASE_ORDER: TableField<TapeEnRouteRecord, String?> = createField(DSL.name("purchase_order"), SQLDataType.VARCHAR(20).nullable(false), this, "")

    /**
     * The column <code>public.tape_en_route.item_code</code>.
     */
    val ITEM_CODE: TableField<TapeEnRouteRecord, String?> = createField(DSL.name("item_code"), SQLDataType.VARCHAR(20), this, "")

    /**
     * The column <code>public.tape_en_route.unit</code>.
     */
    val UNIT: TableField<TapeEnRouteRecord, String?> = createField(DSL.name("unit"), SQLDataType.VARCHAR(20).nullable(false), this, "")

    /**
     * The column <code>public.tape_en_route.description</code>.
     */
    val DESCRIPTION: TableField<TapeEnRouteRecord, String?> = createField(DSL.name("description"), SQLDataType.VARCHAR(50).nullable(false), this, "")

    /**
     * The column <code>public.tape_en_route.spec</code>.
     */
    val SPEC: TableField<TapeEnRouteRecord, String?> = createField(DSL.name("spec"), SQLDataType.VARCHAR(50).nullable(false), this, "")

    /**
     * The column <code>public.tape_en_route.transmit</code>.
     */
    val TRANSMIT: TableField<TapeEnRouteRecord, String?> = createField(DSL.name("transmit"), SQLDataType.VARCHAR(5).nullable(false), this, "")

    /**
     * The column <code>public.tape_en_route.ordered_quantity</code>.
     */
    val ORDERED_QUANTITY: TableField<TapeEnRouteRecord, Int?> = createField(DSL.name("ordered_quantity"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.tape_en_route.delivered_quantity</code>.
     */
    val DELIVERED_QUANTITY: TableField<TapeEnRouteRecord, Int?> = createField(DSL.name("delivered_quantity"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.tape_en_route.response_date</code>.
     */
    val RESPONSE_DATE: TableField<TapeEnRouteRecord, OffsetDateTime?> = createField(DSL.name("response_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

    /**
     * The column <code>public.tape_en_route.tape_lot</code>.
     */
    val TAPE_LOT: TableField<TapeEnRouteRecord, String?> = createField(DSL.name("tape_lot"), SQLDataType.VARCHAR(20), this, "")

    /**
     * The column <code>public.tape_en_route.quantity</code>.
     */
    val QUANTITY: TableField<TapeEnRouteRecord, Int?> = createField(DSL.name("quantity"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.tape_en_route.number_of_boxes</code>.
     */
    val NUMBER_OF_BOXES: TableField<TapeEnRouteRecord, Int?> = createField(DSL.name("number_of_boxes"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.tape_en_route.integration_confirmation</code>.
     */
    val INTEGRATION_CONFIRMATION: TableField<TapeEnRouteRecord, Boolean?> = createField(DSL.name("integration_confirmation"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "")

    /**
     * The column <code>public.tape_en_route.contact_status</code>.
     */
    val CONTACT_STATUS: TableField<TapeEnRouteRecord, String?> = createField(DSL.name("contact_status"), SQLDataType.VARCHAR(20), this, "")

    /**
     * The column <code>public.tape_en_route.created_date</code>.
     */
    val CREATED_DATE: TableField<TapeEnRouteRecord, OffsetDateTime?> = createField(DSL.name("created_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.tape_en_route.created_by</code>.
     */
    val CREATED_BY: TableField<TapeEnRouteRecord, String?> = createField(DSL.name("created_by"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.tape_en_route.updated_date</code>.
     */
    val UPDATED_DATE: TableField<TapeEnRouteRecord, OffsetDateTime?> = createField(DSL.name("updated_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.tape_en_route.updated_by</code>.
     */
    val UPDATED_BY: TableField<TapeEnRouteRecord, String?> = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.tape_en_route.is_deleted</code>.
     */
    val IS_DELETED: TableField<TapeEnRouteRecord, Boolean?> = createField(DSL.name("is_deleted"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "")

    /**
     * The column <code>public.tape_en_route.coupon_code</code>.
     */
    val COUPON_CODE: TableField<TapeEnRouteRecord, String?> = createField(DSL.name("coupon_code"), SQLDataType.VARCHAR(20).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<TapeEnRouteRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<TapeEnRouteRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.tape_en_route</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.tape_en_route</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.tape_en_route</code> table reference
     */
    constructor(): this(DSL.name("tape_en_route"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, TapeEnRouteRecord>): this(Internal.createPathAlias(child, key), child, key, TAPE_EN_ROUTE, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<TapeEnRouteRecord> = TAPE_EN_ROUTE_PKEY
    override fun `as`(alias: String): TapeEnRoute = TapeEnRoute(DSL.name(alias), this)
    override fun `as`(alias: Name): TapeEnRoute = TapeEnRoute(alias, this)
    override fun `as`(alias: Table<*>): TapeEnRoute = TapeEnRoute(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): TapeEnRoute = TapeEnRoute(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): TapeEnRoute = TapeEnRoute(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): TapeEnRoute = TapeEnRoute(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row22 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row22<String?, String?, String?, String?, String?, String?, String?, String?, Int?, Int?, OffsetDateTime?, String?, Int?, Int?, Boolean?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?, String?> = super.fieldsRow() as Row22<String?, String?, String?, String?, String?, String?, String?, String?, Int?, Int?, OffsetDateTime?, String?, Int?, Int?, Boolean?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?, String?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (String?, String?, String?, String?, String?, String?, String?, String?, Int?, Int?, OffsetDateTime?, String?, Int?, Int?, Boolean?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?, String?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (String?, String?, String?, String?, String?, String?, String?, String?, Int?, Int?, OffsetDateTime?, String?, Int?, Int?, Boolean?, String?, OffsetDateTime?, String?, OffsetDateTime?, String?, Boolean?, String?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
