/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.tables


import com.kcvn.spm.model.Public
import com.kcvn.spm.model.keys.TEMP_CHECKING_IMPORTED_DATE_PKEY
import com.kcvn.spm.model.tables.records.TempCheckingImportedRecord

import java.math.BigDecimal
import java.time.OffsetDateTime
import java.util.function.Function

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row8
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class TempCheckingImported(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, TempCheckingImportedRecord>?,
    aliased: Table<TempCheckingImportedRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<TempCheckingImportedRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.temp_checking_imported</code>
         */
        val TEMP_CHECKING_IMPORTED: TempCheckingImported = TempCheckingImported()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TempCheckingImportedRecord> = TempCheckingImportedRecord::class.java

    /**
     * The column <code>public.temp_checking_imported.id</code>.
     */
    val ID: TableField<TempCheckingImportedRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR(50).nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>public.temp_checking_imported.po_number</code>.
     */
    val PO_NUMBER: TableField<TempCheckingImportedRecord, String?> = createField(DSL.name("po_number"), SQLDataType.VARCHAR(30).nullable(false), this, "")

    /**
     * The column <code>public.temp_checking_imported.qty</code>.
     */
    val QTY: TableField<TempCheckingImportedRecord, BigDecimal?> = createField(DSL.name("qty"), SQLDataType.NUMERIC, this, "")

    /**
     * The column <code>public.temp_checking_imported.created_date</code>.
     */
    val CREATED_DATE: TableField<TempCheckingImportedRecord, OffsetDateTime?> = createField(DSL.name("created_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.temp_checking_imported.created_by</code>.
     */
    val CREATED_BY: TableField<TempCheckingImportedRecord, String?> = createField(DSL.name("created_by"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.temp_checking_imported.updated_date</code>.
     */
    val UPDATED_DATE: TableField<TempCheckingImportedRecord, OffsetDateTime?> = createField(DSL.name("updated_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.temp_checking_imported.updated_by</code>.
     */
    val UPDATED_BY: TableField<TempCheckingImportedRecord, String?> = createField(DSL.name("updated_by"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.temp_checking_imported.form_code</code>.
     */
    val FORM_CODE: TableField<TempCheckingImportedRecord, String?> = createField(DSL.name("form_code"), SQLDataType.VARCHAR(12), this, "")

    private constructor(alias: Name, aliased: Table<TempCheckingImportedRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<TempCheckingImportedRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.temp_checking_imported</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.temp_checking_imported</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.temp_checking_imported</code> table reference
     */
    constructor(): this(DSL.name("temp_checking_imported"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, TempCheckingImportedRecord>): this(Internal.createPathAlias(child, key), child, key, TEMP_CHECKING_IMPORTED, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<TempCheckingImportedRecord> = TEMP_CHECKING_IMPORTED_DATE_PKEY
    override fun `as`(alias: String): TempCheckingImported = TempCheckingImported(DSL.name(alias), this)
    override fun `as`(alias: Name): TempCheckingImported = TempCheckingImported(alias, this)
    override fun `as`(alias: Table<*>): TempCheckingImported = TempCheckingImported(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): TempCheckingImported = TempCheckingImported(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): TempCheckingImported = TempCheckingImported(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): TempCheckingImported = TempCheckingImported(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row8<String?, String?, BigDecimal?, OffsetDateTime?, String?, OffsetDateTime?, String?, String?> = super.fieldsRow() as Row8<String?, String?, BigDecimal?, OffsetDateTime?, String?, OffsetDateTime?, String?, String?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (String?, String?, BigDecimal?, OffsetDateTime?, String?, OffsetDateTime?, String?, String?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (String?, String?, BigDecimal?, OffsetDateTime?, String?, OffsetDateTime?, String?, String?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
