ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/proxy-body-size: "50M"
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false
image:
  repository: <image_version>
  tag: <image_tag_version>
  secrets:
    - name: registry
service:
  url: <environment-url>  
  controller_segment: <controller_segment>
  externalPort: 8080
  internalPort: 8080
persistence:
  enabled: false