package com.kcvn.spm.common.constants

class KeyAppSetting {
    companion object {
        //Scheduler
        const val SCHEDULER_PROCESS_PROCEDURE_STRUCTURE = "SCHEDULER_PROCESS_PROCEDURE_STRUCTURE"
        const val SCHEDULER_PROCESS_MASTER = "SCHEDULER_PROCESS_MASTER"
        const val SCHEDULER_WORK_RESULT_START = "SCHEDULER_WORK_RESULT_START"
        const val SCHEDULER_WORK_RESULT_END = "SCHEDULER_WORK_RESULT_END"
        const val WORK_RESULT = "WORK_RESULT"

        const val WORK_RESULT_LIMIT_RECORD = "WORK_RESULT_LIMIT_RECORD"

        const val DATE_SYNC_DATA_FROM_TRANS_AM = "DATE_SYNC_DATA_FROM_TRANS_AM"

        //Mold by frame1
        const val MOLD_BY_FRAME1 = "MOLD_BY_FRAME1"

        //Path config
        const val PATH_HISTORY_PLAN = "PATH_HISTORY_PLAN"

        const val CHECK_EXCEPTION_INVENTORY_DATE_WHEN_CREATE_PLAN = "CHECK_EXCEPTION_INVENTORY_DATE_WHEN_CREATE_PLAN"

        const val APPLY_EQUIPMENT_PRODUCTIVITY_WHEN_CREATE_PLAN = "APPLY_EQUIPMENT_PRODUCTIVITY_WHEN_CREATE_PLAN"
    }
}