DROP TABLE public.work_result;

CREATE TABLE work_result (
    id varchar(50) NOT NULL DEFAULT gen_random_uuid(),
    object_id INT NOT NULL,
    android_id varchar(10),
    description varchar(75),
    grp_departments VARCHAR(5) NOT NULL,
    department_code varchar(10),
    department_name varchar(45),
    order_code varchar(9),
    code varchar(14) NOT NULL,
    customer_code varchar(8),
    item_code varchar(38),
    item_name varchar(100),
    layer_code varchar(2),
    process_code varchar(6) not null,
    process_grp varchar(5),
    process_name varchar(60),
    process_type varchar(1),
    equipment_code varchar(10),
    equipment_name varchar(45),
    tape_lot_no varchar(21),
    completion_type varchar(1),
    seiden_no varchar(11),
    version varchar(2) not null,
    furimukou_type varchar(1),
    is_exclusive_or_exception INT,
    excess_fraction int,
    direction varchar(1),
    item_quantity int,
    shipment_status varchar(1),
    actual_result_code varchar(10),
    actual_result_department varchar(5),
    summary_result_date timestamp,
    enter_actual_result_type varchar(1),
    actual_result_type varchar(1),
    project_check_1 varchar(45),
    project_check_2 varchar(45),
    project_check_3 varchar(45),
    company_code varchar(5) not null,
    work_start_by varchar(10),
    manager_code varchar(10),
    conversion_factor DECIMAL(8,3),
    lon_quantity int,
    furimukou_quantity int,
    error_item_quantity int,
    hifurimukou_quantity int,
    inventory_item_quantity int,
    good_item_quantity int,
    regenerative_item_quantity int,
    total_item_quantity int,
    adjustment_item_quantity int,
    furimukou_tape_quantity int,
    error_tape_quantity int,
    hifurimukou_tape_quantity int,
    inventory_tape_quantity int,
    good_tape_quantity int,
    regenerative_tape_quantity int,
    total_tape_quantity int,
    adjustment_tape_quantity int,
    furimukou_sheet_quantity int,
    error_sheet_quantity int,
    hifurimukou_sheet_quantity int,
    inventory_sheet_quantity int,
    good_sheet_quantity int,
    regenerative_sheet_quantity int,
    total_sheet_quantity int,
    adjustment_sheet_quantity int,
    shift_work varchar(4),
    input_unit varchar(1),
    work_code_1 varchar(5),
    work_code_2 varchar(5),
    work_code_3 varchar(5),
    work_date timestamp,
    work_time timestamp,
    work_start_date timestamp,
    work_start_time timestamp,
    work_end_time timestamp,
    work_end_date timestamp,
    work_place_code varchar(5),
    work_place_name varchar(45),
    team varchar(3),
    memo_work varchar(45),
    work_type varchar(8),
    work_implement_by varchar(10),
    regenerative_code varchar(4),
    regenerative_type varchar(1),
    regenerative_name varchar(15),
    regenerative_process_code varchar(6),
    regenerative_process_name varchar(45),
    made_in varchar(5),
    sheet_flag varchar(1),
    unfinished_quantity int,
    remediation_directive_number varchar(4),
    deliver_lot_no varchar(10),
    end_date timestamp,
    total int,
    price decimal(11,2),
    special_item varchar(75),
    created_date timestamp not null DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    updated_date timestamp,
    updated_by varchar(100),
    is_deleted boolean NOT NULL DEFAULT false,

    CONSTRAINT work_result_pkey PRIMARY KEY (id)
);