CREATE TABLE sync_history
(
    id VARCHAR NOT NULL DEFAULT GEN_RANDOM_UUID(),
    source VARCHAR(100),
    destination VARCHAR(100),
    type VARCHAR(100),
    created_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR NOT NULL,
    updated_date TIMESTAMP WITH TIME ZONE,
    updated_by VARCHAR,
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT sync_history_pkey PRIMARY KEY (id)
);

CREATE TABLE process_procedure_structure
(
    id VARCHAR(50) NOT NULL DEFAULT GEN_RANDOM_UUID(),
    object_id INT NOT NULL,
    company_code VARCHAR(5) NOT NULL,
    grp_departments VARCHAR(5) NOT NULL,
    remediation_directive_number VARCHAR(4) NOT NULL,
    product_code VARCHAR(38) NOT NULL,
    layer_code VARCHAR(2) NOT NULL,
    stage_code VARCHAR(6) NOT NULL,
    stage_sequence INT,
    stage_sequence_rev INT NOT NULL,
    machining_sequence_rev VARCHAR(3),
    completion_rate DECIMAL(5,4),
    finished_product_rate DECIMAL(5,4),
    print_type VARCHAR(1),
    stage_type VARCHAR(1),
    display_stage_sequence INT,
    input_system VARCHAR(1),
    is_actual_result VARCHAR(1),
    shipment_size INT,
    conversion_factor DECIMAL(8,3),
    unit_conversion_factor VARCHAR(2),
    conversion_factors_error_type VARCHAR(1),
    conversion_factor_adjustment_type VARCHAR(1),
    plan_lead_time_normally DECIMAL(5,2),
    work_lead_time_normally DECIMAL(5,2),
    transport_lead_time_normally DECIMAL(5,2),
    plan_lead_time_urgently DECIMAL(5,2),
    work_lead_time_urgently DECIMAL(5,2),
    transport_lead_time_urgently DECIMAL(5,2),
    backlog_type VARCHAR(1),
    unfinished_product_quantity INT,
    standard_procedure_type VARCHAR(1),
    grp_check_process VARCHAR(5),
    register_by VARCHAR(20),
    register_date TIMESTAMP,
    update_by VARCHAR(20),
    update_date TIMESTAMP,
    is_exclusive_or_exception INT,
    workplace_code VARCHAR(5),
    CONSTRAINT process_procedure_structure_pkey PRIMARY KEY (id)
);