CREATE TABLE product_process (
	id varchar(50) NOT NULL DEFAULT gen_random_uuid(),
	product_name varchar(30) NOT NULL,
	layer_code varchar(2) NOT NULL,
	process_code varchar(30) NOT NULL,
	process_name varchar(100),
	process_name_jp varchar(100),
	process_convert_code varchar(10),
	process_statistic_code varchar(10),
	process_inventory_code varchar(10),
	created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	created_by varchar(100) NULL,
	updated_date TIMESTAMP NULL,
	updated_by varchar(100) NULL,
	is_deleted boolean NOT NULL DEFAULT false,
	CONSTRAINT product_process_pkey PRIMARY KEY (id)
);

CREATE UNIQUE INDEX idx_unique_product_process ON product_process (product_name, process_code, layer_code);

CREATE TABLE process_master (
	id varchar(50) NOT NULL DEFAULT gen_random_uuid(),
	object_id INT NOT NULL,
    company_code VARCHAR(5) NOT NULL,
    grp_departments VARCHAR(5) NOT NULL,
    process_code VARCHAR(6) NOT NULL,
    process_name varchar(60),
    process_name_jp varchar(100),
    grp_process varchar(5),
    grp_process_summary varchar(5),
    product_rate_by_material decimal(5,2),
    completion_rate decimal(5,4),
    input_system varchar(2),
    is_actual_result varchar(1),
    office_code varchar(3),
    shipment_size INT,
    conversion_factor DECIMAL(8,3),
    unit_conversion_factor VARCHAR(2),
    conversion_factors_error_type VARCHAR(1),
    conversion_factor_adjustment_type VARCHAR(1),
    plan_lead_time_normally DECIMAL(5,2),
    work_lead_time_normally DECIMAL(5,2),
    transport_lead_time_normally DECIMAL(5,2),
    plan_lead_time_urgently DECIMAL(5,2),
    work_lead_time_urgently DECIMAL(5,2),
    transport_lead_time_urgently DECIMAL(5,2),
    product_rate_by_material_setting DECIMAL(5,4),
    backlog_type VARCHAR(1),
    unfinished_product_quantity INT,
    print_type VARCHAR(1),
    unfinished_procedure_type VARCHAR(1),
    standard_procedure_type VARCHAR(1),
    check_process_code varchar(5),
    actual_result_type varchar(1),
    lead_time_min decimal(3,2),
    ws_type varchar(1),
    ws_code varchar(10),
    persons INT,
    work_time varchar(2),
    grp_quantity INT,
    unit varchar(1),
    neck_flag varchar(1),
    planned_process_code varchar(6),
    grp_actual_result varchar(4),
    grp_capital_price varchar(5),
    register_by VARCHAR(20),
    register_date TIMESTAMP,
    update_by VARCHAR(20),
    update_date TIMESTAMP,
    is_exclusive_or_exception INT,
    workplace_code VARCHAR(5),
	CONSTRAINT process_master_pkey PRIMARY KEY (id)
);

CREATE TABLE work_result (
    id varchar(50) NOT NULL DEFAULT gen_random_uuid(),
    object_id INT NOT NULL,
    android_id varchar(10),
    description varchar(75),
    grp_departments VARCHAR(5) NOT NULL,
    department_code varchar(10),
    department_name varchar(45),
    order_code varchar(9),
    code varchar(14) NOT NULL,
    customer_code varchar(8),
    item_code varchar(38),
    item_name varchar(100),
    layer_code varchar(2),
    process_code varchar(6) not null,
    process_grp varchar(5),
    process_name varchar(60),
    process_type varchar(1),
    equipment_code varchar(10),
    equipment_name varchar(45),
    tape_lot_no varchar(21),
    register_date timestamp,
    completion_type varchar(1),
    seiden_no varchar(11),
    version varchar(2) not null,
    furimukou_type varchar(1),
    furimukou_quantity int,
    product_error_quantity int,
    is_exclusive_or_exception INT,
    excess_fraction int,
    hifurimukou_quantity int,
    direction varchar(1),
    item_quantity int,
    inventory_quantity int,
    shipment_status varchar(1),
    actual_result_code varchar(10),
    actual_result_department varchar(5),
    summary_result_date timestamp,
    enter_actual_result_type varchar(1),
    actual_result_type varchar(1),
    project_check_1 varchar(45),
    project_check_2 varchar(45),
    project_check_3 varchar(45),
    company_code varchar(5) not null,
    work_start_by varchar(10),
    lon_quantity int,
    manager_code varchar(10),
    conversion_factor DECIMAL(8,3),
    furimukou_tape_quantity int,
    error_tape_quantity int,
    hifurimukou_tape_quantity int,
    inventory_tape_quantity int,
    good_tape_quantity int,
    regenerative_tape_quantity int,
    total_tape_quantity int,
    adjustment_tape_quantity int,
    error_sheet_quantity int,
    furimukou_sheet_quantity int,
    hifurimukou_sheet_quantity int,
    inventory_sheet_quantity int,
    good_sheet_quantity int,
    regenerative_sheet_quantity int,
    total_sheet_quantity int,
    adjustment_sheet_quantity int,
    shift_work varchar(4),
    update_date timestamp,
    update_by varchar(20),
    input_unit varchar(1),
    good_product_quantity int,
    work_code_1 varchar(5),
    work_code_2 varchar(5),
    work_code_3 varchar(5),
    work_date timestamp,
    work_start_date timestamp,
    work_start_time timestamp,
    work_end_time timestamp,
    work_end_date timestamp,
    work_time timestamp,
    work_place_code varchar(5),
    work_place_name varchar(45),
    team varchar(3),
    memo_work varchar(45),
    work_type varchar(8),
    work_implement_by varchar(10),
    regenerative_code varchar(4),
    regenerative_type varchar(1),
    regenerative_name varchar(15),
    regenerative_process_code varchar(6),
    regenerative_process_name varchar(45),
    made_in varchar(5),
    sheet_flag varchar(1),
    unfinished_quantity int,
    remediation_directive_number varchar(4),
    deliver_lot_no varchar(10),
    end_date timestamp,
    total int,
    price decimal(11,2),
    special_item varchar(75),
    register_by varchar(20),

    CONSTRAINT work_result_pkey PRIMARY KEY (id)
);
