/*
 * This file is generated by jOOQ.
 */
package com.kcvn.spm.model.indexes


import com.kcvn.spm.model.tables.CommonCategory
import com.kcvn.spm.model.tables.CompletionRateProcess
import com.kcvn.spm.model.tables.CompletionRateProcessProduct
import com.kcvn.spm.model.tables.CompletionRateProduct
import com.kcvn.spm.model.tables.Product

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val IDX_UNIQUE_COMPLETION_RATE_PROCESS: Index = Internal.createIndex(DSL.name("idx_unique_completion_rate_process"), CompletionRateProcess.COMPLETION_RATE_PROCESS, arrayOf(CompletionRateProcess.COMPLETION_RATE_PROCESS.KEY, CompletionRateProcess.COMPLETION_RATE_PROCESS.PROCESS_CODE, CompletionRateProcess.COMPLETION_RATE_PROCESS.LAYER_CODE), true)
val IDX_UNIQUE_COMPLETION_RATE_PROCESS_PRODUCT: Index = Internal.createIndex(DSL.name("idx_unique_completion_rate_process_product"), CompletionRateProcessProduct.COMPLETION_RATE_PROCESS_PRODUCT, arrayOf(CompletionRateProcessProduct.COMPLETION_RATE_PROCESS_PRODUCT.KEY, CompletionRateProcessProduct.COMPLETION_RATE_PROCESS_PRODUCT.PRODUCT_NAME_SHORTCUT, CompletionRateProcessProduct.COMPLETION_RATE_PROCESS_PRODUCT.PROCESS_CODE, CompletionRateProcessProduct.COMPLETION_RATE_PROCESS_PRODUCT.LAYER_CODE), true)
val IDX_UNIQUE_COMPLETION_RATE_PRODUCT: Index = Internal.createIndex(DSL.name("idx_unique_completion_rate_product"), CompletionRateProduct.COMPLETION_RATE_PRODUCT, arrayOf(CompletionRateProduct.COMPLETION_RATE_PRODUCT.PRODUCT_NAME), true)
val IDX_UNIQUE_PRODUCT_NAME: Index = Internal.createIndex(DSL.name("idx_unique_product_name"), Product.PRODUCT, arrayOf(Product.PRODUCT.NAME), true)
val IDX_UNIQUE_TYPE_VALUE: Index = Internal.createIndex(DSL.name("idx_unique_type_value"), CommonCategory.COMMON_CATEGORY, arrayOf(CommonCategory.COMMON_CATEGORY.TYPE, CommonCategory.COMMON_CATEGORY.VALUE), true)
